### ISSUE TITLE
Rewrite SpotCrap()

### ISSUE THREAD

**Issue by willglynn** [raceintospace/raceintospace#114]
This function has several problems:
- I don't understand it
- It uses a weird `SPOTS.CDR` file
- It uses `vhptr`
- There's a ton of magic numbers
- `clang` says it can find a crash bug 27 steps deep, and while it might be wrong, I'm just not sure

![Screen Shot 2013-01-29 at 10 23 36 AM](https://f.cloud.github.com/assets/118362/107614/2a66d948-6a31-11e2-9c6e-4494c23e863f.png)

**Comment by rnyoakum** [comment]
I'm not sure this is entirely fixed, but IMO #800 makes the spaceport animation code far more readable than before. The code is split into component functions, variables have meaningful names, and I even tweaked the algorithm to slightly improve it.

**Comment by sflynn850** [comment]
Seems like a good candidate for closure.

**Comment by sflynn850** [comment]
Closing this — if we come up with more enhancements, let's make a new ticket and link it back to this one in the description.
