### ISSUE TITLE
Move the AI into Lua

### ISSUE THREAD

**Issue by mkmccarty** [raceintospace/raceintospace#117]

**Comment by sflynn850** [comment]
This ticket is coming up on its 11th birthday, but didn't get any comments — is there still an appetite for doing this?

**Comment by peyre** [comment]
Now this one I have _no_ idea.  I never understood what it was for or about.  This was created by BARIS's original programmer, so it must have been something he had in mind but never got to.  If there's no need to mess with Lua, then yes we should jettison this one.

**Comment by sflynn850** [comment]
Works for me. Adios, Lua!

**Comment by sflynn850** [comment]
Won't do.
