### ISSUE TITLE
Game does not build on Debian testing

### ISSUE THREAD

**Issue by tdi** [raceintospace/raceintospace#132]
When building src code from the web page (not git) for testing I get:

ld ...flags... -o raceintospace ...libs...
/usr/bin/ld: Warning: size of symbol `table' changed from 792 in news.o to 408 in //usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-5.0.so
/usr/bin/ld: news.o: undefined reference to symbol 'table'
//usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-5.0.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:98: recipe for target 'raceintospace' failed
make: **\* [raceintospace] Error 1

gcc 4.8.2-4
libsdl 2.12
libogg 3.1
pulse 5.0

I think it is because pulseaudio also has a table exported.

**Comment by rnyoakum** [comment]
Does anyone with a Debian build know if there are any difficulties building the git code under Debian at this time?

**Comment by tdi** [comment]
hey I do no longer actively support this unfortunately

**Comment by peyre** [comment]
I assume you mean non-Ubuntu Debian?  I'm able to compile it just fine in Xubuntu, once I install the prerequisites.

**Comment by mnalis** [comment]
I can confirm that  latest master (b0e0a5a3e204ac3171c3cdb736c0c2080021b4c0) builds fine on Debian Bullseye (current stable)

**Comment by peyre** [comment]
Thank you Matija!  Good to know.  I think it can be compiled in Windows now too, with some fidgeting.

**Comment by sflynn850** [comment]
Closing issue per @mnalis's 19 Mar 22 comment.
