### ISSUE TITLE
[Wishlist] Tag releases on github

### ISSUE THREAD

**Issue by tdi** [raceintospace/raceintospace#136]
This is a wishlist like issue. It would be great that you tag releases on github. It would be great for Debian packaging and checking the newest version automatically with uscan (Debian dev tool). 

Also it would be good for providing a get-import-orig target in debian/rules that automatically downloads the upstream source tarballs to Debian. 

It will also help with consitency. Currently the tarball on the web page is not consistent with the git repo. With git tagging you could just point to tarballs from github on your web page.

**Comment by bentley** [comment]
It would be nice to have a more recent release. The last Sourceforge release has several portability issues that make it difficult to package, and they appear to have been fixed in Git.

**Comment by akien-mga** [comment]
It would be great to have *old* releases tagged in this git repository too, for the sake of history and traceability, and to see how much development has been made since the last SourceForge release.

**Comment by ryandesign** [comment]
This ticket has been open for years. Why has this not been done yet? Please tag all of your past releases.

**Comment by pemensik** [comment]
I think it has easy explanation. It is somehow hard to mark released sources in git repository. I don't know how to work with previous CVS. But it seems to me if was never marked, which commit version was then released in release tarball. I think exactly same commit does not exist in git. It would be very distant from the code today.

**Comment by pemensik** [comment]
I have attempted to import somehow a history of releases. I didn't know old releases are THAT old. It seems 1.1 release did not even converted to C++, which was done seven years ago. Released sources seem to predate start of git repository. I made history branch with tags v1.0 and v1.1. We should make release soon. Previous release is way different than current code.

**Comment by peyre** [comment]
Yes!  I agree Petr - we're making some really good changes to RIS right now, but I've been itching for us to put out a release in the interim so people can enjoy the improvements we've made (so far) without having to compile it from code.

You're correct, RIS was converted from c to c++ when it was brought over to GitHub.

**Comment by pemensik** [comment]
Okay, in that case, I think next version should not be 1.2, but instead 2.0. If it had so many changes, it should be obvious from version as well. Though I admit it does not have many visible gameplay changes for that.

**Comment by peyre** [comment]
I wouldn't object to that.  We could name it 2.0 if you think that's more appropriate.

It would also reflect the fact that it's the first release since 2013, and that the code has moved from Sourceforge to GitHub and been ported from c to c++.

**Comment by sflynn850** [comment]
We now have 9 tags representing a bunch of releases or release candidates; closing ticket.
