### ISSUE TITLE
Warning - missing file

### ISSUE THREAD

**Issue by bmoscon** [raceintospace/raceintospace#151]
Warning when starting game:

```
WARNING raceintospace/src/game/fs.cpp:273:try_find_file	can't find file `moon_32x32.bmp' in image dir(s)
```

**Comment by peyre** [comment]
Oh!  That's just the moon icon.  Here's a copy.
 

    On Friday, May 4, 2018, 1:43:24 PM PDT, Bryant Moscon <notifications@github.com> wrote:  
 
 
Warning when starting game:
WARNING raceintospace/src/game/fs.cpp:273:try_find_file	can't find file `moon_32x32.bmp' in image dir(s)

**Comment by peyre** [comment]
I've retrieved a copy of the bitmap from the CVS code and have uploaded it to here.  Should be good now.

**Comment by peyre** [comment]
It should be in data/images.
