### ISSUE TITLE
SERVICE category

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#165]
The recruitment screen shows a line for SERVICE, which seems to be intended to show where a candidate comes from: USAF, Marines, Navy, etc.  It's always blank though, so I presume this was a feature they never actually implemented in the game.  If we do set up the game to handle service, someone will have to research the 'naut roster and figure out how to mark everyone.  I can do that easily enough.  

Civilian candidates will be a little tricky.  Armstrong, for instance, might show as "NASA Engineer", and Feoktistov as "OKB-1" or "OKB-1 Engineer".  Most of the Mercury 13 might be "Freelance Pilot" and Tereshkova would probably be "Factory Worker".

**Comment by peyre** [comment]
Having looked closely at the hex files, I see there's currently no space in there for the Service category, so this will probably have to wait until crew.dat and user.dat are converted to plain text files.

**Comment by peyre** [comment]
I just found an interesting tidbit.  In news.suq.cpp, when the newscast gives you three air force pilots, it assigns them stats (face, compatibility, etc.), including the following:

** Data->P[plr].Pool[Data->P[plr].AstroCount].Service = 1;**

So Service was to be a number.  I suppose 1 meant Air Force.

**Comment by peyre** [comment]
I don't know why I didn't think of it earlier--maybe 0 is civilian, which would be logical: not in a service.  Then AF, Navy, Marine Corps.  I may add a 4 if any of the cosmonauts came from Artillery or something.

**Comment by peyre** [comment]
So I see that the Soviets at the time had several separate services.  The ones that concern us are:
VVS: the Air Force, including subdivisions such as Long-Range Aviation
RSVN: the Strategic Rocket Force, which grew out of Artillery
VMF: Military Marine Force, Navy

Looks like the numbers might need to be: 
0 Civilian
1 Air Force
2 Navy
3 Marine Corps
4 Strategic Rocket Force (maybe shortened to "Rocket Force")

Also, I see two of the Group V cosmonauts were recruited for **Buran** in 1977: Borodai and Bachurin.  I suppose we could replace them with cosmonauts from earlier groups, such as Romanenko and Sologub, but that might not be worth the effort.

**Comment by peyre** [comment]
Well I got excited about this last weekend.  I added **"service": 1,** lines to roster.json and **"Service": 1,** lines to crew.json for the Mercury 7, just for testing.  To data.h I added ar(CEREAL_NVP(Service)); under ARCHIVE_STRING(Name); and struct ManPool now reads int8_t Sex, Service, Cap, LM, EVA, Docking, Endurance;
I also added this to ast1.cpp starting on line 161:
            switch (Men[now].Service) {
            case 0:
                draw_string(227, 61, "CIVILIAN");
                break;
            case 1:
                draw_string(227, 61, "AIR FORCE");
                break;
            case 2:
                draw_string(227, 61, "NAVY");
                break;
            case 3:
                draw_string(227, 61, "MARINE CORPS");
                break;
            case 4:
                draw_string(227, 61, "S. ROCKET FORCE");
                break;
            case 5:
                draw_string(227, 61, "AIR DEF. FORCE");
                break;
            }

and this under void Recruit
    recruit.Service = Men[candidate].Service;

But Service is coming back all zeroes so everyone shows as a civilian.  _Figures_ this wouldn't be as simple as I thought.

![Service](https://github.com/raceintospace/raceintospace/assets/3118014/cad270cf-d474-4dcf-9710-0b5940f87766)

**Comment by hweimer** [comment]
I think the display code has to go into DrawRecruitProfile(), where there is already a placeholder for service information.

**Comment by peyre** [comment]
But...I think that's where I put it.

**Comment by hweimer** [comment]
Hmm, I followed your instructions (except for plugging into the existing placeholder) and it seems to work fine ...

![t](https://github.com/raceintospace/raceintospace/assets/68769393/a22ccc95-0fc4-4532-a80d-93d509343d36)

I will prepare a PR so you can use that.

**Comment by peyre** [comment]
Hot damn!  I don't know what I did wrong.  Thanks!  I'll update the roster in a bit to assign Service to all the candidates.

**Comment by peyre** [comment]
Ah, I have a question on this...several cosmonaut candidates were from the Intercosmos program, where the USSR recruited people from other countries: Gurragchaa (Mongolia), Remek (Czechoslovakia), Jaehn (E. Germany), Tuan (Vietnam), all in Group IV and all from their own countries' Air Force.  I wonder if I should count them as Air Force, or add a 6th category for Intercosmos so a Soviet player would have a heads-up that they're from other countries.

**Comment by hweimer** [comment]
Ah, good point! I wasn't even aware that we had them, which I also find a bit odd, given they were selected much later historically. We could maybe have a FOREIGN service category, which could also be used in case we want to add the 1978 ESA group on the U.S. side. We could even add a prestige category for the first foreign crew member.

**Comment by peyre** [comment]
Foreign?  That's an idea.  That's general enough it could also apply to two of the astronauts: Llewellyn (UK) and Chapman (Australia) - though Chapman was a US citizen by the time he was selected.

**Comment by hweimer** [comment]
Llewellyn also became a naturalized citizen prior to being selected: https://www.newspapers.com/article/muncie-evening-press/30779535/

But I guess for them, or for the 1978 ESA group, FOREIGN would not make sense as a service category because they were civilians when they were selected. That's different than the Intercosmos folks.

**Comment by peyre** [comment]
Good points!  So you think they should be marked **Foreign**, rather than **Intercosmos** or **Air Force**?

**Comment by hweimer** [comment]
Well, Intercosmos does not really fit as a service category, as this was not a multinational force but a cooperation framework. Air Force is also a bit misleading since the whole point about the selection of these cosmonauts was that they were coming from a different country. Hence, I'd go with Foreign, but I'm also open to other suggestions.

**Comment by peyre** [comment]
That's logical.  I'll go with Foreign for now; we can always change it later if we think of something better.

**Comment by peyre** [comment]
Uh oh!  Something seems to have gotten messed up.  During testing, I found the Soviet cosmonaut candidates were all American!  (Also, how do I add FOREIGN in ast1.cpp?)

![UScosmonauts](https://github.com/raceintospace/raceintospace/assets/3118014/0a4ac1ba-af0c-45a2-9072-cf787a28957f)

**Comment by peyre** [comment]
Uh oh!  It's actually a bit worse now.
![NoCosmonauts](https://github.com/raceintospace/raceintospace/assets/3118014/0e2f7eef-05cc-44ca-8965-dda3ad5643b6)

When I scroll down the game crashes, with error

`unhandled exception: array::at: __n (which is 18446744073709551571) >= _Nm (which is 7)
Aborted (core dumped)
`

**Comment by hweimer** [comment]
Sorry for that. I had only tested the first cosmonaut group, but later groups can move the roster index beyond 127, causing some 8-bit variables to overflow.

**Comment by peyre** [comment]
Not a big deal really.  But it's still crashing--now it crashes before I get to see the recruitment screen.

`unhandled exception: array::at: __n (which is 80) >= _Nm (which is 7)
Aborted (core dumped)
`

**Comment by hweimer** [comment]
This is odd. I completed a game going all the way to group V and didn't notice any errors. Did you start a fresh game or was this when loading a saved game?

(Funnily, after clicking my way up to group IV, I decided to do something with the 600 MB I was sitting on and prototyped the direct ascent kit. I won the game in 1971 despite getting the "your capsule sucks" newscast in between.)

**Comment by peyre** [comment]
Huh!  I downloaded the game fresh and compiled.  It aborts and dumps as soon as I say Yes to recruit.  Maybe it's because the autosave I'm using is in Group III on the USSR side?

**Comment by hweimer** [comment]
Can you send me the autosave file?

**Comment by peyre** [comment]
Uh oh!  I think I was using the autosave, and it's been overwritten now.  I've actually run into a different issue: people's service shows correctly now, but there's some problem with the number recruited.  For Group II, I don't have as many candidates as I should.

![TooFewCosmonauts](https://github.com/raceintospace/raceintospace/assets/3118014/a394a7b1-820b-48ad-a285-bde0190cecbb)

**Comment by hweimer** [comment]
This is what is supposed to be fixed by #831 (and I guess that your autosave had a similar problem).

**Comment by peyre** [comment]
Oops!  I hadn't merged 831 yet!

**Comment by peyre** [comment]
Ah yes, that did it!  Thanks.  

![MoreNauts](https://github.com/raceintospace/raceintospace/assets/3118014/a649ae92-c6e9-436b-aed1-8f1033ff920c)

**Comment by hweimer** [comment]
Many thanks for your hard work in digging out all the service information! However, I saw that John Glenn got assigned a Sex value of 3. While I appreciate your efforts in bringing non-binary astronauts to the game, I feel it is not 100% historically accurate. :smile: 

![t](https://github.com/raceintospace/raceintospace/assets/68769393/36c58d9f-2071-4c93-a427-ec24164dfa1d)

**Comment by peyre** [comment]
Uh oh!  Looks like I assigned his Sex rather than his Service.  I wouldn't be surprised if I made more than one of these boo-boos; I'll fix him.

**Comment by hweimer** [comment]
Don't worry, there are no other persons with Sex > 1 and those with Sex =  1 are the correct ones.

**Comment by peyre** [comment]
Oh!  Yes, I'll close it.
