### ISSUE TITLE
End-of-Turn Warnings

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#166]
I think a big help in playing the game would be if End of Turn had some warnings that can pop up.

(Items struck through have been implemented or mooted.)

1)  <s>Starting after your first turn (i.e. in Fall 1957), if you have no launches scheduled for next turn, you should be informed and given a chance to go back and schedule one.  I can't count how many times I've ended a turn, forgetting to have scheduled a launch or two for next turn.</s>

2)  <s>If you have a mission ready to launch and one of its components isn't yet at Max R&D, you should be warned so you can go back to research it if you choose. The warning should appear only if you have enough funds to do some research. So for instance, if you have 2MB left and the component that needs research is an Atlas, you should be warned--but not if you had 2MB and it was the Saturn V that needed research.  (This might be better placed in the VAB/VIB.)</s>

3)  <s>If you have an LM or a Kicker-C and it's above its starting Safety, but haven't prototyped your docking modules yet, the game should probably warn you.  (Come to think of it, Hardware Purchase or R&D might be a better place for this warning.)</s>

4)  <s>Similarly, if you have an LM or a Kicker-C and it's above its starting Safety, but haven't prototyped EVA suits, you should probably receive a warning (again, possibly in Purchasing or Research).</s>

5)  <s>If you have a lunar mission ready to go (or even assembled) and the capsule/shuttle isn't at Max Safety, you should be warned.  This would be especially helpful if you've had a catastrophic failure but got distracted and didn't go research that part this turn.  (This might be more appropriate for Mission Control.)</s>

6)  <s>If you have a Manned Orbital or any EVA mission planned for next turn but haven't started the EVA suit program, you should be warned. (Never mind, this is prevented in Future Missions: it doesn't let you schedule an EVA mission if you haven't started an EVA program.)</s>

This sort of thing would be a nice continuation of my goal when I added a whole bunch of visual cues to the game in version .4.8 - to make this something you can play more casually.  BARIS was the sort of game you really had to focus on; you had to keep a whole bunch of things straight in your head all the time, and it was really easy to miss something if you weren't paying very close attention.  The game has been made much more playable off the cuff, yet because there's no visual cue for launches, I still frequently end my turn forgetting to schedule missions for the next turn.

**Comment by peyre** [comment]
Hey, I managed to partly accomplish 1 above.  Except on the first turn of the game, when you click the flag, if you have no missions scheduled for next turn, the popup says NO MISSIONS instead of END TURN.  I'd like it to be a separate warning: that is, if you answer Yes to NO MISSIONS, you then get the END TURN message.  Sometimes when I'm really in the zone I hit end, Y just out of habit, and having the End Turn message come up after hitting that would be a real heads-up.  But this should be an improvement, at least.

**Comment by peyre** [comment]
[b]Ha![/b]  On second thought it seemed to me I could get it to do what I wanted.  For once, it worked just right.  Now if you hit the Flagpole when you have no missions planned for next turn, you'll receive a NO MISSIONS warning.  If you say yes to that, you then get the END TURN warning.  So now number 1 is fully implemented.  I'd like to do the others, but they're more complex; maybe I can get on them in a few days.

**Comment by peyre** [comment]
So, the reason I can't fit much text in there is that this new warning is using the Request() function, which will take arbitrary characters.  It would be better to use the Help() function, which would let us create more informative warnings.  However, Help() requires a pointer to the help.cdr file, which is one of the crazy hex data files and is notoriously picky.  I'm not sure how to go about adding warnings to help.cdr, but if we could figure out how, we could greatly improve this warning message.

**Comment by rnyoakum** [comment]
I know the format that help.cdr uses, and it's not the friendliest. On the other hand, I'd mentioned this in passing to my brother and he decided on a lark to write a conversion program to make it easy to edit. So, I should be able to edit the help.cdr file to say whatever you would like. I'm not sure how user-friendly it is, currently, but if you can supply the text you'd like added I'll modify the file.

There are a few other text entries I need to be adding, such as #288.

**Comment by peyre** [comment]
That's great news!  Maybe something like this:
YOU HAVE NO MISSIONS SCHEDULED FOR NEXT TURN. PLEASE VERIFY IF YOU WANT TO CONTINUE WITHOUT PLANNING ANY MISSIONS FOR NEXT TURN.
I think it also needs a heading, which could maybe be:
MISSION SCHEDULING
or maybe
WARNING
or something like that.

**Comment by rnyoakum** [comment]
@peyre wrote:
> So, the reason I can't fit much text in there is that this new warning is using the Request() function, which will take arbitrary characters. It would be better to use the Help() function, which would let us create more informative warnings. However, Help() requires a pointer to the help.cdr file, which is one of the crazy hex data files and is notoriously picky. I'm not sure how to go about adding warnings to help.cdr, but if we could figure out how, we could greatly improve this warning message.
https://github.com/raceintospace/raceintospace/issues/166#issuecomment-624120032


I pushed a commit that handles this part, see my commentary at https://github.com/raceintospace/raceintospace/issues/288#issuecomment-636388554.

**Comment by peyre** [comment]
You certainly did!  The new warning looks great - much better than the one I did.  Thanks Ryan.

![New Warning](https://user-images.githubusercontent.com/3118014/83339603-7de89a00-a284-11ea-8203-0f36070e6353.png)

**Comment by rnyoakum** [comment]
The hard work was done by my brother, who doesn't work on RIS but announced one day he had written a script to encode & decode the help.cdr file. It's pretty easy to use, if you'd like a copy.

**Comment by peyre** [comment]
Yes please!  Say, is it something we could upload to the repository in an "Extras" folder or something like that?

**Comment by rnyoakum** [comment]
Currently it's over a dozen files including tests, so you might get emailed a zipped file or a link to his github.

**Comment by peyre** [comment]
That would work just fine, thanks.

**Comment by peyre** [comment]
I've implemented warnings for 3 and 4 - when you enter R&D, it will warn you if you have an LM or Kicker-C prototyped but haven't started EVA suits.  Same thing if you haven't prototyped DMs.

**Comment by peyre** [comment]
It occurred to me this morning that a better solution for numbers 2 and 5 might be to display the Safety figures in the VAB/VIB, and in the final launch approval window, in a different color.  The VAB/VIB already does that for damaged equipment - maybe these two screens could show <MaxR&D equipment in yellow or something.  I'll have to look into it this weekend.

**Comment by peyre** [comment]
Shoot!  I

**Comment by peyre** [comment]
So, I got newmis working.  Now Safety figures below Max R&D show in black in the final go-ahead for missions.  Still trying letter combos in the VAB without success.

**Comment by peyre** [comment]
So, I got newmis working.  Now Safety figures below Max R&D show in black in the final go-ahead for missions.  Still trying letter combos in the VAB without success.  The VAB is really more important, since if it catches your eye you can do something about it.  If you don't notice until the final-approval screen, it's too late to do anything but cancel the flight.

**Comment by peyre** [comment]
Damn, so I guess it never assigns the Max R&D, which shouldn't be a surprise since The VAB's never needed it before.  I keep trying to set the variable, either mrd or MaxRD, but it keeps coming back saying the variable is undefined. :(

**Comment by peyre** [comment]
Ok, I've uploaded newmis, so now the percentages show in red if they're below Max R&D.  Now if only I can work out how to get the same to happen in the VAB!

**Comment by peyre** [comment]
wth?  I added this line to the VVals function:
`VAS[VASqty][tx].MaxRD = EQ->MaxRD;`

And set the VAB to show MaxRD, but it sets it equal to sf (Safety) instead!

![MaxRD](https://user-images.githubusercontent.com/3118014/152652799-589c0cdc-a920-46da-ad31-abf5cb695b59.png)

**Comment by peyre** [comment]
Hey, I got it working for the payload!  But, the rocket still eludes me.

![MaxRD](https://user-images.githubusercontent.com/3118014/152654936-b6c0d00d-141a-4bc0-a0cb-4856d4b1e5e2.png)

**Comment by peyre** [comment]
I got it working!  Now the VAB/VIB shows Safety in deep red if it's below Max R&D.  I think I'm going to find this was a feature I never realized how much I was missing until it was there.  That red catches your eye right away.

![VIB](https://user-images.githubusercontent.com/3118014/152698776-657ebe78-a745-498d-b140-c4ebdd57471d.png)
![VIBlunar](https://user-images.githubusercontent.com/3118014/152698777-d72066ce-3a20-450d-84b1-486bda18febe.png)

**Comment by peyre** [comment]
Ryan suggested that using two shades of red here probably wasn't a great idea, and I agree.  I've changed it to yellow for being under Max R&D.
![VIB colors](https://user-images.githubusercontent.com/3118014/160662893-f8c3d49c-bc0b-4b00-a45b-f76523bedaf2.png)

**Comment by peyre** [comment]
Say, perhaps the "You don't have any missions scheduled" shouldn't show if you got the newscast saying you can't purchase any rockets for a year.  You probably should still see it if you've had the "no capsules for a year" because you could still fly probes.

![Shouldn't come up if you can't have rockets for a year](https://user-images.githubusercontent.com/3118014/161116968-5cea8fcd-b857-4d10-adfb-b39b208d4e8a.png)

**Comment by peyre** [comment]
So it looks like all of these have been implemented!  Closing this ticket.
