### ISSUE TITLE
The H Launchpad

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#169]
One of the newscasts says that "A STORM FRONT BLOCKS THE LAUNCH WINDOW FOR THE H LAUNCH FACILITY" and so the mission on that pad is canceled.  The issue here is that in event.dat, **h** is a variable or it's supposed to be a variable.  Either it shows the letter because there's no data to display, or it doesn't in fact treat a lower-case h as a variable so treats it like a character.

**Comment by rnyoakum** [comment]
Fixed by commit b3cf7c82086998c1ea716cacf63864a6e308ff65.

**Comment by peyre** [comment]
Congratulations!  This one's confirmed fixed.  I always wondered what it would show: A, B, or C; or Primary, Secondary, etc.

![launch facility](https://user-images.githubusercontent.com/3118014/51805827-13a28e00-2227-11e9-8f7d-f2f1ff1dcc1f.png)

**Comment by rnyoakum** [comment]
It wasn't hard to fix the problem, once I looked at it. The hard part was creating the save editor so I could reliably test it.
