### ISSUE TITLE
Jupiter & Saturn travel time

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#171]
Both the Jupiter and Saturn flyby take 7 turns (3.5 years) to arrive.  That hardly seems right since Saturn is nearly twice as far from the Sun as Jupiter.  Historically our probes took between a year and a half and two years to reach Jupiter, and 3-6.5 years for Saturn.  Maybe in the game, we should make it 4 turns to Jupiter and 7 or 8 to reach Saturn.

 Probe  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  Launch  &nbsp;&nbsp; Jupiter  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp;  Saturn
 Pioneer 10 &nbsp; &nbsp;  3/72 &nbsp; &nbsp;&nbsp; 12/73(1yr,9mo) &nbsp; &nbsp; &nbsp; --
 Pioneer 11 &nbsp; &nbsp;  4/73 &nbsp;&nbsp; &nbsp;  12/74(1yr,8mo) &nbsp;  9/79 (6yr,5mo)
 Voyager 1 &nbsp;&nbsp; &nbsp; 9/77 &nbsp; &nbsp; &nbsp; 3/79 (1yr,6mo) &nbsp;  11/80(3yr,2mo)
 Voyager 2 &nbsp;&nbsp; &nbsp; 8/77 &nbsp; &nbsp; &nbsp; 7/79(1yr,11mo)&nbsp;  8/81 (4 yrs)

**Comment by peyre** [comment]
I've just been looking through the code, and boy, I sure can't find where these numbers are set.

Giving this more thought, we might also want to reduce travel time for the Mars probe to 2 turns, since the Mariner flybys got there in 5-8 months.
Mariner 4       8 months
Mariner 6&7  5-6 months
Mariner 9       6 months
The Viking probes took longer (13-15 months), but they had to slow down to achieve orbit so I'm more inclined to go with figures from the Mariners.

**Comment by rnyoakum** [comment]
I believe that the Flyby durations are set in MissionPast() at mc.cpp, ln 402:
```
Data->P[plr].History[loc].Event = (mc == 10) ? 2 : ((mc == 12) ? 7 : ((mc == 13) ? 7 : 0));
```
where mc is the mission code, and 10, 12, and 13 are the Mars, Jupiter, and Saturn Flybys, respectively. Though the manual states the travel time is 3 turns for the Mars Flyby and 7 turns for the Jupiter & Saturn Flyby, this line suggests the implementation differs.

The mission itself plays out in TestFMis() [start.cpp, ln 1121-1153]. Each time the TestFMis() is run for a flyby, the Event field is decremented and the mission hardware safety - stored in `Data->P[j].History[i].Saf` - is tested
```
if (brandom(100) > Data->P[j].History[i].Saf) {
```
If the hardware test fails, the mission fails. If the Event field hits zero and the mission hasn't failed yet, the mission is a success. Either way, a flag (`Data->P[j].Plans`) is set so the newscast will include the mission results.

All line numbers per commit 779a88ba5253ec3e2af6e0c47bf860d628facc45.

**Comment by peyre** [comment]
Wow, good sleuthing.  I'll have to test it to see, maybe even tinker with the numbers to see what happens.

**Comment by peyre** [comment]
Ok, I just compiled and played a game solely testing the probes.  Where I got the numbers from is: when you launch the mission, if the launch is successful, it tells you how long until it gets there...except I remembered Mars wrong.  The game does make it 2 turns, not 3, so the Mars probes are fine.  I will try tinkering with the numbers later.

**Comment by peyre** [comment]
Sure enough that did it!  I've reduced the Jupiter probe's travel time to 4 turns.  I left Saturn at 7 since that's within the ballpark, and for gameplay reasons.  If you think we should change Saturn to 8, we can certainly do that.

![JupiterProbe](https://user-images.githubusercontent.com/3118014/66856956-271f9180-ef3b-11e9-83c3-49915151b361.png)

**Comment by peyre** [comment]
Looking back on it, I suspect that the Saturn was always supposed to take 7 turns to get there, and Jupiter somewhere around 4 - but it was set accidentally to 7.  That's just speculation, but it would explain why they would have identical flight times even though one is nearly twice as far away as the other.  So, all the more reason to leave Saturn at 7 rather than pushing it out to 8.
