### ISSUE TITLE
Indicate if a crew is currently assigned

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#173]
In the capsule/shuttle screen, “FLT. CREW” could show in a different color if the crew is currently assigned to a mission.  Currently, teams that are assembled show in white; teams that are being assembled (i.e., that aren’t yet complete) show in dark red, and empty crews show in light red.

This would be in ast4.cpp.  Best guess, purple (color 7) might work well.

**Comment by rnyoakum** [comment]
I like this idea, and think we should do it. It shouldn't be difficult. Not sure which colors should be used; we might borrow the colors used in the Future Missions assignment. Would it be useful to differentiate between Primary & Backup teams, or merely confusing?

Similarly, I was playing a couple of weeks ago for the first time in a while (until I realized an Autosave bug was plaguing my save data) and kept running into an issue with the Future Missions I had assigned. Currently, once a flight crew is assigned to a Future Mission, I don't know of any way to check which ones are used. I was unsure if I had assigned the correct Primary / Backup crews, but didn't have any way to see which crew was Primary & which Backup without cancelling the mission and rescheduling. Any ideas on handling that?

**Comment by peyre** [comment]
I think using different colors for primary & backup crews is a good idea, though less important.

So you mean on the turn where you assign the mission, there's no indication that the crews have been assigned?  The only way I can think of to find that out would be to start assigning another mission, and when the screen pops up for you to assign crews, their statuses should show there.

**Comment by peyre** [comment]
How about something like this?  Where Flight Crew I is the primary on a mission on Pad A (either this turn or next) and Flight Crew II is the secondary on a mission on Pad A (this turn or next).

![Soyuz](https://user-images.githubusercontent.com/3118014/79590557-0e2f9e80-808c-11ea-80ed-ba0655c5aae8.png)

**Comment by peyre** [comment]
Wait, that wouldn't work except for flight crew I and maybe V.  Maybe that first line should say CREW I instead of FLT. CREW I.

**Comment by peyre** [comment]
I'm on fire today!  I got this all done: crews assigned to a mission this turn show in blue, those assigned to a mission next turn in green, and primary crews show a darker shade than backups.  Also I added the info (in the appropriate color) to the left of the capsule pic.  It's not exactly the above; it shows, say, PRIMARY CREW THIS TURN.

**Comment by peyre** [comment]
Just for the record, this is how it shows now:

![PrimaryCrew](https://user-images.githubusercontent.com/3118014/85925231-e313b900-b84b-11ea-83b0-aaca05864f0e.png)

**Comment by peyre** [comment]
Another example, since I had an easy opportunity to screenshot:

![Colored Crews](https://user-images.githubusercontent.com/3118014/212752155-b4e064ec-fd1a-41ba-a57f-31bd5631682e.png)
