### ISSUE TITLE
Hospital & Cemetery Images swapped

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#184]
The hospital and cemetery background images are switched. Going to Arlington (or the Kremlin Wall) shows the images for the US/Soviet Hospital, and vice versa. It appears as though the choice of images is reversed in the Hospital function (ast3.cpp, ln 705-709).

I'm willing to fix it and submit a pull request, and to try to do some other bug fixes in the future.

**Comment by peyre** [comment]
That's great!  I've sent you an invite.  Welcome aboard.

I'd sure like to get some of the High Priority items in Issues fixed, if you feel like working on any of them.

**Comment by rnyoakum** [comment]
This issue should be resolved with commit 2f45042.
