### ISSUE TITLE
Missing intel image files

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#186]
When I check the Pentagon for CIA intelligence, the game crashes with the error:
unhandled exception: not found: images/intel.but.56.png
The file is missing from data/images/, along with what appears to be several other intel.but.XX.png files. Is this an unexpected bug in the program, or is there an image this should be finding?

Historically, I think the intel images were all stored in an intel.but file, which I have, but I have no idea how it was encoded.

**Comment by peyre** [comment]
Hum, I haven't seen this, but then, I haven't tried going into the intel screen.  We probably just need to add the missing images.  If you have them handy, try adding them and see if it runs right on your system, then go ahead and add them to the project.  Good find there!

**Comment by peyre** [comment]
Hey, if this is fixed now, let's close the issue. :)

**Comment by rnyoakum** [comment]
This should be fixed with commit 5884660 so it won't crash the game anymore. While looking through the code and image files, I did find some things I couldn't explain:
1) intel.but.22.png is the same as intel_background.png, when I would expect it to be the be an image of Soviet Kicker A.
2) intel.but.55.png does not exist, and isn't generated by the but2png utility. It should be the USSR-spying-on-US equivalent of intel.but.27, which by internal logic corresponds to MISC_HW_PHOTO_RECON. I'm not sure what that is in the game - it's filed under Misc Hardware, not a mission, yet there is no corresponding item in the game. It's possible it's art for something which was never implemented.

Neither of these quite fall under this issue, so I'm closing it, but if anyone knows what is going on with those images I'm curious. If I see either in the wild I'll start an issue for them, but for now they're beyond my familiarity with intel.cpp.
