### ISSUE TITLE
Game crashes when viewing astronaut history

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#192]
Viewing the Astronaut History section of the Museum of Space History can trip a palette compatibility assertion.

**Comment by peyre** [comment]
Yes, I just experienced it.  It gives the following error if the game is run from the command prompt:

raceintospace: /home/leon/raceintospace/src/display/legacy_surface.cpp:142: void display::LegacySurface::checkPaletteCompatibility(display::LegacySurface*): Assertion `myColor.rgba() == otherColor.rgba()' failed.
Aborted (core dumped)

**Comment by peyre** [comment]
It just happened to me again.  Looking at legacy_surface.cpp, lines 140-142 say:

```
// if this assertion blows up, you're probably doing a drawing operation
// without having copied around a palette first
assert(myColor.rgba() == otherColor.rgba());
```

**Comment by pemensik** [comment]
Oh, this is similar issue, but here the same fix would not work. Yeah, correct palette were lost. But I am not sure to which palette it should have been initialized. The intention is unclear from the code (to me).

**Comment by pemensik** [comment]
Ha! Just wanted to give up today, but tried blind test. And it works. Not so different fix as before. It seems first part of palette is fixed. If only those colors are used, it should be fine.

**Comment by peyre** [comment]
That's great!  So this one's fixed now, too?

**Comment by pemensik** [comment]
Can you please verify it fixes your history as well?

**Comment by peyre** [comment]
I can check it tonight when I get home.

**Comment by rnyoakum** [comment]
First off, I checked this and it appears to work properly. It avoids any crashes, which is the biggest problem. Great work.

It seems the problem was with the buffer caching the "No Mission Experience" message. It was creating a conflict with the palette it was copying onto (probably a palette obtained from the face images?), and you solved it by clearing the palette for the buffered content. Out of curiosity, did you track where each of the palettes was getting assigned?

Since the palette is shared for most (all?) sources for the lower values (through ~27 - see issue #7) I don't think it'll be a problem. As the "no mission experience" buffer is the one getting its palette cleared, I'd expect any visual change to show up in that section of the screen, and it looks fine in my game.

**Comment by peyre** [comment]
Yes, it fixes it!  I'm able to get into Cosmonaut History.  I see a small bug though: it looks like, if you have more than one mission under your belt, the name of the mission gets truncated: SOYUZ III (or whatever) gets shortened to SOY.
![Soy Program](https://user-images.githubusercontent.com/3118014/64666124-fdd68780-d409-11e9-95df-9b2d64a7c884.png)

**Comment by peyre** [comment]
Also, I think it'd be a good idea for 'naut history to expand the description for Duration missions like the game does (now) in other places: for instance, with this one it should say ORBITAL-D(B) or whatever the Duration length was.
![Needs to expand Duration mission description](https://user-images.githubusercontent.com/3118014/64666159-16df3880-d40a-11e9-95d5-69c7174f92a0.png)

**Comment by peyre** [comment]
Also, it would be nice if the Duration missions would include the Duration level, like it does in other parts of the game, so the above second mission should show as ORBITAL-EX(B) (or whatever the duration level was for that mission).

And, oddly, it looks like the name of second Vostok mission isn't truncated to VOS.  Odd.
![ORBITAL-X](https://user-images.githubusercontent.com/3118014/64666349-d3d19500-d40a-11e9-87cd-fcdc8595fb4d.png)

**Comment by peyre** [comment]
Looking back on it, the first one was from a saved game, and the second was from a fairly new game that I loaded and then had to fly a Duration B mission to get that screenshot.  So maybe the issue only affects flights done before this fix was implemented?  Might need to test and find out.

**Comment by peyre** [comment]
Say, anyone else notice the artifacts above?  The vertical line just past the astronaut wings, and the vertical colored stripe to the right of the medal?  I've been looking through the museum file but can't seem to find where they're drawn, and I don't see any images for them in gamedat.

**Comment by pemensik** [comment]
I wonder if it isn't part of palette leaked into bitmap data. Or it might be some bug when wrapping the line.

**Comment by peyre** [comment]
Could be.  I'd also like to fix those little artifacts to the right of the astronaut wings and the medal.  It's esthetic, I know, but it'd be nice to get rid of them one of these days.

**Comment by rnyoakum** [comment]
I've been switching RIS over to using the PNG files from the .but files, and got around to looking at this one. The image data is stored in arrows.but, which contains seven images used in Astronaut History:

0. The Left All arrow icon
1. The Double Left arrow icon
2. The Double Right arrow icon
3. The Right All arrow icon
4. The USA Hero medal
5. The USSR Hero medal
6. Astronaut/Cosmonaut flight wings

Each image in the arrow.but file has a header at the beginning of the file, specifying the width, height, size (in bytes), and the data's location in the arrow.but file (as a byte offset from the start of the file).

For the USA Hero medal, USSR Hero medal, and flight wings, there is an error in the image data. There is a discrepancy in the width * height vs. the size, with the size - and file space allocated - being calculated as if the width was one larger. However, the listed width value is correct, the file space is too large, and every (width + 1)-th byte is simply nonsense.

So that's what is going on. I'll convert the arrows.but file to png images that will be accurate.

**Comment by rnyoakum** [comment]
Since the original issue is resolved and the current problem is not related to the original cause, I'm moving the problem of the Astronaut History visual artifacts to issue #299.
