### ISSUE TITLE
Correct behavior for allowing joint missions

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#197]
Currently, the Future Missions code sets the criteria for deciding if a joint mission is allowed by checking if (A) the mission is being planned for the primary / secondary pad, and (B) is the secondary / tertiary pad constructed & undamaged. This means that if a joint mission is planned any previously assigned mission on the secondary / tertiary pad, whichever is relevant, is automatically replaced by the second part of the joint mission. I'm curious what the original behavior was, and what it should be.

I'd like to know the original behavior because I think we should try to have some sort of "legacy" configuration setting which would duplicate the behavior of the original BARIS as closely as possible, insofar as that's feasible. As for how it should work, I see three options:
I) Joint missions should not be displayed if the second launch pad is already occupied with a planned mission,
II) Joint missions should be shown, but when scheduled some form of pop-up should get confirmation the user wishes to displace the other mission,
III) Joint missions continue to quietly displace planned missions on the second pad, trusting the player to know their own mind.

**Comment by peyre** [comment]
The original behavior, and I think the one we should have, is I.  If you have only one pad available for scheduling a mission, then Joint missions shouldn't be available.  Also, as the manual (I think) says, joint missions are always two launches back to back, so you can schedule a Joint mission for pads A&B or B&C, but not A&C.

**Comment by peyre** [comment]
The original behavior, and I think the one we should have, is I.  If you have only one pad available for scheduling a mission, then Joint missions shouldn't be available.  Also, as the manual (I think) says, joint missions are always two launches back to back, so you can schedule a Joint mission for pads A&B or B&C, but not A&C.

**Comment by rnyoakum** [comment]
The behavior the game was using was (III), but I've corrected it to (I) in 6eddedbbf7f93a02d63d1b894ade8e84f2a9a13e.
