### ISSUE TITLE
Additional buttons in capsule/shuttle screen

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#210]
It might make crew assignment easier if you had more options for manipulating crews, something like I've mocked up here.  The UP and DOWN buttons could move a member of a crew up or down so you could rearrange crew members without having to break the crew and then reassign in the order you want.  The REMOVE CREW button could remove a single crew member rather than breaking the entire crew.
![soyuzmod](https://user-images.githubusercontent.com/3118014/50602250-b1df4600-0e6b-11e9-8c96-d4554b7aa40f.jpg)

**Comment by rnyoakum** [comment]
It could make things easier, but I'm not a fan of the idea. Aesthetically, I think it clutters the screen, but obviously that's only a personal interpretation.

From an interface standpoint, before you could move an astro/cosmonaut up or down there would have to be a way to select which one to move. Logically, we could steal the 1-4 keys from triggering the crew compatibility screen, but it would require reworking that system - I believe currently the crew compatibility display hijacks the interface, which would block the use of the buttons. Also, this would require creating new code to track which astro/cosmonaut is selected, deciding how to show that graphically, and mapping appropriate keyboard commands. We would then need to update the help files with the changes.

All of this could be done, but would constitute an odd departure from the established interface design, and might make it trickier to move to a component-based GUI, which I think we should prioritize.
