### ISSUE TITLE
Wrong newscast music for early game

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#214]
The black & white newscast should use a different music file for the news intro - M_NEW1950 instead of M_NEW1970 (new1950.ogg vs new1970.ogg). Currently, only new1970.ogg is used. I'm not sure when the transition between the two is supposed to occur - I would guess 1964, because that's when the transition from the B&W to color animation occurs, but I don't remember it being that early (the name does say 1970, not 1964). It's also possible the B&W to color transition should be later. However, my memory of the game is over 15 years old, so that's not reliable.

I suspect the reason only M_NEW1970 is being used is that it's a longer audio file. Currently, the audio loops, which is distracting when the shorter 1950s clip restarts in the middle of the broadcast. I think what should be happening is: the audio plays as the into to the broadcast, the broadcast plays, and finally the music plays again as an outro after the newscast concludes.

Does anyone else have a better understanding of how the news music should work?

**Comment by peyre** [comment]
Wow, good catch.  I'll play a game of BARIS and let you know.

**Comment by peyre** [comment]
Ok, I just played to 1964, and the music is all the same on opening to Walcrite.  There was a different sound though just before that, when it shows the oddball progress bar of the technician installing your new color TV set.  But the music of the newscast itself is unchanged.

**Comment by peyre** [comment]
I got to thinking, maybe the issue is that new1950.ogg was the music used in the newscast in the floppy version, but no, that's not the case.  new1950.ogg does sound familiar from somewhere, but I can't put my finger on where I've heard it before.

**Comment by rnyoakum** [comment]
I swear that the news music changed in the floppy version at some point - it would transition and I would always be disappointed because I preferred the earlier music. Strangely, the music is one of the things I remember best. I'm not sure when the transition would occur, but there was one.

Either way, the points at which the music is played should change. It's currently on a loop, but it should be played twice - once for the intro, once for the outro. Unless, that is, you think it should be looped for the outro? I'm planning to go ahead and commit that change, along with using the new1950.ogg for the B&W. That sounds right, and it's trivial to change back.

From your comment - do you have a copy of the original floppy installed?

**Comment by peyre** [comment]
Ah, good point; I haven't tried playing a game of the floppy version out to 1964 or even 1970.  Your memory might be right; it would explain why new1950 sounds familiar, but I don't see why it would play new1970 early in the game and new1950 later on.

I do have a copy of the floppy version.  Want me to send you a copy?  You can run it in DOSBox.

**Comment by rnyoakum** [comment]
I had thought the floppy version used new1950.ogg for the B&W and then switched to new1970.ogg - the B&W version had been simpler, and the later newscasts sounded, well... more like the 1970s.

Also, thanks for the offer, but I already have a copy of the original floppy version. If I could find the drive to read it I actually have the original floppy disk (and manual) somewhere. I just don't have a DOS emulator installed at the moment.

**Comment by peyre** [comment]
I can read the original disks!  But, of course, there's no need.

If you ever do want to run original BARIS, DOSBox is quick and easy to install, and pretty easy to use.  The CD version of BARIS is a real bear to get working in DOSBox, but the floppy version is no problem.

**Comment by peyre** [comment]
Aha!  Found it.  The new1950 sound is played in the floppy version for the Soviet newscast, not the US newscast.  The US newscast never plays it (I played a game out to 1975 and never heard it), whereas the Soveit newscast plays that right from the start.  It's used for the Soviet newscast in 1.00b and 1.01, but in the CD verison (1.1), the Soviet newscast uses the same tune as the American one, new1970.

**Comment by rnyoakum** [comment]
I've switched the Soviet newscast to use the new1950 sound, because I feel the distinction between the two helps maintain the sense of difference, and because it seemed to fit better with timing of the Soviet newscast dialogue. I also changed the looping, as I mentioned in a previous comment.

**Comment by peyre** [comment]
I'm finally (I hope) getting my desktop computer back up and running again, and was able to set it up to compile RIS last night, and started up a game as the USSR.  So I've confirmed that the change in music for the Soviet newscast is working, and I agree with you--it seems to fit better with the timing.  It's also always nice to have contrasts between the US and Soviet sides.  I'm pleased that 1) you're still working on the game, and 2) you paid attention to the Soviet side; it seems to be neglected oftentimes.
