### ISSUE TITLE
Intel Briefings created on Autosave load

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#217]
When an save is loaded going into a Fall season, it creates a new intelligence briefing as it normally would. However, in the case of an autosave, the game does not distinguish between a game heading into a Fall season and one saved at the end of the Fall season that resumes that season. Basically, it's issue #204, but for Intel briefings.

This wouldn't seem too bad, but the game records a history of all the Intel briefings, so if this problem occurs often enough in a single play-through there will be an array overflow and other variables will start getting rewritten.

**Comment by peyre** [comment]
Oh yeah, that sounds like something that's worth addressing.

**Comment by rnyoakum** [comment]
I'm handling this bug, and while the solution is a little inelegant, it should work well enough. But I did check and see that the manual says a new intelligence briefing is generated every turn. This is inaccurate - intelligence is only updated in the fall - and I plan to correct that.

**Comment by rnyoakum** [comment]
This issue affected several other things, including Presidential reviews, budget records, and R&D modifiers. I committed a fix (commit 8062cd533ff195a44f70225ae18472685bd0cad2) and I did some testing. Everything seems to work properly, but this is a tricky issue so there might be something I overlooked.
