### ISSUE TITLE
'Nauts get credit for flights that are canceled

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#220]
Since RIS .4.8, veterans now show their number of spaceflights.  However, if a mission is on the pad but the flight is canceled at the last minute (problem with the engines for instance), they get credit for that mission anyway.  It would be better if they didn't.  Also we shouldn't give them credit for a flight when it gets off the ground but there's a failure in the booster and the capsule is emergency-ejected.

**Comment by peyre** [comment]
I suspect this is an issue of when credit is given for having flown a mission, that the number is incremented just prior to countdown or thereabouts.  I would change it to after a successful launch.  I would suggest after an orbital insertion burn, but then credit wouldn't be given for suborbitals.

**Comment by peyre** [comment]
I just got this again. Slayton was on the pad ready for liftoff, but the mission was canceled at the last second due to a "major problem in the boosters".  They never even actually started the engines, yet he still gets credit for having flown.

![Uploading SlaytonSuborbital.png…]()

**Comment by peyre** [comment]
I think the line where the number of missions is incremented might be in mc.cpp, line 462:
`Data->P[plr].Pool[j].Missions++;`

**Comment by peyre** [comment]
An interesting question arises with this one, though: what qualifies someone as a veteran vs. unflown?  Where do you draw the line between "has had a spaceflight" and "has not"?  If the rocket never leaves the ground, that seems pretty clear.  But what if the rocket goes up but the craft never makes orbit?  I'm inclined to say don't give credit for that one (except, of course, for Suborbital missions), since they never really got to _do_ any of their mission.  Yet on the other hand if we don't increment the number of missions, that could cause a perceived mismatch in Astronaut/Cosmonaut History: "I see he was on three missions, but he only has a (2) next to his name in the Apollo screen" for instance.

**Comment by rnyoakum** [comment]
My thought is that the astronaut/cosmonaut should be counted as having been on a mission if the mission is recorded as having a unique number. Consider the example where the rocket explodes on the pad and the entire crew is killed - they never reached orbit, but they were killed during a mission. That would be the sort of contradiction that would be strange - "he's never flown a mission, but died on one." I'm not certain how a mission is defined, but that's the sort of conundrum that informs my opinions.

**Comment by peyre** [comment]
That's a point.  So even if the mission suffers a last-second abort and they never even light the engines, the crew gets credit for the mission since otherwise we'd have a discrepancy in number of flights claimed (in parens) vs. number of flights shown in Astronaut History.  In that case, maybe I should close this issue.

**Comment by peyre** [comment]
I'll go ahead and close, at least for now.
