### ISSUE TITLE
Have game default to the Historical Model

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#221]
I always play the Historical Model.  I don't know, but I suspect that most people do the same.  It might be in line with the game's character as an "edutainment" game if we had it default to the Historical Model with the Historical Roster.  This is determined in prefs.cpp, I think.

**Comment by rnyoakum** [comment]
Handled by commit b3f53a02f08a80d5b5798399445bee0a59d77c47.

**Comment by peyre** [comment]
Hey, neat!  It was a low-priority item, but nice to have it enacted.
