### ISSUE TITLE
Mission not assigned in Future Missions screen

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#222]
In Future Missions, if you choose a mission and move to the screen where you select a capsule or crew, then cancel, press Continue again and select the capsule and/or crew, when you come back to the Future Launch Selections window you see it didn't assign the mission after all.

However, if you cancel out of capsule selection and then change the mission type, it will assign the mission like it should.
![blankfuturemissions](https://user-images.githubusercontent.com/3118014/51794169-bd2f4400-2181-11e9-9f48-3f2f3f6f5eeb.png)

**Comment by peyre** [comment]
Incidentally, this was also a problem in RIS back in our Sourceforge days, so it's not new to us.  However I don't think it existed in BARIS, or at least I never noticed it there.

**Comment by rnyoakum** [comment]
This was the result of a complicated mess of code where Future Missions will be using two or three variables at times to track the same information. I can give a longer explanation if needed, but I patched it for now and plan to overhaul a lot of the FM code. 

Fixed per commit e51fbf66eb64d5711b430d7b9c45a1f563cfd37c.
