### ISSUE TITLE
Tech Transfer after purchase?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#223]
As it works now, an item gains Safety from technology transfer when it's prototyped, provided you have something eligible to transfer to it.  So, if you have a Gemini program and it's fully researched, if you prototype Apollo it will start with a higher Safety because of things you've learned from R&Ding Gemini.

However, if you were to prototype both (say, you bought both Gemini & Apollo because you had a half-off sale), neither would get tech transfer from the other because tech transfer doesn't happen after prototyping.

What I'm thinking is that maybe if you had, say, both the Ranger and Surveyor probe and neither was at 75% yet, if you put research into, say, Ranger, your Surveyor would get a proportional amount of tech transfer from that.  The formulas for tech transfer are in rdplex.cpp.

**Comment by rnyoakum** [comment]
This is an interesting idea. I think it may merit inclusion as a customizable option. It's a large enough change from the original that I wouldn't make it mandatory, but it follows the same logic as the original technology transfer.

**Comment by peyre** [comment]
Yes, I'd say that ideally, it could be turned on or off in Advanced Preferences.  I'd like to see it on by default, but the default is less important than making it optional.

**Comment by peyre** [comment]
I think this probably isn't really a practical idea.  For one thing it raises the question whether a Safety downgrade for one component would also cause damage to components that can get tech transfer from it.  I think I'll close this one.
