### ISSUE TITLE
MIDI support on Unix-based systems

### ISSUE THREAD

**Issue by colorworm** [raceintospace/raceintospace#226]
Since the MIDI files are already there, will this be worked on?

**Comment by peyre** [comment]
Sorry for the delay responding, colorworm.  I would've responded sooner but I actually don't know what to tell you on that one.  The team isn't terribly active and progress has been slow, and I'm not a programmer myself.  However, since you ask about Unix systems, it makes me wonder: are you a programmer by any chance?

**Comment by colorworm** [comment]
No, sorry. I'm not a programmer. I only know enough programming to kludge together simple MATLAB or Bash scripts and mess around with Makefiles. I don't really know much about C or C++, so I don't know how I could be of help to the project.
I only asked the question because I was curious to see how the game would sound on a hardware Roland SC-55, and I remembered liking the game and its music on Windows.

**Comment by peyre** [comment]
Ah, too bad.  Doesn't hurt to ask!  Well, maybe one of the other folks here will have an answer to your original question, but in the meantime you could still make a contribution, if you like, by compiling the game and playing it, and submitting bug reports and/or enhancement requests.  Just be aware that we're not able to make major changes to the game for lack of time and expertise (on the programmers' part and mine, respectively).  We've had people suggest things like "How about being able to sabotage each other's programs?" and that's just way too involved.

**Comment by sflynn850** [comment]
This is being currently worked in #848 — see that ticket for further progress.
