### ISSUE TITLE
Vehicle Assembly is locking up

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#228]
I've never seen this before.  This is a recently compiled copy of the game.  I started playing, and the first time I go into Vehicle Assemly it stops responding.  The music continues to play, but it doesn't respond to mouse or keyboard commands, and I have to X out of the game.  I reran the game with the verbose switch and attached the output below..
[VehicleAssembly.txt](https://github.com/raceintospace/raceintospace/files/3124156/VehicleAssembly.txt)

![VehicleAssembly](https://user-images.githubusercontent.com/3118014/56853029-3b14ff80-68d7-11e9-80f5-0d12f14989ed.png)

**Comment by rnyoakum** [comment]
Okay, I pulled it up and encountered the problem as well. It's probably something that was introduced in my March 20 commit 328830a0cacaf83d7b01f78bbd479d48d7d2846e, but for some reason I wasn't running into this then - I'm guessing I didn't get it built properly.

Thankfully, the program isn't actually locking up; I can still use F1 for help. My guess is I accidentally stopped all of the VAB buttons from triggering. I'll see if I can fix this quickly, if not I can roll back the commits where this was introduced.

**Comment by rnyoakum** [comment]
I issued a commit that should solve the problem - it was basically a typo that got past me. I remember testing my work, so I'm guessing I didn't get the program built properly and was still using the earlier code. Thanks for catching it!

**Comment by peyre** [comment]
Wow, that was fast!  Thanks Ryan.
