### ISSUE TITLE
'Nauts not removed from crews right away

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#240]
I played a game today in which a cosmonaut was killed in a training accident, but wasn't removed from the flight crew until the following turn (when another cosmonaut happened to die in a train wreck).  However, that second guy _was_ removed from the Vostok program right away.  (As I recall, this sort of thing also happened in the old CVS code.)
![BykovskyDies](https://user-images.githubusercontent.com/3118014/64066878-37222280-cbd4-11e9-80b9-d5ec4bfb3d4c.png)
![BykovskyBuried](https://user-images.githubusercontent.com/3118014/64066880-3a1d1300-cbd4-11e9-9d20-8f4d2f8710b1.png)
![BykovskyRemoved](https://user-images.githubusercontent.com/3118014/64066882-3c7f6d00-cbd4-11e9-8baf-6fb6395f719c.png)

**Comment by rnyoakum** [comment]
I glanced at this, and it looks like a one line edit. The game mechanics aspect of news events are handled in news_suq.cpp in the REvent() function. This particular event is case 51, similar to event 52 which also kills an astro/cosmonaut, which you apparently hit the next turn (rotten luck :( ). Event 52 calls Replace_Snaut(), which updates flight crews that have a dead/injured/retired member. Adding a call to the (case 51:) event should fix the problem.

I'll post the fix once I've tested it - I'll modify a save file to include the news event and run through it.

**Comment by rnyoakum** [comment]
Issue resolved by commit f8bb552f65f127d86c5af8fdc1c81b90c0011b99.

**Comment by peyre** [comment]
Nice, thanks for getting to this one so quickly.

**Comment by peyre** [comment]
Yep, this seems to be fixed all right.  I'm playing now and just had a cosmonaut killed by a train, and he was removed right away.  Good work!
