### ISSUE TITLE
Testing framework segmentation faults

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#252]
I've spent a long time trying to get the testing framework (#47) to work properly. I was trying to test the JSON roster setup that was introduced but never integrated into the code, and wanted to make sure it was providing the correct output and agreed with the .dat file.

There were a few changes I had to make - the game_test executable didn't have the game source files included in src/game/CMakeLists.txt, and the correct music sources weren't being included - but I managed to get it to compile and build a simple test case for the roster code.

However, every time I would run the test cases it would throw a segmentation fault, inside the test cases. I'm not sure what's going on. I stripped down the roster test cases to see if they caused the error, but even with a single dummy test - BOOST_CHECK(true) - I was getting a segfault just from building the game source along with the test source.

I'll try to create a branch demonstrating the problem; it would be nice to have a proper test framework when adding new features like JSON data files.

**Comment by rnyoakum** [comment]
I created a branch on my RIS fork that results in a segmentation fault for me, even performing trivial dummy tests. It's available [here](https://github.com/rnyoakum/raceintospace/tree/fix-boost-test) for anyone who's willing to help debug. I'm running cmake, make, and then

> 
> \> make test
> Running tests...
> Test project /data/Games/raceintospace
>     Start 1: game_test
> 1/1 Test \# 1: game_test ........................***Exception: SegFault  0.23 sec
> 
> 0% tests passed, 1 tests failed out of 1
> 
> Total Test time (real) =   0.25 sec
> 
> The following tests FAILED:
> 	  1 - game_test (SEGFAULT)
> Errors while running CTest
> Makefile:61: recipe for target 'test' failed
> make: *** [test] Error 8

However, when I looking in the LastTest.log file, it reports

> ...
> Running 2 test cases...
> 
> *** No errors detected
> <end of output>
> Test time =   0.23 sec
> ...

As I feel it's important to have a working test environment for implementing any of the more ambitious issues proposed, and since there is no existing test code, I am looking at switching the unit testing from Boost Test to another framework if this is not resolved soon.

**Comment by peyre** [comment]
Sounds reasonable to me.

**Comment by rnyoakum** [comment]
I tested the code with Catch, and was still seeing a segmentation fault at the end of the tests. It turned out the Filesystem class was using a singleton object to force PHYSFS_deinit() to be called during cleanup, and was relying on PhysicsFS having been initialized previously. The singleton, being globally defined, was being created during testing and thus calling PHYSFS_deinit() after the tests finished. But since PhysicsFS wasn't being used by the tests, it was never being initialized.

Adding a check to in the Filesystem destructor prevents the singleton from calling PHYSFS_deinit() before PHYSFS_init(). It illustrates the importance remembering to call PHYSFS_init() when testing components that interact with the filesystem.
