### ISSUE TITLE
Downgrade duration missions to shorter durations

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#255]
@peyre proposed in issue #246 that

> Incidentally, I was thinking along these lines re. allowing the player to downgrade the duration level of a duration mission. On duration tests (and any mission that you've assigned a higher duration level to than it requires), an extra button might appear in Mission Control. The reason I think this would be important (if it's practical to implement) is that duration tests sometimes fail. Say you assemble a Dur C and schedule a Dur D for next turn, and the C mission has to cut the Dur step short and you're still at level B. You're faced with the choice of flying your Dur D at a -5 penalty or scrubbing it. It would be handy if you could just change it to a C mission.

Having run into exactly this issue before, I concur. While there's uncertainty about the viability of downgrading a manned mission to an unmanned one (Issue #241), cutting the duration of a mission should be much easier; that's actually what happens when a duration step is failed during an endurance mission.

Additionally, I think we might consider setting the downgrade penalty differently in such cases. Say I've scheduled a Manned Orbital w/ EVA. If a problem with R&D or a news event produces a poor EVA suit reliability, I'd have to consider cancelling the mission, yet I'd loathe allowing the opponent to beat me to the Manned Orbital milestone. This is a good case for downgrading a mission; under these circumstances, a single risky element jeopardizes the entire mission.

However, this logic doesn't translate well to a duration downgrade. Lessening the duration to avoid a -5 duration penalty isn't so attractive if there's a -3 downgrade penalty attached. Sacrificing two duration steps makes more sense, because a -7 penalty is tough to swallow. But I imagine a single duration step of -5 is far more likely, and losing the prestige of the extra duration step (and 3MB) to prevent a -2 penalty is a much harder decision. In short, the relative cost is greater. It may be that, yes, we are mostly concerned about the case where the player is facing a -10 penalty, but it's worth consideration.

**Comment by peyre** [comment]
Ah, a bit of good news.  There should be no Safety penalty when doing a downgrade.  There's supposed to be a -3 hit to prestige, but that was never implemented and I don't think we should fix it.  (There would be a -3 penalty if you were rushing the mission a month, but not downgrading.)

**Comment by peyre** [comment]
Since you've fixed the duration penalty system, this might be an extra-good item to look into.  Do you think it's feasible to do something like this?

**Comment by rnyoakum** [comment]
I imagine it's feasible. I'll take a look at this and #241 when I get an opportunity, but I think I need to do some back-end work on the Future Missions code first. It was always messy, but worked, so I didn't try to change it too much. However, I've changed my mind about how much it's actually working.

**Comment by peyre** [comment]
Ok - cleaning up the code is a good and worthy goal.  Fixing the duration penalty system makes this a more relevant issue than it was before, but even without it we aren't behind where BARIS left us.  If you can get to this sometime, that'd be icing on the cake.

**Comment by rnyoakum** [comment]
I've got most of the downgrade system rewritten - including this part - and am putting it through some tests. I should be handling #276 as well, and hopefully #241 will follow soon.

There was some code that tried to handle the prestige penalty for downgrading. Is your opinion is that the prestige penalty should be disabled for now? If so, I'll comment those sections out to make sure no penalty is applied.

**Comment by peyre** [comment]
Yes please.  I know the developers meant for downgrading or scrubbing missions to carry a prestige penalty, but I've always been glad that penalty was never applied, especially for things like dummy missions.  It's one of the bugs in the game that I've always hoped to see not fixed.
I look forward to seeing what you've done with the downgrade system.  For tonight though I've committed to working on a translation project I have in the works.

So you think you'll be able to allow manned missions to be downgraded to unmanned?  I'd really like that too.  Just this weekend I had a situation where I really would have liked to change to a dummy mission but of course I couldn't.
    On Monday, October 21, 2019, 8:27:52 PM PDT, Ryan Yoakum <notifications@github.com> wrote:  
 
 
I've got most of the downgrade system rewritten - including this part - and am putting it through some tests. I should be handling #276 as well, and hopefully #241 will follow soon.

There was some code that tried to handle the prestige penalty for downgrading. Is your opinion is that the prestige penalty should be disabled for now? If so, I'll comment those sections out to make sure no penalty is applied.

**Comment by rnyoakum** [comment]
This is working as of commit cf31a7888d46601dfbf5531ac631359c7dbda6c7. Enjoy.
