### ISSUE TITLE
Update duration and penalty displays for Duration missions

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#256]
In the Future missions screen, the "Duration Pie" is normally used for navigation, by setting a desired mission duration, locking it in, and navigating between compatible missions using the standard scrolling methods (graphical/keyboard arrow buttons). For duration missions, the pie does double-duty modifying the duration setting. So while non-duration missions display the set length of that mission, on a duration mission the duration is displayed as whatever duration length the pie was set to when scrolling to the mission.

On a duration mission, I think the listed duration and the mission penalty readouts should both change when the pie is clicked to provide an accurate readout of the duration mission, as the mission is currently configured.

**Comment by peyre** [comment]
If I understand you right, it makes sense that it should update like that.  I haven't noticed it not doing it, myself, but haven't been looking for that sort of thing.

**Comment by rnyoakum** [comment]
I implemented this in d55bd23d9ddffde447eac74d74802dd98d80cd7d as part of fixing the duration display bug.
