### ISSUE TITLE
Mission planning allows zero-duration manned missions

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#257]
When I was looking at Issue #256, I decided to test what would happen if I planned a duration mission and did not set a duration. So I selected Manned Orbital Duration (mission 25), spun the duration pie around to the Unmanned setting, and clicked "Continue." The game didn't see a problem with this, and allowed me to select a capsule & crew as normal. Next turn, I handled vehicle assembly and set a launch date.

![RIS-no-duration](https://user-images.githubusercontent.com/44246332/65745020-583d3c80-e0c8-11e9-8828-c14503728441.png)

The game will allow me to fly the mission, even though it reads "No Duration." Unfortunately, I don't have an advanced enough save game file so the mission penalty caused me to fail too many steps too frequently to see what would happen.

**Comment by peyre** [comment]
Wow.  I've never seen that before.

**Comment by rnyoakum** [comment]
I've been looking over the Future Missions code, and this is definitely a bug. There used to be an attempt to catch bad duration settings for duration missions, but the way the code tracks settings has changed and this was broken.

**Comment by peyre** [comment]
Oh that makes sense.  I'm glad you've caught it.

**Comment by rnyoakum** [comment]
Fixed per commit e51fbf66eb64d5711b430d7b9c45a1f563cfd37c.
