### ISSUE TITLE
Mission Control, Launch Pad use wrong music

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#258]
It appears the Mission Control building and the Launch Pad use the music files for the other side. When I visit Mission Control or the Launch Pad while playing the US, it plays the music file ussrmil.ogg, and for the USSR it plays usmil.ogg. I'm not sure how long this has been going on, and a quick code search suggests those music files are used only for Mission Control and the Launch Pad, so there is no issue with consistency. Should they be swapped so their use is in line with their naming, or left as they are?

**Comment by peyre** [comment]
Well how about that?  They _are_ swapped!  Personally either sounds to me like it could work for either space program, but they're labeled us and ussr, so yes, maybe we should fix that so each plays for the side it was intended for.
