### ISSUE TITLE
Going into debt?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#268]
Here's an interesting thing I just found.  The game will allow you to go into debt to fix a piece of hardware (the "pay xMB or suffer y% Safety" thing).  I guess that part of the code doesn't check to make sure you have enough to cover it; it simply deducts the cost.  I don't know if we want to fix it though; I could go either way.

![InDebt](https://user-images.githubusercontent.com/3118014/66259379-32b5d000-e765-11e9-90d4-c538a9555efc.png)

**Comment by rnyoakum** [comment]
I would classify this as a bug. Usually the game does check to make sure the player has enough money, but apparently this case slipped through.

**Comment by TriggeredSnake** [comment]
Wait, it’s a bug? I thought it was intentional. I’ve been using it for
years, as it doesn’t waste any money on repairs.
