### ISSUE TITLE
Move Mission name over slightly

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#270]
In the Launch Pad screen, it might be nice to move the mission name to the left one space so it doesn't touch the right side of the box, like it does sometimes (see below).  This must be somewhere near line 117 of radar.cpp, but I can't for the life of me find it.

![Maybe Center Mission](https://user-images.githubusercontent.com/3118014/66273580-129c1480-e82a-11e9-8303-2fc8df7dfaa7.png)

**Comment by rnyoakum** [comment]
Not at a computer where I can test, but I imagine it's the call to MissionName() on ln. 192.

**Comment by peyre** [comment]
Hey, sure enough!  I saw that earlier but it didn't look right to me.  Thanks Ryan!
