### ISSUE TITLE
Too many downgrade options

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#276]
Extra mission downgrade options were added by commit 81a5e7bef44454a054e4172482ee46e1efb9b232, helpfully expanding player choices. Unfortunately, this resulted in the ORBITAL-OEX and EARTH ORBITAL-LEX missions being able to cycle through their "downgrade" options and into the downgrade options of JT ORBITALS-DEX and JT EARTH ORBITAL-LEX, respectively. I tested an ORBITAL-OEX downgraded to a JT ORBITALS-DE while on Pad A with a Lunar Flyby scheduled on Pad B. Unsurprisingly, the mission was... weird.

The solution is easy enough - the final downgrade entry for each mission MUST be 00. However, it should be possible to expand the available number of options for each mission.

**Comment by peyre** [comment]
Good catch, Ryan.  One thing, if you have a mission scheduled that you want to downgrade to something very simple, there is always the option of downgrading it, then going back into Mission Control and then downgrading again; from a simpler mission, there should be even simpler downgrade options available.  It's a workaround, not a fix, but I expect it's something players would very rarely want to do anyway.

**Comment by peyre** [comment]
I think it's fine to take just make sure all missions have a 00 as their final downgrade option.  Most of the time, you're not going to downgrade a mission spectacularly: it's common to go from Orbital EVA to Orbital, or Historical LL to Lunar Orbital LM test, but it'd be pretty uncommon fro someone to want to downgrade from, say, a lunar pass way down to an Earth orbital or something.

**Comment by rnyoakum** [comment]
This is fixed as of commit cf31a7888d46601dfbf5531ac631359c7dbda6c7. The new JSON file will allow any number of mission alternatives, with no risk of wrapping into the next mission. Just remember that the order missions are listed is the order they will appear in Mission Control. Check src/game/rush.cpp for some rules & advice regarding alternate mission choices.
