### ISSUE TITLE
Docking/EVA Requirements in Future Missions

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#277]
While looking through the help files I had noticed there were error messages in case the player tries to schedule a Future Mission that requires EVA or Docking, yet does not have an EVA / Docking program purchased. Apparently, those requirements were been removed at some point. Should be restored?

The arguments for:

- It helps remind the players that they will need to purchase the EVA Suits / Docking module, which could be useful for the beginning player.
- Allowing players to purchase EVA suits on the same turn as an EVA mission seems unrealistic, simply because the astronauts would presumably need some time to train with them.

The arguments against:

- It reduces player freedom. If they want to schedule a mission, planning to purchase the prerequisite technologies just before launch, that's up to them.
- If the player realizes they don't have the necessary technologies, the game should prevent them from completing Hardware Assembly in the VAB, forcing them to downgrade or scrub the mission.

A compromise option would be to add the EVA / Docking checks back into FM and only enable them if the no_c_training option is set (or a new configuration option).

EDIT: Apparently the checks I found are the ones used in the VAB. Never mind...

**Comment by peyre** [comment]
Maybe we should set it back the way it was done in 1.1.  In 1.1, it shows the error.

![Docking Error](https://user-images.githubusercontent.com/3118014/67025242-8d7eee00-f0ba-11e9-9638-009f37a3e73a.png)
