### ISSUE TITLE
Future Mission duration error message

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#278]
I fixed issue #257, which allowed Duration missions to be scheduled with an illegally low duration, but the fix is that the game doesn't proceed when the continue button is clicked. That's it. There's no error message beyond the color change of the printed duration. I looked through the help files to see if there was a relevant popup entry, but couldn't find one. There should be a popup message that clearly explains the duration requirements to the player.

Related: I mentioned FM help popups in #277, and am curious if those originally appeared  when scheduling Future Missions. Any clue?

**Comment by peyre** [comment]
It looks like the way you describe it (no error, just the Continue button becomes nonfunctional and changes color accordingly) sounds like how it works in 1.1.
