### ISSUE TITLE
Changes to Advanced Training?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#279]
I've been toying with a couple ideas re. Advanced Training.

Maybe the game should give a morale boost to anyone in Advanced, so they don't generally lose morale while they're there.  A full course of Advanced Training in a skill takes two whole years, and it's disheartening to see someone's morale drop while you're putting resources into making them a better astronaut.  Presumably they know you're grooming them for important missions and will feel motivated to stay with it.

I wonder if we should remove the rule that someone can go to Advanced only one time, ever.  (RIS 1.1 did loosen that rule slightly by letting you go back to Advanced if you're withdrawn from it before gaining any skill.)  This rule is presumably to avoid someone creating super astronauts, but given the resources you have to put into it to get extra skill points, that might be a moot point.  For instance to get someone with a CA1 to CA4 would take one and a half round of training: 6 turns, plus 5MB for the training (that's a third of what it cost to recruit his whole group!).  Boosting an astronaut two points in two skills would take 8 turns and cost 6MB.  I can't see players heavily abuse this system, especially with the frequency that people retire from your space program.

**Comment by rnyoakum** [comment]
I wonder if these changes should depend on astronaut difficulty level? I searched for the default Ast1 & Ast2 astronaut difficulty settings. They only appear in two places:
- In ast4.cpp, the crew compatibility display differs based on the astronaut difficulty level, and
- In start.cpp, it appears the morale bonus for a successful mission is based on the astronaut difficulty level,

which isn't much of a difference at all. Having an astronaut difficulty level suggests there should be some differences; RIS might want to incorporate more, and this could be one of them.

**Comment by peyre** [comment]
That's a good idea.  I've also suggested (#176) that at lower astronaut difficulty level, more of the candidates' skills could be visible during recruitment.  Ideally, I'd like that feature to be something you can toggle in Advanced Preferences, so anyone who wants to play by the old rules can.

**Comment by peyre** [comment]
Maybe after subtracting the flat 4 points of morale (as I think it does), the game could then add back 4 points - (astronaut level).  So you'd effectively lose only 1 point/turn if someone's in Advanced and you're on Astronaut Level 1.

**Comment by peyre** [comment]
Or maybe...after the game subtracts 4 points, someone in Advanced should the get back 8 - (2 * Astronaut level), so 6 at level 1, 4 at level 2, 2 at level 3.  That would make it a wash at level 2, and at level 1 astronauts would be actually a little excited to be being groomed for something special.

Or perhaps it should be 5 - Astronaut level, so a wash at level 1 and a slight drop for higher levels.  Any preferences?

**Comment by peyre** [comment]
I've just implemented the latter idea and ran a test.  Here's what I got with the Mercury 7:
`Astronaut  I   II   III   IV   Δ
Grissom    63  58  62  61  -2
Shepard   63  58  62  61  -2
Carpenter 68  63  67  66  -2
Schirra     78  78  82  81  +3
Cooper     73  68  72  71   -2
Slayton     73  68  72  71  -2`
