### ISSUE TITLE
Primary crew not removed by newscast

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#286]
On my first lunar landing this game, the newscast claimed the backup crew would fly the mission, but the primary flew instead:
![Backup Crew will fly](https://user-images.githubusercontent.com/3118014/67624052-054ac800-f7e1-11e9-8124-5ecfa7bd3320.png)
![Primary crew still there](https://user-images.githubusercontent.com/3118014/67624075-493dcd00-f7e1-11e9-9142-3f1320d3587d.png)
![Primary crew all right](https://user-images.githubusercontent.com/3118014/67624092-6e324000-f7e1-11e9-8432-641d69d327f3.png)

**Comment by rnyoakum** [comment]
It appears that you ran into event 85, which is very similar to event 50. Both events have the Primary crew contracting the common cold and the backup crew taking over (except USSR event 50 uses influenza). Comparing them, it's apparent there is a bug; the Event 85 code in news_suq.cpp concludes with:
```
    Data->P[plr].Mission[i].Crew = Data->P[plr].Mission[i].BCrew;
```
while the event 50 code concludes with
```
    Data->P[plr].Mission[i].PCrew = 0;
    Data->P[plr].Mission[i].Crew = Data->P[plr].Mission[i].BCrew;
```

Given that the events are practically identical, I'm tempted to handle the two events together - combine the `case 50:` and `case 85` statements in the switch statement so they trigger the same code block.

However, I'm concerned that the event doesn't change the Prime field for any of the assigned crew. Without resetting the Prime field, the astronauts will continue to be reserved for a mission they're not on. That's okay for the turn, I suppose, but any longer is problematic. The game may have a mechanism to check the astronaut pool and and reconcile any such issues, but if so I'm not familiar with it.

I'm also curious if one of them was supposed to have different news text, given that they're essentially identical, down to the same ailment.

**Comment by peyre** [comment]
Hm, that's interesting.  I think the two are meant to be handled identically.  Both cards show in the Companion, and there are two "Influenza" cards in Liftoff which have identical effects.

I don't know about the game having a bit where it checks the astronaut pool; of course we could always try it and find out.

**Comment by rnyoakum** [comment]
A few quick questions about how this should be handled:
- Should the Primary crew be available for future mission selection?
- If not, should the Primary crew be placed in the hospital?

I think the second option is a little extreme, but it would serve the purpose of keeping the crew unavailable.

**Comment by peyre** [comment]
Good questions.  First off, I'm pretty sure that when the game says the crew caught influenza, it really means the stomach flu, not actual influenza (which can be life-threatening).  I think we can assume that they have something they'll get over in a few days, or weeks at the most, so they could be scheduled for another mission.  That won't be for another six months, after all.  (It also makes it easy for us.)

Sending them to the hospital is a logical idea, but the main problem I see with that is that it breaks the crew and the player will have to go through setting it back up again (including remembering which fellows were in the crew.  Seems like more trouble for the player than it's worth.  The crew isn't supposed to have been seriously ill in any case, just too sick to fly right then.  I think we can just remove the crew from the mission and leave it alone.  That'd be simplest for us and for the player.

**Comment by rnyoakum** [comment]
I looked into this - sending the crew to the hospital is overkill. Taking the approach of event 50, the Primary crew will be removed from the flight but remain locked in - and inaccessible - until the end of the turn. At the beginning of the next turn, start.cpp/AstroTurn() will clear the Prime field, leaving them open for missions.

Unless you want to speed things up and make them available the same turn?

**Comment by peyre** [comment]
I wonder.  It seems to me, offhand, that a crew who comes down with a cold could be scheduled for a mission the following turn, since they'll be over the cold in a week or so and the next mission won't fly for half a year.  However, NASA was terribly picky about its astronauts getting sick, and maybe the agency would ground them for the equivalent of a turn.

I'm inclined to think we should follow the developers' lead on this and handle it the same way as event 50.  If a crew is kicked off a mission because they're sick, it might seem weird to be able to schedule them for another flight right away.

**Comment by rnyoakum** [comment]
Commit e379ebbd361995f3b1ced3fb8d1c0e4606ebe410 combines the event code for event 85 with event 50, which worked properly. This should be resolved.

**Comment by peyre** [comment]
Yay, thanks.  Must add that to the changelog.

**Comment by peyre** [comment]
Oh no!  I just got this newscast again, and it...removed the backup crew instead of the primary(!)

![Common Cold](https://user-images.githubusercontent.com/3118014/68533842-88d8de80-02e2-11ea-9ef8-9f77cb516799.png)
![Backup Unavailable](https://user-images.githubusercontent.com/3118014/68533851-a6a64380-02e2-11ea-8622-82e8e1bb0ae3.png)

**Comment by rnyoakum** [comment]
Okay - several questions here:

1. Do you have a copy of the savegame from the turn before / this turn that I could examine?
2. Did you have anything scheduled on Pad A? If so, the event should have targeted Pad A - even, it appears, if it was unmanned.
3. Is the flight crew number displaying correctly for Conrad / Young? What was the flight crew number for the backup crew?

**Comment by peyre** [comment]
1. Oh no!  No, I didn't copy off the save, but kept playing.
2. Yes, I think I had a Lunar Flyby or something, or possibly an unmanned docking.
3. Yes, they were Crew I if I remember right. I think the backup crew was Crew III.

**Comment by peyre** [comment]
Hey, I just experienced this newscast.  It does now remove the primary crew like it should.  I saw something unexpected though - Future Missions won't allow me to assign that crew to a mission next turn.  I don't know if this is supposed to happen, since the crew is currently sick (does it make them unavailable for a turn?), but if so, maybe (if you have other crews, when crew selection comes up), the affected crew should probably show as SICK or something instead of unavailable. 

In this case it's my only crew, so it shows a message saying I don't have enough to schedule a manned mission.

![PrimaryCaughtCold](https://user-images.githubusercontent.com/3118014/72116643-c3b9bb80-32ff-11ea-895a-ff4b7bf6ee45.png)
![HaveOneCrew](https://user-images.githubusercontent.com/3118014/72116654-cae0c980-32ff-11ea-9e3b-ac0ac1f385a3.png)
![InsufficientCrews](https://user-images.githubusercontent.com/3118014/72116660-cf0ce700-32ff-11ea-9f1b-12f5dfb3cbdd.png)

**Comment by peyre** [comment]
Oh, I see what's happened!  I created a second crew and tried scheduling the mission again, and saw that somewhere out there the crew hasn't been released.  The mission was canceled when I opened the Launchpad, not the VAB.  Normally I'd use the VAB, but I wanted to see what would happen.

![StillAssigned](https://user-images.githubusercontent.com/3118014/72116778-30cd5100-3300-11ea-8966-a266ef64d904.png)

**Comment by rnyoakum** [comment]
Aha! So, I believe this is what's happening:

The news text says that the 

> Primary crew of the **first** launch has caught the common cold

and the game takes that literally. I think it's replacing the crew, but only if it's the very first mission launch. Does pad A have an orbital satellite? Then your Direct Ascent lunar launch crew on Pad B has a mechanically-gifted immunity. For two-part single crew missions, I don't remember if the crew is always on the first or second pad (I think the second), but if they're on the second they would also be immune.

I should be able to rejigger the code and ensure it applies to the first **manned** launch of the season.

**Comment by peyre** [comment]
Well, I'll be!  So much for my reading comprehension.  You're probably right--I'll keep an eye out for this one.

**Comment by peyre** [comment]
Say, is this one ready to be closed?

**Comment by rnyoakum** [comment]
Uh, not yet - I'd kinda forgotten about this particular issue. As I wrote above, I should be able to have it apply to the first manned launch of the season. If the event isn't having an effect, it shouldn't show up because it causes the confusion we experienced, but I  think making it work as expected is the better play. Should be an update soon.

**Comment by peyre** [comment]
Oh thanks, I missed that coming back to it.  Well no hurry, this is a lower-priority item as far as I'm concerned.

**Comment by rnyoakum** [comment]
I've got the fix ready to go, except for the question of how to deal with the flu-stricken flight crew. Do you think they should remain unavailable for the rest of the turn, or should the flight crew be made available for another mission?

**Comment by peyre** [comment]
I think they should be available for scheduling.  The assumption is that it's a short-term illness like a bad cold: weeks, at most, whereas a turn is 6 months.
