### ISSUE TITLE
Astronaut transfer card not working

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#290]
The American text for news event 89 is

> ASTRONAUT c ANNOUNCED A TRANSFER TO THE AIR FORCE TEST PILOT PROGRAM.

while the Soviet text is

> COSMONAUT c HAS BEEN DISCIPLINED AND TRANSFERRED FOR RE-EDUCATION.

However, the event instead results in the astronaut/cosmonaut being injured and placed in the hospital.

EDIT:
I had said:

> It's also supposed to only target inactive astronauts, but I had it affect an astronaut when he was the Primary Crew on a Manned Orbital EVA.

but on reflection that clearly means not dead, injured, retired, or in training.

**Comment by peyre** [comment]
Wow, sending them to the hospital when they've supposedly been transferred?  That is odd.  It sounds vaguely familiar too, IIRC.  That's another good catch.

Hey, when someone does leave your spacecraft, could we have it display the reason ("for business opportunity", "due to safety concerns", etc.) in Astronaut History?

**Comment by rnyoakum** [comment]
That's issue #172 - there are a couple of issues with making it work, however:

- There's not a lot of screen space to work with
- I don't think every retirement event gets a distinct code.

The former reason is a hassle to deal with, aesthetically. The latter is harder to handle, and can probably be handled (there are plenty of codes available) but would require a lot of work. So it's lower priority than some of the big issues, like finishing Manned -> Unmanned downgrading and decoupling the data files & data structures.

**Comment by rnyoakum** [comment]
There's usually a longer delay when astronauts announce retirement than when cosmonauts do - I plan to handle this the same way, with a 1-year delay on retirement for the US event and immediate retirement for the USSR event. This is both consistent with other events and reflects the event text.

**Comment by peyre** [comment]
I agree, it's not a high-priority item by any means; it is, after all, esthetic, though it would provide a nice bit of flavor.

The lack of screen space is an important point.  It would be really difficult to fit in "for business opportunity", for instance.  If this were done, perhaps the "11 of 19" counter could be moved beneath Location, and the reason could show directly below "Retired", lined up with it, something like this. 
![Cosmonaut History](https://user-images.githubusercontent.com/3118014/67702974-e4fd4380-f96f-11e9-8017-29638161c7a0.png)

But, again, this is just esthetic, low priority.  I just thought I'd mention the idea while we were on the subject of retirement.

**Comment by peyre** [comment]
I didn't realize that, the delay discrepancy!  That must have been intentional; I think you're right to have this work the same way as other retirements.

**Comment by rnyoakum** [comment]
Commit c831cb9f20c50a3c7947a50d900553cb79e56451 fixes this. The American astronaut will retire in one year while the Soviet cosmonaut will retire immediately.
