### ISSUE TITLE
VAB showing rocket/booster combo in wrong color

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#298]
I have noticed that once in a while (I think maybe with just this particular mission, but I'm not sure), the VAB doesn't print the rocket/booster combo in a different color to show it can't lift the current payload.  It might be that it misses it when the payload is _just_ a little too heavy for the rocket combo, which only occurs in a few rare occasions such as a lunar pass with the XMS-2, a B-Kicker, and a boosted Titan.  In the past this has led me to accidentally autopurchase the rocketry for a mission I can't fly, since the eye focuses on the color of the rocket/booster down below, and not the current payload up at the top.

![Boosted Titan](https://user-images.githubusercontent.com/3118014/69012330-80f3ec80-0929-11ea-9ed9-dab2f906aad5.png)

(In case anyone needs a quick screenshot for comparison, this is how the rocket/booster combo should look at the bottom of the screen:)
![Titan](https://user-images.githubusercontent.com/3118014/69012340-99640700-0929-11ea-80f2-657b642b2316.png)

**Comment by peyre** [comment]
This is interesting.  On a Joint Lunar Orbital LOR LM Test it _does_ show it in the right color.

![Jt Lunar Orb LOR](https://user-images.githubusercontent.com/3118014/69482141-7c698100-0dcc-11ea-8e87-9ff38529a16e.png)

**Comment by peyre** [comment]
On the other hand, when assembling that mission, when I switched the LM from the Eagle to the Cricket, ti should have changed the color of the rocket/booster combo but it didn't.

![Rocket combo in wrong color](https://user-images.githubusercontent.com/3118014/69482161-a8850200-0dcc-11ea-99c7-fb56978bec32.png)

**Comment by rnyoakum** [comment]
So what this is doing is basing the coloring of the rocket on whether or not the rocket can launch the _default_ payload. I imagine the intent was that the first payload selection would be the lightest payload possible, or that all payloads would be examined to find the lightest, but that doesn't appear to be the case. It's hard to divine intent from looking at the code in cases like this. So there are two options I can offer:

1. Calculate the lightest available payload, and color the rocket listing based on that weight, or
2. Color the rocket listing based on the currently selected payload.

**Comment by peyre** [comment]
I think the color should reflect what's currently selected.  When I assemble a mission, I look at the color of the rocket combo to see if it will lift the payload.  When you change the payload, the rocket combo should change color to reflect whether it can lift the current payload.

**Comment by rnyoakum** [comment]
This should be fixed by commit 5cf6895dcefcd2c79c152b2219de85271b70600d.

**Comment by peyre** [comment]
Awesome, I look forward to testing it.

**Comment by peyre** [comment]
I know it's been a while, but hey it's the holidays.  I just played a game flying the XMS-2, and confirmed that this is working properly now, at least with the combo that prompted me to create this issue in the beginning.
