### ISSUE TITLE
Visual artifacts in Astronaut wings, medal

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#299]
In the discussion of #192 Leon noticed visual artifacts in the Astronaut History:

> Say, anyone else notice the artifacts above?  The vertical line just past the astronaut wings, and the vertical colored stripe to the right of the medal?  I've been looking through the museum file but can't seem to find where they're drawn, and I don't see any images for them in gamedat.
> _Originally posted by @peyre in https://github.com/raceintospace/raceintospace/issues/192#issuecomment-530493473_

I've verified this is a distinct issue from the mechanic causing the Astronaut History to crash, so I'm creating a new issue to handle it. The explanation is:

>The image data is stored in arrows.but, which contains seven images used in Astronaut History:
>
> 0. The Left All arrow icon
> 1. The Double Left arrow icon
> 2. The Double Right arrow icon
> 3. The Right All arrow icon
> 4. The USA Hero medal
> 5. The USSR Hero medal
> 6. Astronaut/Cosmonaut flight wings
>
> Each image in the arrow.but file has a header at the beginning of the file, specifying the width, height, size (in bytes), and the data's location in the arrow.but file (as a byte offset from the start of the file).
> 
> For the USA Hero medal, USSR Hero medal, and flight wings, there is an error in the image data. There is a discrepancy in the width * height vs. the size, with the size - and file space allocated - being calculated as if the width was one larger. However, the listed width value is correct, the file space is too large, and every (width + 1)-th byte is simply nonsense.
> _Originally posted in https://github.com/raceintospace/raceintospace/issues/192#issuecomment-554593278_

**Comment by peyre** [comment]
Capital!  Good spotting, Ryan.

**Comment by rnyoakum** [comment]
This appears to be fixed by commit 8c0c55642165ccd803284bd686b741ab92fe359c.

**Comment by peyre** [comment]
I believe you've fixed it!  Thanks, I know that was totally esthetic but it was a little thing that always bugged me just a little.
