### ISSUE TITLE
Astronaut History duration

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#300]
While looking at the Astronaut History in the Space Museum, I noticed that the Space Duration didn't line up with the actual time spent in space:

![baris-duration](https://user-images.githubusercontent.com/44246332/68987604-1f346500-07f9-11ea-896e-6c7847c12ed9.png)

The astronaut shown, having completed a single mission of duration B, is listed as having a Space Duration of 5.

**Comment by peyre** [comment]
Hum, I wonder if it's showing the maximum duration for a Dur B mission (3-5 days, so it shows 5).

**Comment by rnyoakum** [comment]
Yeah, you're right. I looked in mc.cpp / MissionPast() and that appears to be exactly what is happening. I should probably add in some "Days" text to Astronaut History so it makes more sense (and make sure Sub-Orbitals aren't being treated as Duration A for this purpose). Thanks for the catch!

**Comment by peyre** [comment]
Glad I could catch something!  You've been puzzling out so many of these little things that eluded me,  I'm glad I could contribute.

Assuming that was right, maybe we should add "DAYS" after the number.

**Comment by peyre** [comment]
There, I've added " DAYS" to museum.cpp; I'll upload it to the repository.

**Comment by peyre** [comment]
It looks like there's still an issue with the second mission showing to be truncated to the first letter.  Also, it looks like the game assigned a figure of 2 days to this fellow's suborbital mission.  That's a very long suborbital! ;)  It looks like the game assigns the upper end of a Duration level (2 for A, 5 for C, etc.).  I wonder if we should have a special exception for suborbitals to assign them 1 day.

![Astronaut History](https://user-images.githubusercontent.com/3118014/71645945-79e42c00-2c94-11ea-8f38-e5016a260763.png)

**Comment by rnyoakum** [comment]
I might have done something to affect this in the past, not recognizing what it was doing. What duration should be used for a suborbital, 0 or 1 days?

**Comment by peyre** [comment]
I think 1 day would be fine.  It might seem like stretching it to call a 15-minute flight "1 DAY", but 0 days would sound like not giving him credit for a space mission.

**Comment by peyre** [comment]
Incidentally, like we added DAYS to this screen to be more specific about SPACE DURATION, I've also added SEASON (or SEASONS) to tenure in Basic and Advanced Training.

**Comment by peyre** [comment]
Strange, I never noticed this before: Duration C us unusually narrow, and D unusually broad:
A  1-2 days (2)
B   3-5 days (3)
C  6-7 days (2)
D  8-12 days (5)
E  13-16 days (4)
F  17-20 days (4)
I assume this was done for historical reasons, so I would be loathe to change it.  Anyhow, I have some ideas for working on the issue above, that the game always gives the max number of days for a mission of a given duration level.

**Comment by peyre** [comment]
Ok, I've done it!  The game now assigns a range of days rather than the maximum for each.
A (1-2) - Suborbital, Orbital, Orbital EVA = 1; Docking & Earth LM Test = 2 days
B (3-5) - Duration, Dur EVA = 3 days; Jt Docking = 4 days; LM Test = 5 days
C (6-7) - Duration = 6;; MOL, Lunar Pass = 7 days
D (8-12) - Duration = 8; Single Lun Orbital = random 8-11; Jt Lun Orbital, any Lun Landing = random 9-12 days
E (13-16) - Random 13-16 days
F (17-20) - Random 17-20 days

![3Days](https://user-images.githubusercontent.com/3118014/86518507-0eb41780-bde7-11ea-988a-8930050c6e42.png)
