### ISSUE TITLE
Have Mission Control show current penalties

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#320]
At this point in this game I'm currently on, the mission faces a -4 penalty since I haven't flown the lunar orbital yet.  I wonder if we should have Mission Control display the current safety penalty, if any.  Here, for instance, it would show -4, then -7 if I rushed it a month.  Or, the -4 would drop to -1 or 0 if I downgraded to a mission that doesn't have a milestone penalty.

![Mission Control](https://user-images.githubusercontent.com/3118014/73237093-69b35580-4149-11ea-9814-712a131cdb5e.png)

**Comment by rnyoakum** [comment]
It should be possible to show what the current penalty would be for the mission/downgrades. The biggest concern is the UI, i.e. where does it get displayed?

Currently the downgrade penalty is disabled, so the space beneath the Rushing Penalty is available. However, should the downgrade penalty be restored - more likely as a configurable option - that would eat up the space. It might be possible to do it as a floating tooltip, but that system doesn't exist yet.

**Comment by peyre** [comment]
So that space was supposed to display the penalty for downgrading?  That sounds like a great place to put it, since we don't want downgrade penalties to be applied and have no plans to implement them.

**Comment by peyre** [comment]
By the way, your implementation of the ability to downgrade duration levels on a mission is brilliant - and more elegant than what I had suggested.  That's a big help to players since the duration penalty system is working again.

    On Tuesday, January 28, 2020, 1:35:05 PM PST, Ryan Yoakum <notifications@github.com> wrote:  
 
 
It should be possible to show what the current penalty would be for the mission/downgrades. The biggest concern is the UI, i.e. where does it get displayed?

Currently the downgrade penalty is disabled, so the space beneath the Rushing Penalty is available. However, should the downgrade penalty be restored - more likely as a configurable option - that would eat up the space. It might be possible to do it as a floating tooltip, but that system doesn't exist yet.

**Comment by peyre** [comment]
Given the amount of space available there, maybe it would be good for the line to read, e.g.:

-9%: MILESTONE-3 DURATION-5 NEWMIS-1
or
-1%: NEWMIS-1
or
-10%: DURATION-5

But...I'm not sure we could fit all of the first example in one line there.

**Comment by peyre** [comment]
On second thought, the best thing would probably be to print it right under RUSHING PENALTY, just the total milestone+duration+firsttime figure, e.g.:
RUSHING PENALTY: 0%  COST: 0MB
MILESTONE/DURATION PENALTY: 4%
That would be for scheduling your first Manned Orbital.

**Comment by rnyoakum** [comment]
I tested adding the MILESTONE/DURATION PENALTY line, and it feels a little crowded.

![RIS-schedule-1](https://user-images.githubusercontent.com/44246332/82507740-163a8e00-9ad1-11ea-8744-847f71e8eac2.png)

I'm wondering if the text should be something shorter like "MISSION PENALTY" - it's less specific but still conveys the general idea.

![RIS-schedule-2](https://user-images.githubusercontent.com/44246332/82507950-a547a600-9ad1-11ea-8ec3-e4cfccf9a257.png)

If a display like "MISSION PENALTY" is used, it could be updated to account for the Rushing penalty as well, to be explicit.

Another possibility would be to simply replace the "RUSHING PENALTY" text with "MISSION PENALTY" and show the total penalty:

![RIS-schedule-3](https://user-images.githubusercontent.com/44246332/82508476-28b5c700-9ad3-11ea-8a3b-0a4d33204d89.png)

**Comment by peyre** [comment]
Oh, [b]cool[/b]!  I think I like your second example best (though I would change it from, say, "-1" to "1%".

That does highlight the issue that players may be confused by "Why doesn't the 'mission penalty' change with the rushing penalty?", but I think it'd probably be ok.

**Comment by rnyoakum** [comment]
The MISSION PENALTY display *could* change along with the rushing penalty. I imagine that would remove the confusion. Would you rather it reflect the rushing penalty or only the Milestone/Duration penalty?

**Comment by peyre** [comment]
I don't know; I kind of like having it separate from the rushing penalty.  Maybe change Mission Penalty to Other Penalties?  How would that look?

**Comment by rnyoakum** [comment]
Okay - I'll plan on keeping it separate from the Rushing Penalty. I don't really like Other Penalties, because that's a little vague and things like equipment penalties aren't taken into account, but Milestone/Duration Penalty is too long. How about "Requirement Penalties?"

**Comment by peyre** [comment]
Oh yeah, that sounds good.

**Comment by rnyoakum** [comment]
This should be handled now. This uses the screen area that had been reserved for displaying downgrading penalties. The prestige penalty for downgrading a mission is not implemented, but if it ever is (likely as a configurable option) the conflict will have to be resolved.

**Comment by peyre** [comment]
That's great!  I'll check it out Saturday morning.

I hope never to have the downgrade penalties enabled so it shouldn't be a problem, but if we ever do (and as you say, if we do, it should be an opt-in in Advanced Preferences), we'll have to see.

**Comment by peyre** [comment]
Hey, I know!  If Downgrading Penalties are ever implemented, it could go where it was supposed to, and the Requirement Penalties could be moved onto the button, just below the mission descrtiption.  I assembled the longest-named mission I could find, and the description in the button was still on one line, because it's heavily abbreviated:
![Penalties](https://user-images.githubusercontent.com/3118014/83334222-cdfe3700-a259-11ea-84ef-de8c71a7e6c8.png)
