### ISSUE TITLE
Add PgUp and PgDn and/or Home and End functionality to Prestige Summary

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#351]
Prestige Summary is one of the few places you can get something of a bird's-eye view of where you are in your space program: what you've accomplished so far and what you haven't.  However, it's awkward to use: partly because it's a prestige summary, not an event summary, but also because the only way to navigate in it is one line at a time.

![PrestigeSummary](https://user-images.githubusercontent.com/3118014/80004812-a3a9a480-8477-11ea-932d-89956811077c.png)

**Comment by peyre** [comment]
The Mission Records screen could also benefit from this functionality.   Both are in museum.cpp, if I'm not mistaken.

**Comment by peyre** [comment]
Ugh, museum.cpp is much uglier and more convoluted than I anticipated.  Deassigning myself because I don't think I can do this one.

**Comment by peyre** [comment]
I got back at it today and added the functionality to the Missions Records and Prestige Summary screens.

**Comment by peyre** [comment]
The Help pop-up should also have Home, End, PgUp, and PgDn functionaltiy.

**Comment by rnyoakum** [comment]
>The Help pop-up should also have Home, End, PgUp, and PgDn functionaltiy.

I moved this to its [own issue](https://github.com/raceintospace/raceintospace/issues/468); it's different and this issue is already completed.
