### ISSUE TITLE
helpText i000 and k000?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#378]
I noticed the other day that some of the files in the code call helpText i000 and keyHelpText k000, but those don't exist in help.cdr.  Are those placeholders or something, or should we create entries for those in help.cdr?

The files that call i000 and k000 are museum.cpp, intro.cpp, game_main,cpp, admin.cpp, aipur.cpp, port.cpp, and endgame.cpp.

**Comment by rnyoakum** [comment]
These are non-entries. When `helpText` or `keyHelpText` are set to `x000`, it disables the corresponding Help dialogue. So if there is a section of the game where a Help or Key Help popup is inappropriate (such as when waiting on the AI to complete its turn) setting `helpText` or `keyHelpText` to `i000` / `k000` clears the assigned help codes.

**Comment by peyre** [comment]
Thanks!  I wondered if it was something like that.
