### ISSUE TITLE
News event 91 doesn't occur

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#397]
The beneficial budget event

> Event 91
> IN THE NEWS TODAY, THE PRESIDENT HAS ANNOUNCED THAT THE SPACE PROGRAM WILL PUT A MAN ON THE MOON WITHIN THREE YEARS. FUNDING HAS INCREASED BY 20 M.B.'S TO SUPPORT THIS EFFORT.

looks like it will never trigger. Early on in the src/game/news_suq.cpp `REvent()` function that handles news events, there's a check
```
    if (Data->Year <= 65 && Data->Events[Data->Count] > 80) {
        return 1;
    }
```
which causes the News to skip any event ID 81+ if it would occur before 1966 (and replace it with a "flavor" event). However, in the code for event 91

```
    case 91:  // increase budget by 20MB's in the budget
        if (Data->Year > 65) {
            return 1;
        }

        Data->P[plr].Budget += 20;
        break;
```
there's a check to skip the event if the year is greater than 1965. In combination, these two checks should effectively prevent event 91 from ever being seen - which is a shame, because it's a true blessing! I'm thinking the check for event 91 is a typo, meant to stop it from triggering before '65. Because it makes more sense to have a three-year goal for a Lunar Landing set after 1965 than before, I was thinking of dropping the check in case 91.

_Originally posted by @rnyoakum in https://github.com/raceintospace/raceintospace/issues/394#issuecomment-661613040_

**Comment by peyre** [comment]
Yes, another good catch.
