### ISSUE TITLE
Graphic for damaged/destroyed launch pad

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#412]
I've recently noticed that if one of your pads is damaged or destroyed, while it shows a trashed pad graphic in your spaceport (usa_port.dat.36.png for instance), if you click on the launch facility, that screen comes up showing a graphic for a healthy one (lfacil.but.0-5.png).  This is just esthetic of course, but it might be handy if we created an lfacil graphic showing a damaged pad.

![lfacil but 0](https://user-images.githubusercontent.com/3118014/89714839-64d02980-d956-11ea-9566-7c40671c5b17.png) ![lfacil but 1](https://user-images.githubusercontent.com/3118014/89714840-6568c000-d956-11ea-897b-c2bda80e62e6.png) ![lfacil but 2](https://user-images.githubusercontent.com/3118014/89714842-6568c000-d956-11ea-9f67-e6152d161156.png) ![lfacil but 3](https://user-images.githubusercontent.com/3118014/89714843-66015680-d956-11ea-8dba-b6cc8a9a2517.png) ![lfacil but 4](https://user-images.githubusercontent.com/3118014/89714844-66015680-d956-11ea-96d5-96f883727ad9.png) ![lfacil but 5](https://user-images.githubusercontent.com/3118014/89714845-6699ed00-d956-11ea-86ca-984f62d40307.png)

**Comment by peyre** [comment]
Ah, looking closer, I see the first one is supposed to represent a damaged US pad (which looks about right, now I think of it), and the second is supposed to be a damaged Soviet pad (when in fact it shows a pad in good condition with a rocket at it).

**Comment by peyre** [comment]
I've replaced the US image with one that's more obviously damaged, and the Soviet one also looks damaged now.

![lfacil but 0](https://user-images.githubusercontent.com/3118014/89721990-8e11a980-d998-11ea-8a81-7e46aceec4fa.png)
![lfacil but 1](https://user-images.githubusercontent.com/3118014/89721991-8e11a980-d998-11ea-8ecf-ab151cffbb43.png)

**Comment by peyre** [comment]
If someone would like to improve the images I put up there, please feel free. I'm no artist, and my artwork there is admittedly crude.

**Comment by peyre** [comment]
I just had an R-7 explode on the pad, with the error below.  It 

EXPLOSION ON PAD. LAUNCH FACILITY, COMPONENTS AND FLIGHT CREWS DESTROYED. LAUNCH FACILITY MUST BE REBUILT.

**Comment by hweimer** [comment]
It's straightforward to have a repair cost of 20 MB or more (and not just 20 MB exactly) to show the pad as destroyed rather than damaged. Newscasts can only damage by 10 MB or 15 MB (events 36 and 64, respectively), so nothing to worry about.
