### ISSUE TITLE
CRC error?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#417]
I'm in the middle of a game, and in R&D, whenever I arrow (either left or right) to the N1, the command line shows CRC error, though it doesn't cause trouble within the game.  It doesn't do this with other components, as far as I know, certainly not with other rockets.  Any idea what's causing this?

![CRC-error](https://user-images.githubusercontent.com/3118014/90170996-b103db00-dd55-11ea-8786-28f153e8448d.png)

**Comment by pemensik** [comment]
It would be some png game data encoding error. But we should somehow track and print name of offending files. Do you know minimal way to reproduce this?

**Comment by rnyoakum** [comment]
The file is data/images/rdfull.but.42.png and the error can be reproduced by starting a USSR game, entering the R&D facility and buying the N1 rocket program. Anytime the image displays in Hardware Purchasing or R&D the warning is triggered.

**Comment by peyre** [comment]
Yes, that's right.  It's very easy to reproduce.

...come to think of it...that's a file I modified to look a bit more like the real thing - the old image had it too wide at the bottom.  But if my edited image is causing trouble, maybe we should roll back to a prior version.

**Comment by peyre** [comment]
I redid the N1 image just to see if that would still cause CRC errors, and it looks like it doesn't!

![rdfull but 42](https://user-images.githubusercontent.com/3118014/91666457-c432dc80-eab1-11ea-9ebf-78cde7d4f0fe.png)
