### ISSUE TITLE
No room to show LM with shuttles in VAB

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#418]
Similar to the CRC error (#417), when I go to assemble a Hitorical L.L. in the VIB, the command line gives an error saying it can't fit the LKM image, though again it doesn't affect gameplay.

![LKM](https://user-images.githubusercontent.com/3118014/90172106-5ec3b980-dd57-11ea-8ff9-189596ee4116.png)

**Comment by peyre** [comment]
Oho!  I get the same message for the LK if I change the payload.  Must be that there isn't room for the image of the lunar module when your main spacecraft is a shuttle.

![LK](https://user-images.githubusercontent.com/3118014/90172299-a8140900-dd57-11ea-9108-2fa634ad6880.png)

**Comment by pemensik** [comment]
Can you please attach savegame with prepared turn to reproduce this?

**Comment by peyre** [comment]
I've created a pretty bare-bones one but it should do the trick.  Sent to your email.

**Comment by peyre** [comment]
I flew XMS-2 this past weekend and noticed that I didn't get this warning with XMS-2.  I think the graphic of the US shuttle is shorter than the Soviet one, so the issue doesn't come up.  Maybe if we shorten the Lapot a bit this would disappear.

**Comment by peyre** [comment]
Of course, I could shorten the image itself easily, but I don't know where I would go to tell the game to change the dimensions of the vehicle.

**Comment by peyre** [comment]
Just as an initial attempt, here's a shortening to 54px in height.

![Lapot](https://user-images.githubusercontent.com/3118014/141024850-c4088adb-0ee8-4a2e-90c6-10dc6903b88a.jpg) -> ![ShortLapot](https://user-images.githubusercontent.com/3118014/141024852-1e34d0d5-d528-4468-89f6-2f89647f15b4.jpg)

**Comment by peyre** [comment]
Yep, looks like that just centered the shuttle vertically.  I figured it would, but couldn't hurt to try.

![VIBSmallerLapot](https://user-images.githubusercontent.com/3118014/141046576-885ee26e-75a9-46ad-9734-734a14ebd303.png)

**Comment by peyre** [comment]
So, this weekend I've been tinkering with vtable.dat.  It looks like the B-Kicker is controlled in column 3 of 01B0.  The Lapot's horizontal placement is the first digit in the 3rd column of 0160.  Its vertical placement is the first digit in 3rd column of 0100.  I still can't seem to find where to change it so it knows the shuttle should be shorter than it is now.

**Comment by rnyoakum** [comment]
Yeah, vtable isn't user-friendly, given that it's meant to be read quickly and take up little space. Here's a quick summary:

The vtable.dat is 560 bytes, holding 56 consecutive entries that specify the image locations for each component image in the VAB sprites. The first 28 entries are for the USA sprite (vab.img.0.png) and the second 28 entries are for the Soviet sprite (vab.img.1.png). Each entry is 10 bytes long. The order of the entries is hard-coded into the source code; consult the enumeration `VabSprite` in src/game/vab.cpp.

Example: To find the information for the Lapot minishuttle, I'd check vab.cpp to find that `VabImg_Minishuttle` is the 17th entry. Accounting for the 28 preceding US entries, I'd check 440 bytes (0x01b8 in hex, for everyone with a hex editor) into the file.

Each entry in the file is formatted as _(x1, y1, x2, y2, yOffset)_, each value stored as a 16-bit integer. In each entry
- ***x1, y1*** is the top-left coordinate of the image in the sprite
- ***x2, y2*** is the bottom-right coordinate of the image in the sprite
- **yOffset** is the y-offset to use from the top of the rocket casing, when the component is the top payload image.

For the Lapot, as of commit 01f4d9da40a6c2cfa58a31a8351d1a3c675994da this is

> 000001b8: f900 8400 1301 c100 0b00

these translate to (249, 132, 275, 193, 11), which matches the old image. So if you've shortened the image, you would probably want to modify the y2 value.

**Comment by peyre** [comment]
Wow!!  Thanks.  I'll get after it soon.

**Comment by peyre** [comment]
Brilliant!  Thanks to you I was able to nail it, Ryan.  I was able to shorten the Lapot enough that it doesn't error out, and it shows the lander now.

![LapotBefore](https://user-images.githubusercontent.com/3118014/143473270-9b9ea90d-35da-4488-a0f7-16a9df2b014a.png)
![LapotAfter](https://user-images.githubusercontent.com/3118014/143473279-d3f82648-5c21-4b15-8f06-6e8fc5eb0747.png)

**Comment by peyre** [comment]
Uh oh!  I must've done something wrong.  I just found that if I click in the box to change payloads, the game crashes.  This happens with both LK and LKM.  The error reads:

**Comment by peyre** [comment]
Ah!  Fixed it.  I just needed to tweak a value in vtable.dat.
