### ISSUE TITLE
Artifact in Future Missions

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#425]
In Future Missions, if you select a capsule with no crews, you get the help window telling you so.  When you hit Continue to go back, bits of the bottom left & right of that help window stay on the screen.

![FutureMissions0](https://user-images.githubusercontent.com/3118014/90984650-26786400-e52b-11ea-8ba3-b868e734530e.png)
![FutureMissions1](https://user-images.githubusercontent.com/3118014/90984651-2710fa80-e52b-11ea-807a-a07f190f69c3.png)
![FutureMissions2](https://user-images.githubusercontent.com/3118014/90984652-27a99100-e52b-11ea-9199-b8ff9c690642.png)

**Comment by peyre** [comment]
I also just noticed an artifact after withdrawing someone from Basic Training:

![Withdraw](https://user-images.githubusercontent.com/3118014/90985116-87556b80-e52e-11ea-862c-7db621952b61.png)

**Comment by rnyoakum** [comment]
This is an issue with the `Help()` function; it's supposed to cache the screen area, draw the help popup, and redraw the original original screen from the buffer after the help popup closes. This looks like it's not caching a large enough area, which is new.

I'd start by examining the relevant Help file entries for any errors, since I don't believe the Help function has been changed recently.

**Comment by peyre** [comment]
I think you're right.  I also get it if I hit the flagpole and say No to the warning about continuing even though I haven't scheduled any missions for next turn.

![End1](https://user-images.githubusercontent.com/3118014/90989051-7fa4bf80-e54c-11ea-9ca5-6a5e919959fe.png)
![End2](https://user-images.githubusercontent.com/3118014/90989053-803d5600-e54c-11ea-9f96-4820780eda57.png)

**Comment by rnyoakum** [comment]
I hate to say this, but [you're the villain](https://github.com/raceintospace/raceintospace/commit/75925c3574bb8354ab57966b449e880e030b1e97) in this issue.

I'm not sure what you were trying to do in the commit - contrary to the commit message, it's not undoing anything in your [previous commit](https://github.com/raceintospace/raceintospace/commit/11978986d83d8d4b29999d22320dc0259f74f2b8). It does lengthen the Help box's height by 10 pixels. Those extra 10 pixels aren't being buffered when the Help popup is drawn, and thus that part of the background isn't being redrawn when the Help popup is closed.

**Comment by peyre** [comment]
Uh oh!  Figures it would be something I did.  How do I fix it?

**Comment by rnyoakum** [comment]
Just revert the line - it's line 520 in src/game/place.cpp. Change it from
`     ShBox(34, 32, 283, 169); `
to
`     ShBox(34, 32, 283, 159); `

**Comment by peyre** [comment]
Oh I see!  That's one of the little changes I made when I was trying to find where the game drew the yellow box around the main game options, before I finally realized it's a static image.  I thought I had undone all my tinkerings, but I must have gotten excited and missed one.  Thanks, I'll correct it.
