### ISSUE TITLE
Have the game distinguish a damaged pad from a destroyed one

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#426]
When a pad is damaged or destroyed, the game doesn't distinguish between the two except when it's first announced: instead it has a **Data->P[plr].LaunchFacility[pad]** equal to the cost to repair/rebuild the pad, and that's how various screens know whether the pad is operational.  Consequently these buildings would show a pad as DAMAGED if the value is over 1, except the launch pad screen would show it as DESTROYED.  We don't want to have the various buildings showing an inconsistent status, even though it's really just esthetic.  For the time being I've changed the launch pad to show DAMAGED instead, figuring it's better to call a destroyed pad "damaged" than a damaged pad "destroyed".  But it would be a nice extra if the game would keep track of that and reflect it in these screens.  Perhaps it could have a boolean value of **Data->P[plr].LaunchFacilityDestoyed[pad]** or something like that.

**Comment by rnyoakum** [comment]
This would require more research, but is it possible to distinguish between the two on the basis of cost? The event cards damage the Launch Facility by directly setting the cost, but never to 20. The mission code uses the `DestroyPad` function to damage the launch facility. In at least one case, the comments describe the pad as "destroyed" and set the cost to 20. The cost of the others is not as easily checked.

It's quite possible a "Destroyed" pad is one that costs the full value of the pad to repair (20MBs) while a "Damaged" one is a pad whose repair cost is less than the full value.

**Comment by peyre** [comment]
Oh, that's a good question!  I know a damaged pad sometimes costs 25, more than a destroyed one (presumably due to extra demolition cost), but I don't know of it ever setting a damaged one to 20.  I'll have to give it a try and see.

**Comment by peyre** [comment]
I think I've gotten this one working, so I'll close it.
