### ISSUE TITLE
AstroTurn comments don't match code

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#428]
In the astronaut update code, there's a difference between some of the code comments and the game code. After a catastrophic failure, the astronauts in the program must test to see if they get scared and retire:

```
if (num > temp && cnt < (ActTotal[j] * .4)) {
    /* Guy retires due to being scared */
    if (j == 0) {
        Data->P[j].Pool[i].RetirementDelay = 3;  /* US Guy Retires in 2 */
        Data->P[j].Pool[i].Special = 1;
    }

    if (j == 1) {
        Data->P[j].Pool[i].RetirementDelay = 2;  /* URS Guy Retires Now */
        Data->P[j].Pool[i].Special = 1;
    }

    Data->P[j].Pool[i].RetirementReason = 11;    /* Reason=Scared */
}
```

For cosmonauts, the comment suggests they retires immediately, while the code has the cosmonaut retiring **after** the next turn. There are other USA/Soviet retirement differences for various retirement causes, but they don't follow a consistent pattern, so I'm not sure which is intended: the comment or the code.

Even more importantly, there's another comment/code disagreement when checking if astronaut/cosmonauts are mustering out:
```
/* Mustering Out - even seasons after 8 */
if ((Data->P[j].Pool[i].Active >= 8)
    && Data->P[j].Pool[i].Status == AST_ST_ACTIVE
    && Data->P[j].Pool[i].RetirementDelay == 0) {
        num = brandom(100);

        if (num > 89) {
            /* Guy retires */
```
In this case, the comment suggests astronauts / cosmonauts are tested for retirement every other season, but the code tests for retirement each season.

@peyre - Since you're the most authoritative source on gameplay, I was hoping you could issue a ruling on these items. Are they bugs or are the comments wrong?

**Comment by peyre** [comment]
Well, that's a tough one.  I'm really not sure.  My guess is that the comments indicate what the developers intended.  It makes sense that astronauts and cosmonauts should be handled the same way; maybe we should have both retire that turn rather than next?

**Comment by rnyoakum** [comment]
There are three other times in the function where cosmonauts and astronauts are treated differently

- Cosmonauts retire in one turn after mustering out, astronauts in two
- Cosmonauts are less likely to retire after a catastrophic failure (10% vs 20%)
- When mood reaches 20 or less, astronauts retire in two turns, cosmonauts immediately.

so I'm not surprised by a USA/USSR discrepancy, just a comment vs. code discrepancy.

**Comment by peyre** [comment]
Huh.  Well...I'm not sure, and I don't have strong feelings about it.  Again, my guess is that the comments reflect what the programmers had in mind, but it's hard to say.  (Am I right in thinking "URS Guy" is a typo?)

**Comment by rnyoakum** [comment]
> Am I right in thinking "URS Guy" is a typo?

The International Olympic Committee (and ISO 3166-1) three-letter code for the Soviet Union is URS, so I think that's intentional.

**Comment by peyre** [comment]
Wow, good catch!

**Comment by rnyoakum** [comment]
> Huh. Well...I'm not sure, and I don't have strong feelings about it.

The first issue, the retirement delay, is probably only relevant if the cosmonaut in question is assigned to a mission. The second issue, the retirement check, is something that will make a big difference with early astronauts/cosmonauts. Only AST_ST_ACTIVE crew get checked, so it won't affect astronauts/cosmonauts who are injured or in the hospital, but their Active count keeps ticking up regardless.

Personally, I favor going with the comments, because comments are _supposed_ to explain what the programmer intends; that's what makes comments useful in understanding code and debugging. But the mustering-out check is impactful enough I wasn't going to change functioning code without checking in.


P.S. The retirement issue makes me think there should be a popup warning ("Are you sure...") when a player is about to assign a flight crew with a member who will retire before launch.

**Comment by peyre** [comment]
That's not a bad idea.  In most cases the color of the name should tip a player off, but I could see it being missed occasionally, especially by new players.

**Comment by rnyoakum** [comment]
> In this case, the comment suggests astronauts / cosmonauts are tested for retirement every other season, but the code tests for retirement each season.

For the record, I changed this part in ca31328ad17f1fb153ccbb6b9c23a1548481dcdf, but forgot to mention the issue in the commit message. Just wanted to update the record.

**Comment by sflynn850** [comment]
@peyre / @rnyoakum Can we close this?

**Comment by peyre** [comment]
I'd be ok with closing it.  Ryan?

**Comment by rnyoakum** [comment]
Yeah - this is a trivial issue. It seemed weird so I wanted to check with Leon, and I don't think we had "discussions" available at the time. But it's not a bug, so let's go ahead and close it.
