### ISSUE TITLE
A:OK error on LEM Thrust Test does not award LM point

### ISSUE THREAD

**Issue by hweimer** [raceintospace/raceintospace#441]
Just had a LM test mission, during which the LEM Thrust Test had a minor error (I think it was "INSTRUMENTATION FAILURE, SIMPLE PROBLEM. REPAIRS MADE BY CREW, ALL SYSTEMS GO"). However, Mev[i].StepInfo got set to 50, which means there was no LM point being awarded because Set_LM in prest.cpp checks for a StepInfo == 1.

**Comment by peyre** [comment]
Good catch.  It's cruel to require LM tests and then not award the points when you've earned them.

**Comment by hweimer** [comment]
The step also doesn't count as a successful attempt in the L.M. program building.

**Comment by hweimer** [comment]
Here is the relevant Mev[i]:
`
{step = 15 '\017', loc = 26 '\032', StepInfo = 50, E = 0x55c2400e2e72, 
  Prest = -100 '\234', PComp = 0 '\000', pad = 0 '\000', Class = 2 '\002', 
  fgoto = 16 '\020', sgoto = 0 '\000', dgoto = 17 '\021', trace = 16 '\020', 
  dice = 94 '^', rnum = 1876, ast = 0 '\000', asf = 0 '\000', FName = "F026", 
  Name = "aUC6\000\000\000\000\000"}`

**Comment by hweimer** [comment]
Thanks to the data-decoder in src/utils I've been able to figure out that an Mev[i].rnum of 1876 translates to the error "MINOR PROBLEM WITH CABIN AIR CIRCULATION SYSTEM. CREW MAKES NECESSARY REPAIRS, ALL SYSTEMS GO." The associated .code is zero, like in the other "all systems go" cases. This leads FailEval() to set stepInfo to 50, which doesn't award any LM points as mentioned above.
In cases there is a failure that can't be repaired, then stepInfo is set to a higher value and PComp is set to 4. Testing for PComp != 4 is what should be tested for in Set_LM, as this also matches the tests for successful prestige awarding steps in AllotPrest().
