### ISSUE TITLE
Possible error in handling Code 21 mission failure

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#445]
There is a single code 21 error case, able to occur during lunar LEM activities:

per: 5100
code: 21
val: 50
xtra: 0
fail: 98
text: RETROROCKET FAILURE, COMPLEX PROBLEM. REPAIR UNSUCCESSFUL, PERMANENT LOSS OF SEVERAL MANEUVERING JETS.

The `FailEval` function doesn't explicitly handle this code; it gets dumped into the default failure along with the error codes that aren't implemented. This means it's treated as a minor problem and the mission continues.

```
    case 1:
    case 8:
    case 10:
    case 11:
    case 14:
    case 21:
    case 27:
    case 28:
    case 29:
    default:
        FNote = 0;
        Mev[STEP].StepInfo = 50;

        if (Mev[STEP].fgoto == -1) {
            Mev[STEP].trace = 0x7F;
        } else {
            Mev[STEP].trace = STEP + 1;
        }

        break;  // nothing : continue steps
```

What makes this notable is that there are two error codes (0 and 20) which are "minor problem, mission continues" effects and they are explicitly handled.

```
    case 0:   // Failure has no effect on Mission
    case 20:   // don't want to test for crew experience
        FNote = 0;
        Mev[STEP].StepInfo = 50;

        if (Mev[STEP].fgoto == -1) {
            Mev[STEP].trace = 0x7F;
        } else {
            Mev[STEP].trace = STEP + 1;
        }

        break;
```

The error should either be explicitly handled along with codes 0 and 20, or it should have an effect defined. Thoughts?

**Comment by hweimer** [comment]
I think this should be a branch to failure with a permanent loss in safety (code 26).

**Comment by hweimer** [comment]
Yup, that should definitely be a code 26 error. This is the equivalent of the F016 (i.e., LM instead of capsule) error "RETROROCKET FAILURE, COMPLEX PROBLEM. REPAIR UNSUCCESSFUL, PERMANENT LOSS OF MANEUVERING JETS. COMMAND SPACECRAFT MUST MAKE RENDEZVOUS.", which has exactly the same .percentage (although the safety penalty is slightly different, but that got removed in 2011 anyway).
