### ISSUE TITLE
DM in orbit alert

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#451]
There needs to an indicator to say whether there is a Docking Module in orbit or not. This is one of the most impenetrable aspects of the game, from the perspective as a player.

Per the game manual
> A docking module will remain active in space for a year, so it may be used in the season after its launch: to take advantage of this option, select a Manned Orbital Docking (Orbit) mission.

but this is only true if the Hardware Power-on test is successful. That fact isn't listed in the RIS manual (or the original game's) and without that knowledge the game is - in my experience - very confusing. Since unmanned docking missions report if they were successful or not, but don't (as I recall) display the failure case, the player is left guessing whether the DM is available or not.

At the least, there should be an explanation in the manual that a successful Hardware Power-on step is required. Leon's proposed [summary page](https://github.com/raceintospace/raceintospace/issues/352) could help with the issue, but requires the player to go out of their way to verify information that should be provided to them in the course of play.

**Comment by peyre** [comment]
This is a very good point.  Should definitely be mentioned in the manual - it's an example of something I took for granted so didn't think to mention.

**Comment by hweimer** [comment]
Isn't it two seasons rather than one year? If I put one up in June 1966, I think i won't be able to use it anymore in March 1967, although that's less than one year. If I remember correctly, the DM status gets updated in Update(), which gets called once at the end of the turn.

**Comment by rnyoakum** [comment]
@hweimer - you're correct about how it works, so possibly the language needs rewritten. The original BARIS manual specified two seasons

> Note: Mission Descriptions that include docking require that you place a docking module in orbit in the previous mission or season. Docking modules have a life span of two seasons in space.

**Comment by peyre** [comment]
I think the game means that it's good for the turn you launch it, plus the following turn.  That would mean it was active for (about) a year, though the way they worded it, it's not clear that you can't use it two turns after launch.

Hey, do you think it would be feasible to add a little docking module icon in Future Missions if there's one in orbit?  Something like this?
![DMinOrbit](https://user-images.githubusercontent.com/3118014/92999391-5507b000-f4d5-11ea-970b-e3eabfb45b27.png)

**Comment by peyre** [comment]
Another option could be to add a Help pop-up if you select an (Orbit) mission.

**Comment by rnyoakum** [comment]
> Hey, do you think it would be feasible to add a little docking module icon in Future Missions if there's one in orbit? Something like this, if there's a DM in orbit that you could use for a mission next turn?

You could, but since the DM is only good for the turn you launch it and the next turn, any DM shown in the Future Missions screen wouldn't be available by the time the mission is flown.

> Another option could be to add a Help pop-up if you select an (Orbit) mission.

Same issue - having a DM in orbit means nothing when planning Future missions.

**Comment by peyre** [comment]
If I'm not mistaken, Data->P[plr].DockingModuleInOrbit holds the variable for whether there's one currently in orbit and how long (1-2 turns) it will be there.  We could set it so that if you have mission 17, 24, 28, or 29 selected and you hit Continue, it checks that variable.  If it's 2, it doesn't pop up a warning.  

If it's 1, it could say:
NO DOCKING MODULE

THIS MISSION TYPE DOES NOT INCLUDE A
DOCKING MODULE. IT RELIES ON ONE
BEING IN ORBIT ALREADY.

THERE IS A DOCKING MODULE IN ORBIT
NOW, BUT IT WILL COME DOWN BEFORE
THIS MISSION CAN LAUNCH.

IF YOU WANT TO FLY THIS MISSION, YOU
MUST LAUNCH A REGULAR DOCKING TEST
BEFORE IT.

If it's 0, it could say:
NO DOCKING MODULE

I've added entries for this in a help file on my computer, but couldn't get future.cpp to handle it the way I wanted.
THIS MISSION TYPE DOES NOT INCLUDE A
DOCKING MODULE. IT RELIES ON ONE
BEING IN ORBIT ALREADY.

THERE IS NO DOCKING MODULE CURRENTLY
IN ORBIT.

IF YOU WANT TO FLY THIS MISSION, YOU
MUST LAUNCH A REGULAR DOCKING TEST
BEFORE IT.

**Comment by rnyoakum** [comment]
I don't see a point in having different messages depending on the status of the DM in orbit. After all, that DM won't be in orbit by the time the Future Mission is launched (the two season duration includes the season it's put into orbit). Consequently, any future mission will need to be accompanied by a mission conveying a DM into orbit. Now, modifying the message based on whether there is a current mission/future mission carrying a DM planned for launch before this mission is a different matter.

**Comment by peyre** [comment]
I thought it would help give new players a better feel for how that part of the system works: "Oh, it stays up for the turn I launch it and the one after."

**Comment by peyre** [comment]
Ok, this feature is implemented in Future Missions.  Feel free to change what I've done of course.

**Comment by rnyoakum** [comment]
I'm reopening this issue, because I don't feel the changes implemented address the original point - nothing alerts you if the docking module was successfully put into orbit, or explains what step (Hardware Power-on) is required for the docking module to be available.

**Comment by peyre** [comment]
Oh, ok!  Please be my guest.  When you've made changes to things I've done in the past, they've always been improvements over what I did.

**Comment by peyre** [comment]
Maybe something like this?

![(Orbit)](https://user-images.githubusercontent.com/3118014/100030036-70c9e500-2da7-11eb-9b77-de92a199e59a.png)

**Comment by peyre** [comment]
Hey Ryan, I've worked out how to make a DM appear if DockingModuleinOrbit==2 (ie, if you currently have one up that will be available for any mission you schedule this turn).  Do you want me to implement it, or hold off?

![FutureMissionsDM](https://user-images.githubusercontent.com/3118014/102701934-57cf1b00-4211-11eb-9e7d-37105f6ff9b5.png)

**Comment by peyre** [comment]
Hum, I can get the graphic to appear (and I've improved it over the above), but I can't get the conditional statement to work...

**Comment by rnyoakum** [comment]
> Hey Ryan, I've worked out how to make a DM appear if DockingModuleinOrbit==2 (ie, if you currently have one up that will be available for any mission you schedule this turn). Do you want me to implement it, or hold off?

I would hold off on implementing any new element until after the next release is made (bug fixes are another matter).

As for a DM image in the Future Missions screen:
* I would only show the DM image on missions that require docking.
* It would be nice to place the DM near where the Docking step bubble is displayed. However, that might vary by mission - I don't remember.
* Personally, I think the DM image is a bit large. I might need to pursue that on my own.

I'm also a little confused - `DockingModuleinOrbit == 2` should _never_ be true when you're in Future Missions. It gets set to 2 when the docking module is placed in orbit during a mission, but is immediately decremented during the start-of-turn updates. So it should only be 1 or 0 when in the Future Missions building.

> Hum, I can get the graphic to appear (and I've improved it over the above), but I can't get the conditional statement to work. I guess the page can't access Data-> info at the point where it draws the spacefield.

The code should absolutely be able to access Data, because Data is a global variable. If you want to send me a copy of the code, I'll review it.

**Comment by peyre** [comment]
Yes, I've made the DM much smaller, closer to the other screenshot higher up.

DockingModuleinOrbit does seem to equal 2 sometimes - Future Missions is currently able to distinguish between "there's no DM in orbit" and "there's one up, but it'll come down before this can launch".  I'll send you what I have now; have a look at it if you have a chance.

I'm excited about us getting a release out soon - the only reason I was working with this is that it seemed like something I could accomplish; it's not a high priority to my mind.

**Comment by peyre** [comment]
Wow.  Yes, you're right of course that DockingModuleinOrbit == 2 should never be true in Future Missions.  I had some trouble wrapping my head around it all, but sure enough - there's no way to know, in Future Missions, whether a DM will be waiting in orbit for an (Orbit) mission.  I'll have to remove this warning, d'oh!

**Comment by peyre** [comment]
I wonder, though, if a different sort of warning might be helpful for new players.  If you select an (Orbit) mission and his Continue, you could see something like this before selecting the capsule:

(ORBIT) MISSIONS DO NOT INCLUDE A 
DOCKING MODULE. THEY RELY ON ONE
BEING IN ORBIT ALREADY.

NO DOCKING MODULES CURRENTLY IN
ORBIT WILL STILL BE OPERATIONAL WHEN
THIS MISSION LAUNCHES. THAT MEANS
THAT IN ORDER TO FLY THIS, YOU WILL
HAVE TO DO ONE OF THE FOLLOWING:
1. LAUNCH A DOCKING TEST THIS TURN
2. SCHEDULE A DOCKING TEST FOR NEXT
    TURN TO LAUNCH BEFORE THIS
    MISSION.

**Comment by peyre** [comment]
Ok, I've added a warning very like this.  Maybe it helps?

**Comment by peyre** [comment]
Oh shoot, if you say Yes to that message, it will never come up again in a game.  That's fine for while you're in Future Missions, but once you hit Continue there, it should reset so next time you schedule a mission you'll be hit with the warning if you select an (Orbit) mission.

**Comment by peyre** [comment]
FWIW, I've found the help pop-up to be useful when playing.  Once or twice I've accidentally selected an (Orbit) mission when I didn't mean to, and the pop-up alerted me.  So this can potentially be helpful even to veteran players.

**Comment by sflynn850** [comment]
Can/should we close this? Do we need a PR for this, or is it already merged?

**Comment by peyre** [comment]
I would say that's up to Ryan.  I set the game to pop up a warning about the DM needing to be in orbit, any time you select an (Orbit) mission, but I don't know if he considers that to have taken care of this one, or if there's something else he wants done on it.

**Comment by rnyoakum** [comment]
Yeah, I'm going to close this. If you schedule a mission, there's no way to tell if there's going to be a docking module in orbit; the module has to go up either at the end of the turn when you schedule the mission or before the mission launches the next turn. The best thing to do - which I think Leon may have done - is to have a warning when a mission requires (but doesn't provide) a DM and clearly document which missions launch DMS.
