### ISSUE TITLE
InvalidatePrestige errors

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#453]
Uh oh!  I'm getting an error this morning trying to compile the game from the latest source: 

/home/leon/raceintospace/src/game/mis_m.cpp:921:13: error: ‘InvalidatePrestige’ was not declared in this scope
  921 |             InvalidatePrestige();
      |   &nbsp;  &nbsp;  &nbsp; &nbsp;^~~~~~~~~~~~~~~~~~
/home/leon/raceintospace/src/game/mis_m.cpp:925:13: error: ‘InvalidatePrestige’ was not declared in this scope
  925 |             InvalidatePrestige();
      |   &nbsp;  &nbsp;  &nbsp; &nbsp;^~~~~~~~~~~~~~~~~~
/home/leon/raceintospace/src/game/mis_m.cpp:1088:17: error: ‘InvalidatePrestige’ was not declared in this scope
 1088 |                 InvalidatePrestige();
      |   &nbsp;  &nbsp;  &nbsp; &nbsp; &nbsp;^~~~~~~~~~~~~~~~~~
/home/leon/raceintospace/src/game/mis_m.cpp:1092:17: error: ‘InvalidatePrestige’ was not declared in this scope
 1092 |                 InvalidatePrestige();
      |    &nbsp;  &nbsp;  &nbsp; &nbsp; &nbsp;^~~~~~~~~~~~~~~~~~
/home/leon/raceintospace/src/game/mis_m.cpp:1161:13: error: ‘InvalidatePrestige’ was not declared in this scope
 1161 |             InvalidatePrestige();
      |    &nbsp;  &nbsp;  &nbsp; &nbsp; &nbsp;^~~~~~~~~~~~~~~~~~
/home/leon/raceintospace/src/game/mis_m.cpp:1164:13: error: ‘InvalidatePrestige’ was not declared in this scope
 1164 |             InvalidatePrestige();
      |    &nbsp;  &nbsp;  &nbsp; &nbsp; &nbsp;^~~~~~~~~~~~~~~~~~
/home/leon/raceintospace/src/game/mis_m.cpp:1201:13: error: ‘InvalidatePrestige’ was not declared in this scope
 1201 |             InvalidatePrestige();
      |   &nbsp;  &nbsp;  &nbsp; &nbsp; &nbsp;^~~~~~~~~~~~~~~~~~
/home/leon/raceintospace/src/game/mis_m.cpp:1205:13: error: ‘InvalidatePrestige’ was not declared in this scope
 1205 |             InvalidatePrestige();
      |   &nbsp;  &nbsp;  &nbsp; &nbsp; &nbsp;^~~~~~~~~~~~~~~~~~
/home/leon/raceintospace/src/game/mis_m.cpp:1326:17: error: ‘InvalidatePrestige’ was not declared in this scope
 1326 |                 InvalidatePrestige();
      |   &nbsp;  &nbsp;  &nbsp; &nbsp; &nbsp;^~~~~~~~~~~~~~~~~~
/home/leon/raceintospace/src/game/mis_m.cpp:1330:17: error: ‘InvalidatePrestige’ was not declared in this scope
 1330 |                 InvalidatePrestige();
      |   &nbsp;  &nbsp;  &nbsp; &nbsp; &nbsp;^~~~~~~~~~~~~~~~~~
make[2]: *** [src/game/CMakeFiles/game_test.dir/build.make:635: src/game/CMakeFiles/game_test.dir/mis_m.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:366: src/game/CMakeFiles/game_test.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

**Comment by rnyoakum** [comment]
Should be fixed now.

**Comment by peyre** [comment]
Thanks Ryan!  That did it.
