### ISSUE TITLE
Not given credit for Duration step

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#457]
Funny, I had a Vostok mission that did the Duration step successfully, but then the cosmonaut was killed later in the flight.  The Mission Summary says it did Duration B, but then the Satellite Building shows I'm at Duration A, so I didn't get credit for Duration B.

![Failed Duration B](https://user-images.githubusercontent.com/3118014/93021327-df641880-f596-11ea-9653-2cd4afff030d.png)
![Didn't get Dur B](https://user-images.githubusercontent.com/3118014/93021331-e68b2680-f596-11ea-8790-db1bfc3a51c8.png)

Incidentally, the Duration C flight I had scheduled for the following turn shows no requirement penalties, yet if I break it out it shows a duration penalty.

![Dur C](https://user-images.githubusercontent.com/3118014/93021336-ea1ead80-f596-11ea-859d-0542004ee9e3.png)
![Dur Penalty!](https://user-images.githubusercontent.com/3118014/93021440-60231480-f597-11ea-9858-eda08fdb95e3.png)

**Comment by peyre** [comment]
Also (again, a separate issue but I'm mentioning it here because it all happened in the same place), if I downgrade the mission from Duration C to B, the duration penalty still shows in the penalty pop-up. :(

**Comment by rnyoakum** [comment]
> I had a Vostok mission that did the Duration step successfully, but then the cosmonaut was killed later in the flight. The Mission Summary says it did Duration B, but then the Satellite Building shows I'm at Duration A, so I didn't get credit for Duration B.

That's... not a bug. From the discussion in #374, you don't get credit for achievements when the crew is injured/killed. And, well, I wouldn't support giving credit for anything done when the entire crew is killed. Nope, that's a straight up failure.

If you think the mission should display the duration as (A) or No Credit, or in red, or something like that when no duration credit is given, that's possible, but I believe it's more accurate to present the mission duration that occurred in the mission summary.

As for the Mission Control requirement penalties/ popup: yeah, that's a bug in how Mission Control is calculating duration penalties on duration missions. I'll have to fix it.

**Comment by peyre** [comment]
Oh, ok.  I think might be helpful to indicate somehow that the duration step doesn't count, which would prevent such misunderstandings.  I'm not sure how it would be best to do that though, and it's really optional.  As long as this is intended behavior, we're good.

Any idea, though, about the requirement penalties?

**Comment by rnyoakum** [comment]
Yes. The penalty popup is displaying the original penalties because the popup function is being passed the original mission information, rather than the downgraded mission data. The Requirement Penalties error is because the function that calculates mission penalties isn't being passed data by Mission Control updated to reflect optional Duration levels. These are easy to fix, and I've already written the fix.

**Comment by peyre** [comment]
Woohoo!  Good to get that fixed before release.
