### ISSUE TITLE
Message when recruiting too few astronauts

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#462]
When the player is recruiting astronauts but has not filled all the available slots, they are not allowed to leave recruitment. However, there is no error message if they try to continue. There should be a Help entry that explains that all recruit slots must be filled. Disabling the "Continue" button is another idea to consider, but I think a Help entry is a superior option.

**Comment by peyre** [comment]
That's a good idea.  I should be able to add an entry for it in the help file; there are a few other changes I've been planning to make in it.

**Comment by peyre** [comment]
Ok Ryan, I've added one for this, I045.  We can of course change the wording etc., but this will let you link to it anyway.

**Comment by peyre** [comment]
While I have some time to spare, I've gone ahead and implemented this.
