### ISSUE TITLE
Game crashes when assigning a crew

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#464]
When I assign crew(s) to a mission, it sometimes (but not always) crashes with the following error:

> raceintospace: /home/leon/raceintospace/src/game/place.cpp:499: int Help(const char*): Assertion `NTxt != NULL' failed.
Aborted (core dumped)

That line of place.cpp seems to reference the help file, but I didn't press F1:

> assert(NTxt != NULL);

**Comment by rnyoakum** [comment]
When you added Help entry I045 in commit d7c0e943ef1344d9cf6e58adc9f0db6785cef780, you accidentally removed entry I099.

**Comment by peyre** [comment]
I did!?  Argh!

**Comment by rnyoakum** [comment]
Yeah, but I fixed it :)

**Comment by peyre** [comment]
Thanks for having my back.
