### ISSUE TITLE
ABOUT button in R&D and Purchasing

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#467]
The manual has a section that describes each piece of hardware in the game.  I wonder if it would be a good idea to also have an ABOUT button in R&D and Purchasing that brings up a Help pop-up giving that information.  What do people think?  Something like this maybe (though putting it at the top would mean moving the AVOID FAIL icon, but that's easy enough to do.

![About](https://user-images.githubusercontent.com/3118014/93913911-97da3c80-fcba-11ea-84e5-180c391394c1.png)

**Comment by rnyoakum** [comment]
I like the idea of providing in-game information. I think an "About" button where you illustrate would be awkward - it doesn't fit the GUI's template. Perhaps clicking the equipment's image could launch the popup?

**Comment by peyre** [comment]
I've written the help file entries for the individual hardware items.  This weekend I'll have to see about adding them here somewhere.

On a related note, I wonder if it would be a good idea to indicate, for rockets, their max payload when boosted.

**Comment by rnyoakum** [comment]
> I've written the help file entries for the individual hardware items. This weekend I'll have to see about adding them here somewhere.

What format are you using to store the data?

**Comment by peyre** [comment]
I've written them as I201 and up, so the I200 series would be for hardware.

**Comment by peyre** [comment]
I'm torn.  Part of my thinking is that a new player wouldn't know that was a button, but _adding_ a button might crowd the display too much.  This might be a better option for a standalone button.  Thoughts?

![AboutButton](https://user-images.githubusercontent.com/3118014/94999778-832a5e00-0570-11eb-89b8-e29a34418933.png)

**Comment by peyre** [comment]
Ok, I ran this past my daughter and she agrees with you Ryan, stuffing in an extra button looks weird.  I'll work on this tomorrow morning.

**Comment by peyre** [comment]
Ok, this is implemented!  Also I changed docking modules so instead of showing R&D COST PER TEAM:  0, it shows -- instead.
