### ISSUE TITLE
Indicate Requirement Penalties before continuing mission

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#473]
In the screen where you give a final go-ahead or scrub to a mission, perhaps it could indicate if the mission faces requirement penalties.  Maybe below SINGLE LAUNCH or something like that.  It would need to be updated, of course, if a launch just completed satisfied a requirement penalty (such as if you flew a Lunar Pass on Pad A followed by a Lunar Orbital on Pad B).

![Historical LL](https://user-images.githubusercontent.com/3118014/94346506-e7ce4180-ffe1-11ea-87d3-049e67aa7312.png)

**Comment by peyre** [comment]
It could have a button or something, like this maybe?

![PEN button withNum](https://user-images.githubusercontent.com/3118014/102020955-58f3da00-3d31-11eb-9999-1f537d8ff3c7.png)

**Comment by rnyoakum** [comment]
It's a different approach, but maybe the penalties (equipment damage, mission penalty, etc.) should be incorporated into the component safety values displayed? That would avoid the need to find more GUI space that doesn't really exist.

**Comment by peyre** [comment]
Oh, that's an idea.  Each of those percentages could be followed by a box with a penalty number or the penalty number in parentheses or something...though, now you mention GUI space, we'd have to move that column to the left.  A Joint mission would also have a column on the right.

**Comment by peyre** [comment]
Another good idea might be to indicate there if any component holds an Avoid Fail card.  Not sure if that's practical though, given how full the screen is already.

**Comment by peyre** [comment]
Maybe something simple like a plus sign next to anything that has an Avoid Fail:

![PlusSign](https://github.com/raceintospace/raceintospace/assets/3118014/bfac2a50-9105-43b8-9144-aa315dd61b54)

**Comment by peyre** [comment]
There, got it done.

![Plus Sign](https://github.com/raceintospace/raceintospace/assets/3118014/c4e42c19-7003-4e3f-8e35-50c9fb2c6693)
