### ISSUE TITLE
Photo Recon check using wrong safety

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#482]
I had 90% photo recon before launching my lunar landing, but on the mission itself it rolled against a much lower figure.

![Photo Recon bad](https://user-images.githubusercontent.com/3118014/95689008-e34d7f80-0bc2-11eb-8694-c58fabec4005.png)

_Originally posted by @peyre in https://github.com/raceintospace/raceintospace/issues/427#issuecomment-706761058_

**Comment by peyre** [comment]
I wondered if this would be better done as a separate issue. Let me know if you want to analyze the savegame.

**Comment by peyre** [comment]
Incidentally, that was my second attempt at the landing.  The first time it was scrubbed because the photo recon step failed.

**Comment by rnyoakum** [comment]
> Let me know if you want to analyze the savegame.

Sure, send it my way if you have it. It might not help, but it won't hurt.

**Comment by peyre** [comment]
It should be here in my autosave.

    On Sunday, October 11, 2020, 2:06:32 PM PDT, Ryan Yoakum <notifications@github.com> wrote:  
 
 



Let me know if you want to analyze the savegame.


Sure, send it my way if you have it. It might not help, but it won't hurt.

**Comment by rnyoakum** [comment]
Okay, this is an easy fix - `MH[j][Mission_PhotoRecon]->MisSaf` isn't getting set in `MissionSetup()` anymore. I'll push a commit in the morning.
