### ISSUE TITLE
Better place to show Duration Level

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#487]
BARIS never had a place that showed what duration level you'd reached.  Years ago I kind of shoved it into the Satellite Building, but I've always wanted to find a better place for it.  Here is the Satellite Building in BARIS vs. RIS; as you can see, I squeezed things down for the docking module to make room for duration level, but it doesn't really belong there.
![BARISSatelliteBuilding](https://user-images.githubusercontent.com/3118014/96374775-a8e76380-1129-11eb-8704-cc0c0a1aeddb.png)
![RISSatelliteBuilding](https://user-images.githubusercontent.com/3118014/96374776-a97ffa00-1129-11eb-9ebc-c92e67669169.png)

Trouble is I haven't been able to come up with a better place to put it.  It should be easily accessible from the spaceport screen, but where?  I wonder if it could go in the Capsule Screen.  Thoughts anyone?
![New place for duration level](https://user-images.githubusercontent.com/3118014/96374933-a6393e00-112a-11eb-80c9-66064a4f34d8.png)

**Comment by rnyoakum** [comment]
I don't know of a great place to put it in the capsule screen. I like your idea of a [summary page](https://github.com/raceintospace/raceintospace/issues/352), which shouldn't be hard to make, but I was going to put that off until after the next release. It seems a bad idea to try and rush in a new feature (as opposed to a bug fix) without time to test it out.

**Comment by peyre** [comment]
Thanks.  I agree the summary page is a lower priority.  I was just thinking of a small change I could make - pushing the data into another screen should be very simple.  But I'm happy to hold tight on this one; I thought up there below the Continue button would fit well and it would make more sense to show it in the Capsule screen than the Satellite one.  But if we're planning to move it to the summary page in the next release, that's even better.
