### ISSUE TITLE
Indicator that women must be recruited?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#490]
I realize this is almost a trivial suggestion, but do you think it would be a good idea to include some indication in recruitment when women must be recruited?  Like a female symbol or something?

![Indicator that women must be recruited](https://user-images.githubusercontent.com/3118014/97085676-cb6af800-15d3-11eb-81da-3679d993260a.png)

**Comment by rnyoakum** [comment]
I don't think this is needed. Most of the time, I think the player will remember. After all, by default female candidates don't show up unless you get the event requiring them. If you're using the custom settings that allow female candidates without the news event, you probably want to recruit some anyways.

Regardless, If the player doesn't remember the candidate requirement, they'll be explicitly reminded when they try to continue. It's not hard to replace one candidate.

**Comment by peyre** [comment]
I think you're right.  Just thought I'd float the idea.
