### ISSUE TITLE
error: static assertion failed: sizeof(Players) == 38866

### ISSUE THREAD

**Issue by pemensik** [raceintospace/raceintospace#494]
When building on 32bit platform, the build fails with:

```
[ 28%] Building CXX object src/game/CMakeFiles/game_test.dir/music_none.cpp.o
In file included from /home/pihhan/git/raceintospace/src/game/data.h:845,
                 from /home/pihhan/git/raceintospace/src/game/Buzz_inc.h:69,
                 from /home/pihhan/git/raceintospace/src/game/music_none.cpp:26:
/home/pihhan/git/raceintospace/src/game/data.h:852:37: error: static assertion failed: sizeof(Players) == 38866
  852 | BOOST_STATIC_ASSERT(sizeof(Players) == 38866);
      |                     ~~~~~~~~~~~~~~~~^~~~~~~~
```

I think ``struct MisEval, Equipment *e;`` pointer is responsible. If this structure is saved into save file, it would make 32 bit build incompatible with 64bit build. I think this is blocker for 2.0.0 release, because it cannot compile on i686 platform.

**Comment by pemensik** [comment]
Compiled it with ``CC=/usr/bin/gcc CXX=/usr/bin/g++ CFLAGS="-m32 -g -O2" CXXFLAGS="-m32 -g -O2" cmake  ..``, and installed ``dnf install SDL-devel.i686 gcc-c++.i686 glibc-devel.i686 libstdc++-devel.i686``.

**Comment by pemensik** [comment]
On X86_64, it is ``sizeof(MisEval) == 40)``. But on i386, ``sizeof(MisEval) == 36)``. That makes total ``sizeof(Players) == 38146`` on 32 bit platform.

**Comment by pemensik** [comment]
Oh, those static asserts were inserted too long ago by Will Glynn, commit c65f5d5eb0644bd84b0f17d2452fac96def2569f. It must have been broken for ages.

**Comment by peyre** [comment]
Good finding, Petr.  I hope you're able to fix it so the game can be built on 32-bit systems.

**Comment by rnyoakum** [comment]
> Oh, those static asserts were inserted too long ago by Will Glynn, commit c65f5d5. It must have been broken for ages.

The static asserts haven't been broken for very long (only since August 22). Prior to commit b2067d4f1660e9985a6de9443672f02f35913104, `MisEval` objects were only used locally in the mission evaluation code; @hweimer added them to `struct Players` to get Play-By-EMail working in that commit. Consequently, he changed
```
BOOST_STATIC_ASSERT(sizeof(Players) == 31663);
```
to
```
BOOST_STATIC_ASSERT(sizeof(Players) == 38866);
```

**Comment by pemensik** [comment]
Great, I just wondered how my previous build on Fedora passed. That explains it. I have seen the size was changed, but I kind of missed addition to Players.

I have prepared a fix, which would eventually move E pointer from ``struct MisEval``. I changed it to union, making the size constant.

**Comment by hweimer** [comment]
Ouch! Sorry to have missed that one. For PBEM games, it actually won't matter what's stored inside the E pointer. But of course it's crucial that the data structures have the same size both on 32-bit and 64-bit platforms.

**Comment by pemensik** [comment]
I have merged the fix, it should be fixed now. Builds passed on all platforms on [Fedora builder](https://koji.fedoraproject.org/koji/taskinfo?taskID=55590816). The E pointer might be removed, because I made wrapper functions to provide the pointer from internal structures instead.
