### ISSUE TITLE
Lunar landing failure skips a step

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#505]
On a Historical Manned Lunar Landing, I brought my LKM down to the Moon and got a red line:

MANEUVERING FAILURE, CRAFT LANDS IN ROUGH TERRAIN CAUSING DAMAGE.

The lander actually set down, but the next step after the landing was Lunar Orbital Activities.  The LM never had to lift off!  Must be a fault in the failure codes for that mission.

![After a rough landing](https://user-images.githubusercontent.com/3118014/104854977-bd6d0080-58be-11eb-96e3-5283ed8afce1.png)

**Comment by peyre** [comment]
Having a closer look at mission 53, it looks like failure on step J had it skip K, L, and M and go straight to N, Lunar Orbital Activities.

If I'm reading Ryan's summary.txt (a decoded copy of mission.dat) right, the 10th number under .Alt for mission 53 should be 12 rather than 13.  Not sure how to go about fixing that though.

**Comment by hweimer** [comment]
You can change the values in mission.dat with a hex editor. Just search for the string "HISTORICAL L.L." and look for the sequence 0e 0e 0d 0c, which you need to change to 0e 0e 0c 0c.

**Comment by peyre** [comment]
Hey thanks!  I've changed it...now the hard part, testing the change.

**Comment by hweimer** [comment]
Once the mission is running (i.e. starting with the countdown), you can use a debugger to modify the Mev[i].dice fields such that you are only seeing a failure at the desired step. You might have to change Mev[9].rnum as well, to make sure that you hit a branch to alternate event.

**Comment by peyre** [comment]
Oh, that would work better than relying on chance and repetition, wouldn't it?  Not sure how to get it to trigger one specific step though.

**Comment by hweimer** [comment]
You can set all the Mev[i].dice to zero for all steps from 0 to 8 and set Mev[9].dice to 100 to guarantee a failure on the landing step. In gdb, you can do that by "print Mev[0].dice = 0", for example. gdb also supports looping if cut and paste becomes too cumbersome. For the landing step, you can reproduce the failure by setting Mev[9].rnum to 9000.

**Comment by peyre** [comment]
Thanks!  Unfortunately you're still ahead of me.  What's the debugger and how do I open it?  (I'm not trying to be dense - I really don't know this stuff.)

**Comment by hweimer** [comment]
If you have gdb installed, you can run the game in the debugger by running "gdb src/game/raceintospace" in the build directory and then "run BARIS_DATA=YOUR_SOURCE_DIR/data" inside gdb, replacing YOUR_SOURCE_DIR with the source directory.   Pressing Ctrl-C when the countdown starts will take you back to the gdb prompt, where you can do the modifications I described in https://github.com/raceintospace/raceintospace/issues/505#issuecomment-822773720. Once you are done, you can go back to the game with the "cont" statement.

If gdb complains about a missing symbol table, you have to call cmake with the argument -DCMAKE_BUILD_TYPE=Debug before compiling the game.

**Comment by peyre** [comment]
Wow, I never would have figured that out!  Thanks, I'll try it tonight.

**Comment by peyre** [comment]
Hum!  I started the mission, then entered print Mev[9].dice = 900 in gdb, but the step never failed.  The mission was a complete success.

**Comment by hweimer** [comment]
.dice is a char, setting it to 900 will wrap around to -124, which is always lower than the safety factor.

**Comment by peyre** [comment]
Ok, but setting it to 900 while on the step just before it didn't seem to do anything.  I must be missing something here.

**Comment by hweimer** [comment]
You should set Mev[9].dice to 100 and not to 900. The dice field is a signed char, which means that it can hold values between -128 and +127. Setting it to any larger value will typically wrap the value around (similar to modular arithmetic) until it ends up between the valid values. Converting 900 to a signed char will then result in an actual value of -124, which you can see in the value returned by the print statement. The game checks for a step failure by computing whether the value stored in .dice is larger than the current safety factor. Obviously, a negative number cannot be larger than the positive safety factor, so you will never see a failure in this case. Setting .dice to 100 instead will ensure that it's always larger than the safety factor and trigger a failure event.

**Comment by peyre** [comment]
Ok, but running print Mev[9].dice = 100 doesn't cause the step to fail.

**Comment by hweimer** [comment]
When did you run that command? It has to be between the countdown and the end of step 8. If you did that, can you run "print Mev[9]" at the end of the mission and paste the output of the entire gdb session?

**Comment by peyre** [comment]
As you can see below, I ran the command during the previous step.  Entering "print Mev[9]" after the game closed throws an error, so I think I did this right.  (Actually I think I didn't, but can't see where I went wrong.)

![1 Photo Recon](https://user-images.githubusercontent.com/3118014/115586670-b10f8f80-a281-11eb-86b6-1ced2b05c0e5.png)
![2 Lunar Landing](https://user-images.githubusercontent.com/3118014/115586672-b1a82600-a281-11eb-93f9-a47168bd0e6c.png)
![3 Endgame](https://user-images.githubusercontent.com/3118014/115586673-b240bc80-a281-11eb-9367-49d1f76c1b8c.png)

**Comment by hweimer** [comment]
Ah, I see! You need to press Ctrl-C first (in the gdb window) to get a gdb prompt. This is an input line starting with "(gdb)", where you can enter your commands. Once you are done, you need to enter "cont" to continue with the game. Here's how it should look like:
```
^C
Thread 1 "raceintospace" received signal SIGINT, Interrupt.
0x00007ffff7b6080e in ?? () from /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
(gdb) print Mev[9].dice = 100
$1 = 100 'd'
(gdb) cont
Continuing.
```

**Comment by peyre** [comment]
Huh!  It's still not working right for me.

![Photo Recon](https://user-images.githubusercontent.com/3118014/115621022-cf3db580-a2aa-11eb-8274-12c2de78db9a.png)
![Lun Landing](https://user-images.githubusercontent.com/3118014/115621040-d5339680-a2aa-11eb-9d27-edce9f042d3c.png)

**Comment by hweimer** [comment]
This looks like gdb is missing some debugging symbols. Did you call cmake with -DCMAKE_BUILD_TYPE=Debug before compiling the game?

**Comment by peyre** [comment]
Ahh, that might be the issue.  The command I run to compile the game is below.  So what do I need to do exactly?

`cd ~/ && sudo rm -rf ~/raceintospace-build && mkdir raceintospace-build && cd raceintospace-build && cmake ../raceintospace && make && sudo make install && cd src/game && ./raceintospace`

**Comment by hweimer** [comment]
You  need to replace "cmake ../raceintospace" by "cmake -DCMAKE_BUILD_TYPE=Debug ../raceintospace/".

**Comment by peyre** [comment]
Hey, that did it!  I wondered if I should just tack that switch onto cmake, but I thought Nah, that's too simplistic.  So yes, that lets me force a failed roll on that step each time, brilliant.  Now I just have to keep running it until it rolls the type of failure I want.  Thanks for bearing with me!

**Comment by peyre** [comment]
Yes, it now goes to lunar liftoff instead of straight to orbital activities.  Thanks for your help!

**Comment by peyre** [comment]
Ok, I've found something else I want to test and I'm trying to make a given step fail again.  Unfortunately I didn't write down last time how I did it and...I'm missing a step, because Ctrl-c just moves the mission to the next step.  I seem to be missing the bit about how to get into  the gdb window.  Can you tell me what I'm missing?  I have "cmake -DCMAKE_BUILD_TYPE=Debug ../raceintospace/" in my compile statement.

    On Wednesday, April 21, 2021, 3:21:14 PM PDT, Hendrik W. ***@***.***> wrote:  
 
 


You need to replace "cmake ../raceintospace" by "cmake -DCMAKE_BUILD_TYPE=Debug ../raceintospace/".

**Comment by hweimer** [comment]
You have to run the game via "make gdb" and press Ctrl-C not inside the game but in the terminal from which the game was launched. Then you should see a gdb prompt indicated by "(gdb)", where you can enter your debugging commands.

**Comment by peyre** [comment]
No, scratch that.  I got as far as starting gdb in a terminal window.  But then I can't run the game.  _I'm missing something simple_, I know.  These are the instructions I have so far.

`First you have to have gdb installed.

Open mission.dat with a hex editor and find the step you're looking for in the sequence, which will look like something like "0e 0e 0d 0c".
  Make a note of the step number.

Compile the game but replace "cmake ../raceintospace" with "cmake -DCMAKE_BUILD_TYPE=Debug ../raceintospace/".

Open a gdb prompt by executing gdb raceintospace (from raceintospace-build/src/game) or gdb ~/raceintospace-build/src/game/raceintospace (from anywhere)

Run the mission, and while it's running, go to the terminal window and hit Ctrl-C to drop into the gdb prompt.

Execute: print Mev[x].dice = y    where x is the step number from above and y is the roll you want it to have, so e.g.:
         print Mev[9].dice = 100  to make sure that step 9 fails for sure.

Then execute cont to continue`
