### ISSUE TITLE
No Crews Warning

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#509]
Many times, early in the game, I go to assign crews to a mission, and get the "no crews available" warning.  It's not a huge deal, but I wonder if we could change this one to offer to take you directly to the Astronaut Complex to assign crews.  A No would of course leave you in Future Missions.

![NoNauts](https://user-images.githubusercontent.com/3118014/105614486-93b04f80-5d7e-11eb-8358-8645bb1b4357.png)

**Comment by peyre** [comment]
Making this change in help.cdr 

;=I099
; Longest Line:                     ;
;xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
%11:1
.011
CREW ASSIGNMENT PROBLEM
.001
THERE ARE NO CREWS AVAILABLE IN THIS
PROGRAM TO ASSIGN TO THE MISSION.

.009
THE SOLUTION IS TO TRANSFER MORE
PEOPLE INTO THIS PROGRAM, SELECT
ANOTHER PROGRAM, OR MOVE PEOPLE
OUT OF ADVANCED TRAINING AND INTO
THIS PROGRAM.

.005
WOULD YOU LIKE TO EXIT OUT OF HERE TO
ASSIGN PEOPLE TO THE PROGRAM?

would do this:
![NoNautsYesNo](https://user-images.githubusercontent.com/3118014/105614791-86946000-5d80-11eb-863f-16659902d9f2.png)

**Comment by peyre** [comment]
As it is now, after you hit Continue, it takes you on to the crew selection window (below) and you have to cancel out of here.  Maybe hitting Continue now (or saying No if it's made a yes/no) should bring you back to Future Missions for the pad, so you can select another mission if you want without having to take the extra step of canceling the crew selection.  I've tried adding "return 1;" to crew.cpp to do that, but it takes you to the initial screen for Future Missions, where you select the pad to schedule on.

![FutureMissionsNoCrews](https://user-images.githubusercontent.com/3118014/105641339-3e387900-5e38-11eb-8193-808777bcd0b0.png)

**Comment by rnyoakum** [comment]
> As it is now, after you hit Continue, it takes you on to the crew selection window (below) and you have to cancel out of here. Maybe hitting Continue now (or saying No if it's made a yes/no) should bring you back to Future Missions for the pad, so you can select another mission if you want without having to take the extra step of canceling the crew selection. I've tried adding "return 1;" to crew.cpp to do that, but it takes you to the initial screen for Future Missions, where you select the pad to schedule on.

Huh, you're right. If there isn't an available crew, it should automatically cancel. Particularly since the act of alerting the player with a text message means the game **knows** there's no point in displaying the selection menu. I'll try to uncover why it's not handling this automatically.

**Comment by rnyoakum** [comment]
That the game wasn't automatically cancelling out of the crew selection menu when no crews were available was a one-line fix. I handled it in #649.
