### ISSUE TITLE
Move hardcoded bitmaps into images

### ISSUE THREAD

**Issue by willglynn** [raceintospace/raceintospace#51]
`DispChr()` draws a bitmap font using a bunch of macros in a `switch` statement. `Flag()` and `FlagSm()` draw flags by setting individual pixels. We should dump these things to PNGs instead of embedding the images in code.

**Comment by peyre** [comment]
As one small part of that, I've been able to prettify the country insignias in the game.  When you start your turn, your country's insignia always looked kind of squashed:


![Insignia](https://user-images.githubusercontent.com/3118014/73568376-22fd7e00-441d-11ea-8037-e00201166bcc.png)

**Comment by peyre** [comment]
In #605, Ryan pointed out something I should've noticed, that using auto-resize fuzzes up the image - especially the stars in the center.  Should be better now.

**Comment by sflynn850** [comment]
Closing, as the issue seems to have been (further) resolved by #605
