### ISSUE TITLE
Black spots in some hardware images

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#513]
Pretty sure the Kicker-B isn't supposed to look like that, with all those black spots on its backside.  I wonder if this is an issue with the color palette, or with transparency in the image.

![Kicker-B](https://user-images.githubusercontent.com/3118014/106395335-9c280c00-63b6-11eb-8129-23a87b2247ec.png)

**Comment by peyre** [comment]
Looks like Lapot has the same issue.

![Lapot](https://user-images.githubusercontent.com/3118014/108644927-d2145980-7465-11eb-8eeb-baa7de428f16.png)

**Comment by peyre** [comment]
And there's just a little bit of it with the Soyuz.

![Soyuz](https://user-images.githubusercontent.com/3118014/108758420-ec9b1100-74ff-11eb-8c3d-8e23b5286ce0.png)

**Comment by peyre** [comment]
Might be a slight change to the palette would fix this - don't know.

**Comment by rnyoakum** [comment]
Yep, this is a palette issue. Back in commit a072664fa786dfe9e2ea2be0fd5d41de55031618 R&D images converted from rdfull.but to PNGs. However, due to an oversight their palettes aren't being exported to the main display. It's an easy fix and I'm testing it now.

**Comment by peyre** [comment]
Thanks Ryan!  It's a little esthetic thing, but good to have done.
