### ISSUE TITLE
Game asks for first on Moon when no one will be getting out

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#514]
Found another small anomaly in failure handling.  On a Historical LL, I got a mission scrub and it did scrub the mission, but first it asked me who should be the first on the Moon.  Then they blasted off without leaving the LM.

![Mission Scrubbed 1](https://user-images.githubusercontent.com/3118014/106395415-06d94780-63b7-11eb-8e72-93543fe97c34.png)
![Mission Scrubbed 2](https://user-images.githubusercontent.com/3118014/106395416-0771de00-63b7-11eb-907c-4e8fc57509cf.png)
![Mission Scrubbed 3](https://user-images.githubusercontent.com/3118014/106395417-080a7480-63b7-11eb-908a-a94444b798b9.png)

**Comment by hweimer** [comment]
This one got closed by #534.
