### ISSUE TITLE
Tech transfer for kickers?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#519]
I realize that a player will almost never develop both a Kicker-A and B - you pick one and stick to it depending whether you want to fly LOR or EOR.  However, logically it might make sense for A to give technology transfer to B and vice versa.  Thoughts, anyone?

**Comment by smudog** [comment]
First post - long term fan.

My take would be Kicker-A represents Agena-D (hypergolic) and Kicker-B represents Centaur (cryogenic), at least for the US program, so not much transfer between them.

**Comment by peyre** [comment]
Wow, good point!  I don't know about that one way or another, but it sounds like that's probably the case.  Might be different for the Soviets, but given it's kind of obscure anyway, we might be best off leaving this as is.
