### ISSUE TITLE
Problems in Advanced Preferences

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#520]
I started going through Adv. Preferences today, thinking maybe I'd have all the values set to default from the get-go, rather than the player having to uncomment the lines and refer to the instructions at the top to not use equal signs with them.  So, changing it from 
`# show_recruit_stats`
to
`show_recruit_stats 1`

However, I found several issues.

1. Uncommenting either `show_recruit_stats` or `use_endurance` (or both) prevents the game opening at all.  If I'm compiling from source, it returns "Segmentation fault (core dumped)".  Incidentally, setting `game_style 1` (Classic settings) does hide candidate skills as if you had set `show_recruit_stats`.  Does this have anything to do with the fact that they're the only options that default to 1 instead of 0?
2. ~~There's a typo: `altasLunar`, instead of `atlasLunar`.  This would be easy enough to correct, except we might have to accommodate existing config files that still have the typo.  (I've verified that altasLunar works and atlasLunar doesn't.)~~ _Fixed! Users who want to use this option should correct the spelling in their config file, or simply delete it and reopen the game_.
3. `random_eq` ("random equipment model") doesn't seem to randomize equipment.  I'm uncertain about this one; if we don't want it to work I'm completely ok with that, but maybe we should make a note of it in the config file or even remove it.
4. `eq_name_change` ("change equipment name when starting a new game") doesn't seem to work.  I'm never given an option to change names, that I can see.  Maybe the option is for something like allowing a user to edit a text file to change the names, and this option tells the game to read that file instead of the usual one?
5. ~~`fullscreen` also doesn't work, as mentioned in #359.  (This seems to be fixed by a recent pull request.)~~
6. `succesRDMax` doesn't seem to work either.  I got a Voskhod to smash to Earth, and it did degrade the capsule's Safety.  Like random_eq, I'm ok with this not working if we want it not to, but we should probably say something about it in the config file if so.

**Comment by rnyoakum** [comment]
> 1. One is that uncommenting either `show_recruit_stats` or `use_endurance `(or both) prevents the game opening at all. If I'm compiling from source, it returns "Segmentation fault (core dumped)". Incidentally, setting `game_style 1` (Classic settings) does hide candidate skills as if you had set `show_recruit_stats`. Does this have anything to do with the fact that they're the only options that default to 1 instead of 0?

I'll take a look at this. As for your other points...

> 3.  `random_eq` ("random equipment model") doesn't seem to randomize equipment. I'm uncertain about this one; if we don't want it to work I'm completely ok with that, but maybe we should make a note of it in the config file.

This was never implemented, and I've seen no documentation on how it was to be designed. I'd probably remove the option entirely for now.

> 4. `eq_name_change` ("change equipment name when starting a new game") doesn't seem to work. I'm never given an option to change names, that I can see. Maybe the option is for something like allowing a user to edit a text file to change the names, and this option tells the game to read that file instead of the usual one?

This was never implemented either, and is never referenced outside of options.cpp. It also seems like it would be a hassle for a minor change - a new GUI would be needed, and any text in the Help files wouldn't be updated.

> 6. `succesRDMax` doesn't seem to work either. I got a Voskhod to smash to Earth, and it did degrade the capsule's Safety. Like random_eq, I'm ok with this not working if we want it not to, but we should probably say something about it in the config file if so.

I'm a little confused about your last point. The `succesRDMax` option is supposed to increase your Max R&D when a flight is successful, in addition to the safety gain. It shouldn't have any impact on crashes. Other than the misspelling, what's wrong with it?

**Comment by peyre** [comment]
Oh yes, I think I got succesRDMax wrong.  We can strike that out - my mistake there.  (I know I quibbled about altasLunar, but I don't have a problem--unless others do--assuming succes is just a shortening.)

Those two that were never implemented: I'd be happy to lose them.  They seem kind of unnecessary and a lot of work to implement, as you point out.  I'll remove them from the documentation next time I'm at it, and maybe we can rem out the lines that create them when the config file is created.

So, it looks like we're down to the two that make the game crash.  Thanks for checking those out!

**Comment by peyre** [comment]
Well - this is just a bit overdue, but better late than never.  I've removed random_eq and eq_name_change from options.cpp, so they won't appear in any (new) options file.

**Comment by rnyoakum** [comment]
Okay - I believe I have fixed problem (1) in 74823997512fff5a417d08f2aa01a66eac1af5b0. The `show_recruit_stats` and `use_endurance` options should no longer cause a segmentation fault.

**Comment by rnyoakum** [comment]
> Okay - I believe I have fixed problem (1) in 7482399. The show_recruit_stats and use_endurance options should no longer cause a segmentation fault.

That ought to resolve all of the concerns detailed. You took care of (2), handled (3) and (4) in 288c36ea58daba0eb7e98e30f611333ec53b7fea, I believe (5) was fixed by #517, and (6) is moot.

This issue is ready to be closed.
