### ISSUE TITLE
Fire kills wrong(?) people, then mission isn't scrubbed

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#529]
This is another obscure one.  A fire broke out and engulfed the LM, killing...everyone but the LM pilot(!)  Then the mission continued, and the surviving crew member actually did an EVA on the Moon while the empty capsule orbited overhead.

![Fire 1](https://user-images.githubusercontent.com/3118014/115158806-eaa78700-a044-11eb-94d7-7b5cbaabd7b7.png)
![Fire 2](https://user-images.githubusercontent.com/3118014/115158807-eb401d80-a044-11eb-9555-a3b9feb80789.png)

**Comment by peyre** [comment]
And another similar one: a fire in the LM killed everyone but the Commander (so maybe this mission kills crew members somewhat randomly, which is probably fine), but then the mission continued and Popov attempted the landing.

![Fire 3](https://user-images.githubusercontent.com/3118014/115159016-f3e52380-a045-11eb-9954-b97ff0d54698.png)

**Comment by hweimer** [comment]
Type 16 failure, here. That one always (randomly) affects all nauts, although the message sounds that it should only apply to the ones inside the LM. In any case, the mission should not continue but branch to alternate instead.

**Comment by hweimer** [comment]
There's a similar issue with ORBITAL EVA steps, where killing the naut by a type 22 failure doesn't cause the mission to get scrubbed. Just had a dead guy happily performing an LM test and spacewalking a second time after a failed docking.

**Comment by peyre** [comment]
Haha - "Nothing to see here! Move along, people."

**Comment by hweimer** [comment]
This affects type 16, 17, and 22 failures.
