### ISSUE TITLE
Centering of names in "who should be first on Moon" screen

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#535]
When the game asks who should be first on the Moon, there are times when the names might go past the edge of the button, as in this pic borrowed from # 476.  I've moved them over to the left, but that makes short names look funny - it would be handy if they could be centered, but I've had trouble getting the game to do that.

![dead](https://user-images.githubusercontent.com/3118014/96385637-068ba800-114a-11eb-9cc5-c8887b99ec60.png)

**Comment by rnyoakum** [comment]
Okay - handling this using the TextDisplayLength() function should be straightforward.

**Comment by peyre** [comment]
I tried doing that, but it just wouldn't do it - I think it's a problem with the variable type, but I had trouble sorting that out.

**Comment by peyre** [comment]
Grr - MX[cPad][i].A errors out if I try to assign it to a **char** variable.  What am I doing wrong?

**Comment by rnyoakum** [comment]
> Grr - MX[cPad][i].A errors out if I try to assign it to a char variable. What am I doing wrong?

`MX[cPad][i].A` is a pointer to the astronaut entry, so you shouldn't be assigning it to a char. If you want to access the astronaut name, you need `MX[cPad][i].A->Name`. If you'd like, you can email me directly with any questions.

**Comment by peyre** [comment]
That's it, thanks!!
