### ISSUE TITLE
Problems with type 7 mission errors

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#537]
I have several concerns with how type 7 mission step errors are implemented. I started discussing them [here](https://github.com/raceintospace/raceintospace/issues/530#issuecomment-829579930) but since they go beyond the scope of that issue, here we are.

Originally, type 7 errors were supposed to damage the hardware permanently, and that's supported by some of the error messages - for example: `SUIT MALFUNCTION, COOLANT SYSTEM IS BROKEN. EVA IS SCRUBBED. EVA SUIT SAFETY FACTOR IS REDUCED BY 20%.`.  In spite of the game text, there is no penalty assigned to the relevant hardware. This was changed in the the old CVS repository seen [here](https://github.com/raceintospace/raceintospace-cvs/commit/539db695d2b6e7d8c5ddaf7a96f1f166a42e975d#diff-0408c681edd9aefd3a917cfe7a6e6d0b1c0caac9176eb6cd82bac06b1a8a1a35) with the log message

> 2011-06-11    Nicolas Laplume <nikakd@users.sourceforge.net>
>       * V264
>
>       * Make MaxRD improve by 1 with each succesful mission (up to MaxSafety-2)
>
>       * Make MaxRD change back to original MaxRD after catastrophic failures
>
>       * Reduce Safety penalty in no-catastrophic failures to up to 10 (to 0 if "All systems are GO")
>
>       * Fixed bug that awarded duration level if last duration step failed

I presume the change was to reduce the oft-lamented difficulty of the game. From Nicolas' notes, the equipment damage was reduced to 0 because the status message for this type of error is "All systems are GO" (more on that later). Regardless, there's a disparity between the game behavior and the error description which should be corrected.

Another concern is that type 7 errors uniformly use the "All systems are GO" error message. It's an odd choice since the StepInfo value for that step is set to 

>         Mev[STEP].StepInfo = 1700 + Mev[STEP].loc;

and StepInfo values from 1000-1999 correspond to a step failure. Consider the error text for the two Lunar EVA instances:

> SUIT MALFUNCTION, COOLANT SYSTEM IS BROKEN. EVA IS SCRUBBED. EVA SUIT SAFETY FACTOR IS REDUCED BY 20%.

Scrubbing the Lunar EVA doesn't sound like an "All systems are GO." "Step Failure" is more apt, but since the Lunar EVA is the whole point of its mission, "Mission Failure" is the strongest contender.

Meanwhile, the error text for the Orbital EVA failures is:

> DURING EVA, SUIT MALFUNCTION: COOLANT SYSTEM IS BROKEN. EVA IS CUT SHORT.

The StepInfo value marks the step as an error, but the error text resembles another error (a code 0) which is ruled a success

> OVEREXERTION, CONDENSATION ON VISOR FORCES CREW TO SHORTEN EVA. EVA STILL SUCCESSFUL.

The latter example creates a precedence whereby a shortened EVA is ruled a success. I'm not sure how to rectify this conflict, as it leans toward the _opposite_ approach: inflict some program damage and declare the step successful.

Finally, there's the case of the Minishuttle landing errors
> - 'JAMMED NOSE GEAR LIMITS STEERING CONTROL. COLLISION WITH FIELD EQUIPMENT, MAJOR DAMAGE TO SHUTTLE.'
> - 'HARD LANDING, LANDING GEAR IS HEAVILY DAMAGED. '
> - 'HEAVY TURBULENCE, PRIMARY SITE IS REACHED. SHUTTLE IS DAMAGED. '

But, end of the day, the craft landed and everyone is fine. Hooray! More so than the Orbital EVA failure, it seems like it should be counted as a success; while a problem arose, the step (and mission) was completed and the crew was fine. It's weird that two of the error scenarios are instance-specific damage rather than program-specific, but since mini-shuttles are reused, that's OK?

These errors seem like they have just enough in common - the hardware program is damaged (err, no longer implemented), and the mission continues - that they are associated under a single error type. I'm not sure they should be.

**Comment by hweimer** [comment]
The lunar EVA is simply the wrong code. This should be a code 26 failure, which both damages the equipment and marks the step as a failure. Currently, you will win the game when encountering this failure even though no lunar EVA has taken place. The orbital EVA ones look fine as they are (successful step, no damage to equipment), and the minishuttle landings could go either way. I will fix the lunar EVA case, but leave the others unchanged.
