### ISSUE TITLE
Header Text displays incorrectly

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#540]
Header text shows the wrong characters for alphanumerics.  Here's what I see it doing.

Should show:
> ! @ # $ % ^ & * ( ) - = , . / ; : ?

Actually shows:
> ? " # $ ^ % ) ' ( - < + - . : 9 >

So it looks like it shows the following symbols incorrectly: ! @ % ^ & * ( ) = , . ; :
Except, it doesn't seem to handle them entirely consistently.  Not sure what's going on here.

This is Basic Training showing !@#$%^&*() -=,./;:?
![BasicTraining](https://user-images.githubusercontent.com/3118014/120218084-14300280-c1ee-11eb-8e4d-0c1e0c5736c0.png)

**Comment by rnyoakum** [comment]
This looks like it was an earlier version of issue #566, which was resolved. I'm pretty sure this was also fixed by solving the other, so I'm closing.

**Comment by peyre** [comment]
Looks like it.  Good to close two Issues with one fix.  I'll test this out soon and see if any characters still aren't showing right; I'll reopen the issue if so (or 566 instead, if that'd be better).
