### ISSUE TITLE
Air Force pilots

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#541]
I've noticed that when the Air Force transfers three pilots to your space program, they come in with zeros in all their skills - consequently they never become very talented.  I wonder if we should have the game give them a few random skill points; it looks so odd to see all zeros.

![AF Pilots](https://user-images.githubusercontent.com/3118014/120081982-305c6400-c075-11eb-9b51-f3e620d62dfc.png)

**Comment by rnyoakum** [comment]
I'll have to check, but that sounds like a bug - I was pretty sure they had defined stats in the Roster file, at least for the US candidates.

**Comment by peyre** [comment]
I don't think they're in there.  The names (and Service) are hard-coded in news_suq.cpp.

**Comment by rnyoakum** [comment]
Wow! You're absolutely right! I'd misremembered seeing the stats once, and reasoned they weren't being loaded, but I searched the data files for YEAGER and he's nowhere to be found. They should have defined stats like the other astronauts - I'd imagine Yeager should have a pretty high Capsule skill.

**Comment by peyre** [comment]
Oh I hadn't thought about assigning skills to them; I'd been thinking of assigning skills at random - I was thinking assigning skills on a d4: 1=0, 2-3= 2, 4=3.  However I have no problem assigning skills if we want to do that.  

In addition to Yeager, Ilyushin should also have a high CA I think, since he was a decorated, high-ranking test pilot.  Come to think of it, the newscast says all three are "test pilots" (US) or "top fighter pilots" (USSR), so probably none of them should have a CA0.  

Of course there's also the flip side that this newscast is already giving the player the advantage of 3 extra 'nauts for free and it could be unfair to give one player three super-nauts.  Seems to me if we want to assign skills, Yeager and Ilyushin should be CA3 and the others CA2 or less.  Not sure about the other skills.

It also comes to mind that we might want to reconsider a couple of the names.  Manke and Powell were test pilots for the lifting bodies the XMS-2 is patterened on, so they're good I think, but Shiborin and Dolgov are maybe problematic.  Dolgov was an air force colonel who was killed testing pressure suits at high altitude, so he was involved with the space program in a way.  Shiborin is make-believe though; he's one of the [phantom cosmonauts](http://www.astronautix.com/p/phantomcosmonaut.html).  I chose him because he also appeared in Michael Cassutt's novel _Red Moon_.  So it may be worthwhile to replace Shiborin, at least, with a real-life Soviet pilot.

**Comment by rnyoakum** [comment]
> Of course there's also the flip side that this newscast is already giving the player the advantage of 3 extra 'nauts for free and it might be unfair to give them three super-nauts. Seems to me if we want to assign skills, Yeager and Ilyushin should be CA3 and the others CA2 or less. Not sure about the other skills.

On this, I support keeping to historical accuracy as much as possible. RIS originally attempted to accurately reflect the skill levels of astronaut/cosmonaut recruits, so new scores should follow the same guidelines. The big change is transitioning from _recruits with no skill_ to _recruits with skills_. Yeager having a 4 instead of a 3 is minor in comparison, so it seems more an issue of one exceptional 'naut and two solid ones (I don't imagine they're all six Chuck Yeager-caliber).

But even if they are (historically) all super-nauts I'm unconcerned. Strong 'naut recruits are valuable, but in my experience less important than MBs. Would I rather see an early +15MB boost to my budget, or a timely safety increase of ~20% to my Saturn V program? Yes, yes I would.

**Comment by peyre** [comment]
I'm ok with that.  Do we want to hard-code the stats, or add them to the 'naut roster?

**Comment by peyre** [comment]
Ok, I've rolled up stats for the Air Force pilots, similar to how I did women for Group IV and V, except for skills 0-3 (0 1-2, 1 3-5, 2 6-8, 3 9-0 on a d10).  Moved around a handful of skills (esp. to make Ilyushin and Yeager good pilots), and here we are.  We can change these of course.

```
NAME        CA LM EV DO EN

MANKE       1  2  2  1  3
POWELL      2  0  0  1  0
YEAGER      3  0  1  1  2

ILYUSHIN    3  0  0  3  3
KRAMARENKO  2  1  2  0  3
DOLGOV      2  3  0  0  1
```

**Comment by peyre** [comment]
Ok, the game now assigns them the above skills.  We can change them, of course, and when we redo the 'naut roster, we can add them to that rather than hard-coding them.

**Comment by peyre** [comment]
Here's a screenshot.

![Air Force Pilots](https://user-images.githubusercontent.com/3118014/132108196-e429137c-c3a8-4a8e-acde-0aa6c40afc6d.png)
