### ISSUE TITLE
Crew survived rocket explosion?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#547]
I just had a rocket explode on the pad.  Nothing about the emergency escape system pulling them to safety - it just blew up - yet my astronauts survived.  The rocket didn't take the pad with it, which probably helps.  Any idea what happened here?

![Crew not killed](https://user-images.githubusercontent.com/3118014/121781763-1fbeea00-cb5b-11eb-8f24-9f7ef9966f27.png)
![Crew not killed 2](https://user-images.githubusercontent.com/3118014/121781764-20578080-cb5b-11eb-87a3-7719749d2de2.png)

**Comment by hweimer** [comment]
That's a code 16 failure, i.e., the same situation #244, but in the other direction. This failure has a 40% chance to injure a 'naut and will never be fatal. Maybe the text could be adjusted by adding something about emergency abort procedures.

What puzzles me more is that you got away with 0 prestige points, that should have been a -7.

**Comment by peyre** [comment]
That is odd.  It's not like it was even a big-prestige mission in the first place, like first to fly a shuttle - this was a docking duration, which didn't accomplish either.

**Comment by hweimer** [comment]
Anyway, you tried to go for a manned orbital and didn't make it. That should mean -7 prestige, even if nobody got hurt.

This failure cannot occur for unmanned missions, so adding a text of "FLIGHT CREW EVACUATES." would be fine and have some consistency with "MINOR FIRE ON PAD, EXTINGUISHED BY GROUND CREW. FLIGHT CREW EVACUATES SAFELY."

**Comment by hweimer** [comment]
Hmm, that doesn't seem to be quite right. If you have already done a manned orbital, a catastrophic failure on launch or orbital ins burn doesn't seem to affect your prestige in any way. However, a simple branch to failure on orbital ins burn gives a -7.

![547](https://user-images.githubusercontent.com/68769393/121960865-f5da1300-cd66-11eb-90b3-b5b34f55048a.png)
![547-2](https://user-images.githubusercontent.com/68769393/121960871-f8d50380-cd66-11eb-9dbf-06d22b6bac48.png)

**Comment by peyre** [comment]
Wow, that's backwards, isn't it?

**Comment by hweimer** [comment]
The second case looks okay to me, given that a failed orbital should warrant a -7 prestige (used to be -10, but this got softened at some point). The first one, not so much.

**Comment by peyre** [comment]
Ah, I can clarify the "softening" - years back I suggested to Nicolas Laplume (who did a _lot_ of the work for v. 1.0), that it didn't make sense that you lost as much prestige on a non-catastrophic failure on one of those 10-point failure missions whether the crew survived or not.  So he changed it supposedly to a random value of 7-10, but I think maybe it turned out to be exactly 7, which is fine by me.

**Comment by hweimer** [comment]
I just filed a PR that fixes both the ambiguous failure text and the prestige issue.

**Comment by peyre** [comment]
Great work, Hendrik!
