### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#550]
I just flew my first Gemini mission, an EVA Duration C.  The moment I saw my astronaut begin a spacewalk, the game crashed with the following:

![Core dump](https://user-images.githubusercontent.com/3118014/121816309-b65cdb00-cc2f-11eb-9aed-aa37b188a05d.png)

**Comment by peyre** [comment]
Just loaded the autosave and reran the mission, but it succeeded.  I wonder what went wrong the first time.

![EVA](https://user-images.githubusercontent.com/3118014/121817555-f96e7c80-cc36-11eb-9c23-b4a7846df4a9.png)

**Comment by hweimer** [comment]
Do you have the core dump lying around somewhere (i.e., does `ulimit -c` show something else than 0)? Otherwise, this will be challenging to hunt down.

**Comment by peyre** [comment]
Shoot, I don't think so.  Not sure where I'd find that.

**Comment by peyre** [comment]
Ok, I just had it happen again.  I've saved the game where it happened.  Where do I find the core dump, or how do I pull it up?

In this case, my Vostok killed the pilot on its first flight so I switched over to Lapot, and I was about to launch my first suborbital on it, followed by an orbital EVA, and it did a segfault.  I'll avoid playing any more til I hear from you, at least for the time being.

**Comment by hweimer** [comment]
Is there a file named "core" in the same directory? If yes, then I will need that as well as your raceintospace executable. If not, then you will first need to enable the creation of core files by running "ulimit -c unlimited" before launching the game. See https://askubuntu.com/questions/1349047/where-do-i-find-core-dump-files-and-how-do-i-view-and-analyze-the-backtrace-st/1349048

**Comment by peyre** [comment]
Ah.  No, there's no "core" file either in .raceintospace, raceintospace, or raceintospace-build.

So to generate one, what do I do exactly?  Running **ulimit -c unlimited ./raceintospace** in that folder doesn't do anything - no error, it just goes to the next line.
![ulimit](https://user-images.githubusercontent.com/3118014/128579976-708bf66e-9c9b-4974-8bc4-20b1fffe5ce5.png)

**Comment by hweimer** [comment]
The core file would be generated in the current directory, i.e., ~/raceintospace-build/src/game/core. If it's not there, you need to run
`ulimit -c unlimited`
first and then launch the game the usual way, i.e.,
`./raceintospace`
You can check whether setting the core file size worked by running `ulimit -c`, which should show "unlimited".

**Comment by peyre** [comment]
Oh why didn't I think of that?  So that started the game all right, but it hasn't created a core file there - either after finishing the game, or just opening it, or loading a save and going to next turn.  What am I missing?

**Comment by hweimer** [comment]
Am 8. August 2021 00:44:25 MESZ schrieb Leon Baradat ***@***.***>:
> Oh why didn't I think of that?  So that started the game all right,
> but it hasn't created a core file there - either after finishing the
> game, or just opening it, or loading a save and going to next turn. 
> What am I missing?

Did the game segfault again? Core dumps are only generated when a program is terminated abnormally.

**Comment by peyre** [comment]
Oh, is that it?  No, that would explain it - the game didn't segfault again.  Guess I'll have to play some more and see if I can get it to crash.  I don't recall what I was doing when it went down this last time.

**Comment by hweimer** [comment]
Am 8. August 2021 19:22:17 MESZ schrieb Leon Baradat ***@***.***>:
> Oh, is that it?  No, that would explain it - the game didn't segfault
> again.  Guess I'll have to play some more and see if I can get it to
> crash.  I don't recall what I was doing when it went down this last
> time.

Can you send me a copy of the saved game? I will see if I can get gdb's time-travel debugging to work (unfortunately, it's broken on the machine I mostly use for RIS development) and try to reproduce the bug by running something like 100 EVA steps in a row.

**Comment by peyre** [comment]
I emailed it to you.  Let me know if it hasn't come in.

**Comment by peyre** [comment]
So far, Hendrik and I have been unable to get it to segfault again with ulimit -unlimited running.  I'll keep trying.

**Comment by hweimer** [comment]
Unfortunately, gdb's time travel debugging does not work for multithreaded applications like RIS. I've started to look into rr, which supports multithreading, but this will take a while.

**Comment by peyre** [comment]
Um, not sure what that means on my end.  Should I keep trying to get it to segfault with `ulimit `running?

**Comment by hweimer** [comment]
It means that I won't be able to hunt down the bug in a systematic way in the near future, so yeah, it would be a good idea to continue to run the game that way in case you bump into it again. I'm always playing the game inside gdb (luckily, its ressource requirements are also on the level of the early 90s), so in case I should encounter the bug by chance, I should be able to trace it down as well.

**Comment by peyre** [comment]
Ok good, I'll keep at it as I'm able, and try to get the SOB to crash again.  It goes down twice when I don't want it to, but once I actually want it to crash again, ohhhhh noooo.

**Comment by peyre** [comment]
I seem to be having trouble sending the file.  I'll try again.

    On Thursday, August 19, 2021, 11:27:10 AM PDT, Hendrik W. ***@***.***> wrote:  
 
 


It means that I won't be able to hunt down the bug in a systematic way in the near future, so yeah, it would be a good idea to continue to run the game that way in case you bump into it again. I'm always playing the game inside gdb (luckily, its ressource requirements are also on the level of the early 90s), so in case I should encounter the bug by chance, I should be able to trace it down as well.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hweimer** [comment]
Could be that the file is too large, core files can have quite a bit of size. Does compressing it help?

**Comment by peyre** [comment]
I zipped it and mailed that to you, but it failed with a bogus reason.  At that point I tried to send it to you again, but I had accidentally wiped the whole folder at that point, so all I have left is the original attachment from the email, which I'm not sure I trust.  I'll try again.

    On Sunday, September 5, 2021, 4:13:02 AM PDT, Hendrik W. ***@***.***> wrote:  
 
 


Could be that the file is too large, core files can have quite a bit of size. Does compressing it help?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by peyre** [comment]
How about this?

    On Sunday, September 5, 2021, 4:13:02 AM PDT, Hendrik W. ***@***.***> wrote:  
 
 


Could be that the file is too large, core files can have quite a bit of size. Does compressing it help?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by peyre** [comment]
Given that I haven't seen this in almost 2 months of play, and that another segfault was caused by one of the images I had modified, I wonder if this whole thing was due to a modified image that I've since fixed.

**Comment by peyre** [comment]
I still haven't seen this recur, so I think I'll close the issue.  Must have been one of my modified images that I later fixed.
