### ISSUE TITLE
Mac OS X build fails with CMake errors

### ISSUE THREAD

**Issue by sflynn850** [raceintospace/raceintospace#551]
Hi all!

Attempting to build the project on Mac OS X (Version 11.3, 13" 2020 MBP M1) results in the following error:

```
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:29 (if):
  if given arguments:

    "STREQUAL" "debug"

  Unknown arguments specified


-- Configuring incomplete, errors occurred!
See also "/Users/sean/personal_code/raceintospace-build/CMakeFiles/CMakeOutput.log".
See also "/Users/sean/personal_code/raceintospace-build/CMakeFiles/CMakeError.log".
```
Attachments:

[CMakeError.log](https://github.com/raceintospace/raceintospace/files/6651429/CMakeError.log)
[CMakeOutput.log](https://github.com/raceintospace/raceintospace/files/6651430/CMakeOutput.log)

Will be updating this issue as I continue to troubleshoot.

**Comment by sflynn850** [comment]
Adding the -DCMAKE_BUILD_TYPE=debug argument to the cmake command resolves this issue, as you might expect - I guess there's two points to update here:
1) Why isn't a default value being set?
2) If we don't want a default value, it seems like we might want to update the documentation.

**Comment by peyre** [comment]
Looks like a good catch there, though I don't know anything about the Mac myself.  The game also seems to fail to build in Windows - don't know what's wrong there.

**Comment by smudog** [comment]
I had to backup to version 5c34ed9 before the error checking code was checked in to get it to compile past this point. (trying on to compile on an M1 MacBook Pro).
