### ISSUE TITLE
The yellow blocks don't always show right

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#555]
About the yellow blocks that are supposed to show at the top of the blue bars during a mission (i.e., added to the Safety of the affected component), which are supposed to indicate when that step has someone with a 4 in the relevant skill...

This is a tough one to confirm, but I'm sure I've seen the blocks appear all over the Capsule steps when the pilot was a CA3, and even occasionally when it was a CA2.  I don't know what might be going on, but I thought I should bring it up.

![Docking](https://user-images.githubusercontent.com/3118014/124297009-7478d380-db0f-11eb-9359-39d103ca7453.jpg)

**Comment by sflynn850** [comment]
I think this happened in the original game too.

**Comment by hweimer** [comment]
That's a rounding thing. At 100% safety, the bar has a height of 22 pixels. Depending on how the rounding of both the safety factor and the safety factor minus the 'naut skill goes, you can have anything from a skill value of 1 being enough to get the yellow block and even a value of 4 not being enough. (Of course, a skill value of 4 will result in the blocks being shown most of the time, while a value of 1 typically doesn't.)

**Comment by peyre** [comment]
No kidding!!!  I never would've thought of that - but arguably, should have.  I'll have to mention that in my RIS guide.
