### ISSUE TITLE
New Atlas image

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#556]
I don't know if other people feel the same, but I've always thought the image of the Atlas looked kind of lame:
![rdfull but 8](https://user-images.githubusercontent.com/3118014/124365107-c6e2ee80-dbfa-11eb-9662-07deabff2794.png)

Seems to me we should be able to do better.  I put this together this morning; I'm not real happy with it, but I'm no artist.  Thoughts anyone?
![rdfull but 8](https://user-images.githubusercontent.com/3118014/124365158-07db0300-dbfb-11eb-81d7-607cbb8059b3.png)

**Comment by sflynn850** [comment]
I like it! It's a lot closer to how it actually was.

**Comment by peyre** [comment]
Thanks.  It doesn't look as good in the game.  I wish I were a bit more talented at this sort of thing, 'cause I'd like to make it an approximation of the original on a par with the Titan image.

![Atlas](https://user-images.githubusercontent.com/3118014/124390450-8fc71880-dca0-11eb-80da-c97464297c09.png)

**Comment by peyre** [comment]
I've touched it up a bit at the bottom.  Is this any better?

![Atlas2](https://user-images.githubusercontent.com/3118014/124393229-4382d500-dcae-11eb-9756-a7f413af6ab4.png)

**Comment by peyre** [comment]
Ok, we're about to leave on vacation to Oregon & Washington for a couple weeks, so I will upload this image for now.  We can revert or replace it if needed - I'll be the first to admit this image can use some help, though I do think it's an improvement over the original.

**Comment by sflynn850** [comment]
👍

**Comment by peyre** [comment]
The change is made and seems to be working ok.
