### ISSUE TITLE
Header text has wrong alphanumerics

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#566]
Header text for alphanumerics shows some wrong characters.  I assume the headings are those characters in /data/images, letter.dat.#.png.  The following, for instance, should show #$%&'()*+,-./ at the top:

![Purchasing 2](https://user-images.githubusercontent.com/3118014/129448713-8854a7d2-8b34-4d49-a10c-05da17443ecd.png)

And the following should show []^_`:;<=>?

![Purchasing](https://user-images.githubusercontent.com/3118014/129448337-ac3c54b3-f0dc-4242-88a2-a4e3d5f5275f.png)

There were some characters - " ( ) \ - that I couldn't get it to display, so I don't know how those show in the game.  Anyhow, it's not like these get used all the time - otherwise the issue would've come up much sooner - but I think it'd be good to correct this at some point.

**Comment by peyre** [comment]
Also, ! seems to not show at all - I think it displays as the empty character, letter.dat.0.png.  So it looks like the wrong characters (that I can find) are:

# - "
$ - #
% - $
& - %
' - &
( - '
) - (
* - )
+ - *
, - +
- - -
. - -
/ - .

: - 9
; - :
< - ;
= - <
> - =
? - >

**Comment by rnyoakum** [comment]
Looks like there's an off-by-one error in there. Should be reasonably easy to fix.

**Comment by peyre** [comment]
I've wondered if it might be something like that.  Certainly parts of it look that way.

**Comment by peyre** [comment]
Yes Ryan, all the list above is displaying correctly now (also the backtick [`], if it wasn't before).  Thanks!
