### ISSUE TITLE
Newscast doesn't lower Safety of hardware item

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#569]
I had a newscast come up saying my EVA suits' Safety was lowered by 64.  They were only at 30, but ok, so I go to see if the game put them at 5% or what, and...they're unchanged!

![EVA Suits](https://user-images.githubusercontent.com/3118014/129450373-e063abdc-0b9c-4d44-b88d-6cf4bb3bd36c.png)
![EVA Suits 2](https://user-images.githubusercontent.com/3118014/129450375-c34c3880-e334-4706-906a-0f65cb5ee229.png)

**Comment by hweimer** [comment]
30 is the lowest possible value for EVA suits. There's a check in the code that prevents you from going below the initial safety factor without technology transfer being applied.

**Comment by rnyoakum** [comment]
While the safety value shouldn't go below the minimum value, it's still unusual from the player's perspective. Ideally, the news report should list the _actual_ decrease in the safety value, and if no change occurs one of the "color" news items should be substituted. I'd still characterize this as a bug.

**Comment by hweimer** [comment]
Fair point, but "THE SAFETY FACTOR FOR EVA SUITS IS NOW LOWERED BY 0." is also a bit weird.

**Comment by peyre** [comment]
Good points there!  It _would_ be nice if the newscast gave the actual value, and substituted one that doesn't do anything if the decrease doesn't have any effect.

**Comment by rnyoakum** [comment]
This problem was being caused by an array indexing error when checking if tech theft was allowable. It should be fixed now.
