### ISSUE TITLE
I'm not sure the Funding Appropriation newscast is actually working

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#585]
This is odd.  I had 4MB left over after the spring.  In fall I get a message saying I'm given an extra 5MB and I thought great, I can use it for research, but when I came into the spaceport I was still at 4MB.

![Funding appropriation](https://user-images.githubusercontent.com/3118014/133424340-58903610-4a2c-4f6e-9128-8db972f8dd74.png)
![Funding appropriation2](https://user-images.githubusercontent.com/3118014/133424342-be824678-38c4-4192-bf55-006d0ad8b107.png)

**Comment by hweimer** [comment]
The newscast increases your budget, not your cash. The budget is converted into cash only once per year, after the fall turn.

**Comment by sflynn850** [comment]
It does seem a bit unclear though - I can see how someone would expect
another 5 MB in their coffers.

**Comment by hweimer** [comment]
True, but unless we find a way to make good old Carter Walcrite say things he didn't say, we are kinda stuck with the wording of the newscasts.

**Comment by peyre** [comment]
I'll have to listen for it next time(s) I play and see if there's a plausible change/addition that could make it more clear.
