### ISSUE TITLE
Astronaut names not changing color like they should

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#603]
When you assign crews to a mission, crew.cpp is supposed to print the name in black if someone has announced retirement, and in blue for females.  But it doesn't seem to be doing that now.  In these screenshots, Armstrong had announced retirement and showed in black in the Capsule screen etc., but not here.  I can't think what I might have changed to make this happen.

![Armstrong has announced retirement - should be showing in black](https://user-images.githubusercontent.com/3118014/141384534-fda7548d-65d9-4de3-8bed-e40a42fc6043.png)
![Women should show in different color](https://user-images.githubusercontent.com/3118014/141384537-a7f5ae03-9644-4a4a-843e-81c2ebaee20f.png)

**Comment by peyre** [comment]
Ok, fixed it.  This was broken by the code I added to avoid names after those EN highlights showing in yellow as well.  Just had to move the line up a bit.

**Comment by rnyoakum** [comment]
Hmph, I was going to commit the fix when I saw that you had already done it in 3760754762e1518b1ffe96bfeb6d6bd71f1554c1. Then you beat me in closing the issue literally while I was writing my comment.

**Comment by peyre** [comment]
D'oh!  I hate to see us doubling our efforts.
