### ISSUE TITLE
Clean up country emblems

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#605]
Originally, the country emblems that display before the start of each turn (data/images/turn.but.0.png) were shorter vertically than horizontally. Leon created a revised version that made them [more circular](https://github.com/raceintospace/raceintospace/issues/51#issuecomment-580877295), but the changes also washed out the stripes on the US flag and blurred the stars.

I recommend the image should be edited by either
- reverting to the original image, or
- editing (either version) to obtain a round(er) image which preserves detail.

**Comment by peyre** [comment]
Oh, good point.  I'll have to look into this.

**Comment by peyre** [comment]
Well, they sure did.  In fact they made the whole image more blurry.  How about this?  I'm no artist and the Soviet emblem looks a little...homemade.  The border it a little crude and wobbly; that thing's a challenge to get looking right!  But how do these look?

**Comment by peyre** [comment]
Hey, I never noticed this before, but this page was cutting off the bottom row of the image--that's why the bottom looks flat.  Fixed it.  I also touched up the emblems some more; I think they're better now.

![turn but 0](https://user-images.githubusercontent.com/3118014/143982878-b80b6ff5-07cf-478a-ac94-830822f6fd36.png)

**Comment by peyre** [comment]
Damn!  It's still cutting off the bottom row of the US emblem when you're doing single-player as the Soviets.  I don't know why.

**Comment by peyre** [comment]
Ah!  Fixed it I think.  I'll upload the logos as I currently have them.  Let me know if they need more touchup.

**Comment by peyre** [comment]
I touched up the Soviet emblem a bit.  I think it's better now.

![Sov](https://user-images.githubusercontent.com/3118014/146647118-f99089fb-e59a-49bc-af13-4f7a93a9aee7.png)

**Comment by rnyoakum** [comment]
These images look a lot crisper than they had. Whenever you're satisfied, I think this issue can be closed.

**Comment by peyre** [comment]
Thanks!  I'll close this one then.  Of course we can always fine-tune them more later if we think appropriate.
