### ISSUE TITLE
LM should have 1 crew, only found 0

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#607]
I just found these two error messages in my terminal window after getting beaten by a hair by the AI.  This must have been referring to the computer, which used the 1-man lander, whereas I used the 2-person LM.  It must be that the AI didn't have any astronauts to spare for the LM crew, or something?  (Similar to the issue we had with not enough 'nauts for a direct ascent crew - #552.)

```
ERROR   /home/leon/raceintospace/src/game/mis_m.cpp:1446:LMCrew	LM module should have 1 crew, only found 0
ERROR   /home/leon/raceintospace/src/game/mis_m.cpp:1446:LMCrew	LM module should have 1 crew, only found 0
```

**Comment by hweimer** [comment]
The problem is that the naut selection only looks for the current pad, which is the wrong one for joint launches (initially, there are no nauts on the pad with the LM). I have used the same logic as in the selection of the first naut on the moon, as this one seems to work properly.
