### ISSUE TITLE
Hardware can exceed Max Safety

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#614]
I think I've seen this before but only now confirmed it and worked out what's going on.  If you fly a successful mission with something (the shuttle in this case) that's at Max Safety (94%) already, and there's a mission to go on the next pad, it gets Max Safety +1 (95%).  This is all corrected by next turn - but it looks like the game checks for anything exceeding Max Safety _after_ all missions fly.

I don't know if this is something that's worth addressing or not.

![95 Percent](https://user-images.githubusercontent.com/3118014/153770135-f874b115-3ed2-4cec-b2a1-1d2c7c98dd8a.png)

**Comment by peyre** [comment]
Here's another example, rather amusing.  "100 percent, you say?"

![B-R-7 100](https://user-images.githubusercontent.com/3118014/155891409-fd6f245d-5f5b-4bb9-80f3-35b0c0da7f3f.png)

**Comment by rnyoakum** [comment]
This should be fixed by https://github.com/raceintospace/raceintospace/commit/c4655da065a0166ab0bbb8d3e46f04fe053a2311.

**Comment by peyre** [comment]
Uh oh, I just noticed an issue.  I just flew two missions with my Soyuz this past turn (both successful as to capsule), but it gained only 1 point of Safety.
