### ISSUE TITLE
Emergency escape works but then didn't

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#659]
Something went wrong in the launch step and the mission movie showed my emergency escape system (presumably) pulling the capsule to safety, but then it says the capsule was pulled down by the booster.

![Negative stage separation](https://user-images.githubusercontent.com/3118014/173244264-0349b63f-e748-49fd-a56f-f9f3f60f4915.png)

**Comment by hweimer** [comment]
Hm, I can't confirm the pulling to safety part, this failure gives me a sizable impact crater every time I've tested it. The only oddity is that you don't see the rocket rising from the pad, a fate it shares with "NEGATIVE STAGE SEPARATION, CAPSULE EMERGENCY SYSTEMS WORK. RECOVERY REQUIRED." and NEGATIVE STAGE SEPARATION, CAPSULE PULLED DOWN BY BOOSTERS."

![Screenshot_20220612_203211](https://user-images.githubusercontent.com/68769393/173248165-311c2dcf-f5b1-4bb1-8362-ec0be6834690.png)

**Comment by peyre** [comment]
That's the problem with these oddballs, where there's a small disconnect between what's said and what's shown in a mission movie.

**Comment by peyre** [comment]
Had this again today.

![CapsuleEscape](https://user-images.githubusercontent.com/3118014/178119304-acdb917c-1290-4abf-b0e2-8c73b56be4bf.png)

**Comment by hweimer** [comment]
This one also got fixed by 6a07647cc6ee1db3218fcf27ac331b5ab5e04416.

**Comment by peyre** [comment]
Good catch.
