### ISSUE TITLE
Blank name of save game

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#660]
Now when I save the game, it seems to give it a blank title/name.

![Trouble with save game](https://user-images.githubusercontent.com/3118014/173244470-0ac6acb9-f4ba-487c-920c-9b1e01e4fc36.png)

**Comment by hweimer** [comment]
Yeah, that looks like one of the leftovers when the save game code got refactored.

**Comment by peyre** [comment]
I figured the things I'm seeing this morning are probably from that.  I'm glad you made the changes to standardize the code a bit; we just have to iron out the wrinkles from it--thanks for taking care of this one already.

**Comment by peyre** [comment]
Uh oh, it looks like it's displaying the .sav extension now.

![Leon sav](https://user-images.githubusercontent.com/3118014/174496243-3723a8b1-320c-4322-b254-2499c5761cbd.png)
