### ISSUE TITLE
Core dump in Intel during a mission

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#675]
I was flying a Manned Lunar Pass, and just after the Reentry step, the game crashed with this message:

raceintospace: /home/leon/raceintospace/src/game/intel.cpp:524: void MissionIntel(char, bool): Assertion `mis >= 0 && mis <= 56 + plr' failed.
Aborted (core dumped)

Edit: wait, I may have misremembered when it occurred.  I just started the game again, loaded the save, and the mission succeeded.  But then while showing my opponent's prestige first (a Mercury flyby), it crashed again with the same message.

But on my third try, it showed my opponent completing the Manned Lunar Pass just ahead of me, I flew mine, then it showed the computer's Mercury flyby prestige first with no trouble.

I have the save game if anyone wants to see it.

**Comment by hweimer** [comment]
Feel free to send me the save game. I have an idea where to look for the problem.

**Comment by peyre** [comment]
Thanks Hendrik!  Here it is.

    On Sunday, September 18, 2022 at 02:10:51 PM PDT, Hendrik W. ***@***.***> wrote:  
 
 


Feel free to send me the save game. I have an idea where to look for the problem.

**Comment by hweimer** [comment]
Did you try to attach it to the bug report? That didn't work. Probably the best is if you send it to me by e-mail.

**Comment by rnyoakum** [comment]
One possible issue I might have discovered: Were you playing the Soviets with a Soyuz Lunar Landing planned for the next turn?

**Comment by peyre** [comment]
Oops.  Sent by email.

**Comment by hweimer** [comment]
@rnyoakum:
> One possible issue I might have discovered: Were you playing the Soviets with a Soyuz Lunar Landing planned for the next turn?

Yes, he did. The plr variable in MissionIntel refers to the current player, not the one on which the intel is created. If created a fix for that, with the minor downside that if you see a report for a Soyuz L.L., you know it's the real thing because this one will never be faked. But that's also true for some other missions like some Joint Lunor Orbital variants.

**Comment by peyre** [comment]
Wow, so that was it!  Lucky happenstance I thought yesterday I'd do something different an fly the Soyuz L.L.
