### ISSUE TITLE
Parking unmanned craft in lunar orbit counts as manned lunar orbital

### ISSUE THREAD

**Issue by hweimer** [raceintospace/raceintospace#678]
Blowing up a launch pad and still getting credit for a manned lunar orbital ... too bad these things never happen in actual games

![t1](https://user-images.githubusercontent.com/68769393/191094042-74ed0ebb-5082-4729-8f4b-ed328f0f1447.png)
![t2](https://user-images.githubusercontent.com/68769393/191094047-702d1ccd-dad2-4e93-bbfc-7dd5ee15ec45.png)

This bug was introduced in [98cf50a](https://github.com/raceintospace/raceintospace/pull/536/commits/98cf50a807e13ad3e18f1c1d56ade7ce6d8dd955) when I tried to outsmart the original devs (failing badly, of course), who chose to award the manned lunar orbital prestige on lunar orbital activities for a good reason: there is also a lunar orbital ins burn step in the first unmanned part of a Joint LOR mission, and obviously completing that step does not make it a manned lunar orbital. However, reverting this change would bring back #332.

**Comment by hweimer** [comment]
I think this should be fixable if we check whether the hardware assigned to the current pad has a capsule component, the same way it is currently done for the manned orbital prestige. I hope to find some time to test this later today.

**Comment by peyre** [comment]
That'd be excellent, Hendrik!  It would be good to have this little bug fixed before we release v. 2.0.

**Comment by hweimer** [comment]
Seems to work like a charm.

**Comment by peyre** [comment]
Wonderful!  Thanks for your hard work on this one.
