### ISSUE TITLE
Endurance not counted on Jt Orbital Docking Duration missions

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#690]
I've noticed a recent trend.  When I fly Joint Orbital Docking Duration missions, it _performs_ the duration steps of the mission, but it doesn't _count_ them.  This happened to me twice in a row.  This mission, for instance, was Duration C and it went flawlessly.

![EnduranceNotCounted](https://user-images.githubusercontent.com/3118014/193429814-140ff629-d882-41b9-9a8a-86a846afe359.png)

**Comment by peyre** [comment]
But, not always!  I just flew another one, and it did count it.  Maybe the problem is with Joint missions?

![Duration](https://user-images.githubusercontent.com/3118014/193429939-68cc9aae-f39d-4cb4-987a-4c74e9652905.png)
![DurationCounted](https://user-images.githubusercontent.com/3118014/193429942-56558523-e2ac-46c8-9a82-52f49a3a027c.png)

**Comment by hweimer** [comment]
I can confirm this bug, joint duration missions do not set the correct duration level. As far as I understand, the duration counter is only increased for the pad that does the duration steps (which usually is the second one in joint launches). However, Update_Prestige_Data always gets called with the first pad. I guess a way to fix this would be to have the duration level as the maximum of both pads for joint launches.

**Comment by peyre** [comment]
Thanks Hendrik.  It's good to get confirmation.
