### ISSUE TITLE
Viewing Stand shows wrong newscast

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#696]
I just started a game, and on the third turn I went back to see again what the newscast on my second turn was, but instead it showed the first newscast as being the newscast for my second turn.

![Spring 1957](https://user-images.githubusercontent.com/3118014/194769959-ef9bc63a-f9c2-46a9-a676-7f63e24abecc.png)
![Fall 1957](https://user-images.githubusercontent.com/3118014/194769966-f754f65c-510a-4099-835e-676991553803.png)

**Comment by hweimer** [comment]
Thanks for spotting this. Easy change, but I think it won't fix your current game.

**Comment by peyre** [comment]
Oh that's all right.  All save games are disposable, as far as I'm concerned.
