### ISSUE TITLE
Show Director Ranking in endgame?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#697]
It seems like it would be nice if the endgame offered an option to show the Director Ranking screen, in addition to the other options of things to see.

![Endgame1](https://user-images.githubusercontent.com/3118014/194772131-34ceec7f-653f-49c7-aef5-8df02f7f1d84.png)
![Endgame](https://user-images.githubusercontent.com/3118014/194772079-c92c149c-d794-4e9b-aedf-c4db57748782.png)

**Comment by hweimer** [comment]
Isn't that what it's showing when you click on the diagram on the top between "STATISTICS" and "EXIT"? Maybe it should be moved down to the other buttons to make it less confusing.

**Comment by peyre** [comment]
OMG, I never noticed that!  I always assumed that was just a decoration!
