### ISSUE TITLE
Doubled penalties if hardware used twice on joint missions

### ISSUE THREAD

**Issue by hweimer** [raceintospace/raceintospace#709]
If you fly a joint mission having the same hardware components on both launches, the penalty is applied *twice*. For example, if you have a 6% penalty and use a 98% Titan rocket on both launches, the mission safety will be downgraded to 86%. The bug lies in MisSkip/MisRush, which goes through the hardware table and subtracts the penalty irrespective whether the penalty has already been applied before.

**Comment by peyre** [comment]
Oh that shouldn't be.  Looks like a good catch on your part.

**Comment by peyre** [comment]
MisRush case?

**Comment by hweimer** [comment]
In my initial PR, I only addressed milestone and duration penalties (which are handled in the function MisSkip) and not rushing penalties (which are handled in MisRush).

**Comment by peyre** [comment]
Oh, I see.  Good spotting.
