### ISSUE TITLE
Downgrading from joint launches to single launches does not work

### ISSUE THREAD

**Issue by hweimer** [raceintospace/raceintospace#713]
When downgrading from a joint mission to a single launch, the data structures do not get updated properly. In the VAB, you can still select hardware for both pads. In my case (downgrading from Jt Lunar Orbital LOR to Earth Orbital-L, I had only two rockets and no payloads. Running the mission nevertheless caused an endless loop of EVA steps (huh?) after a successful launch on the first pad.

**Comment by peyre** [comment]
Good catch.  Hey, we're finding a lot of little issues in this PBEM testing!
