### ISSUE TITLE
Docking step rolled against LM safety factor

### ISSUE THREAD

**Issue by hweimer** [raceintospace/raceintospace#715]
If you have a craft that does not require a docking module to dock with a LM (e.g., three-seater, not sure if this also applies to the minishuttle), the docking step is rolled against the safety of the LM and not against the docking module. The relevant lines in the code appear to be:
https://github.com/raceintospace/raceintospace/blob/6b93c58872eafbb10a339a4f7da40465f9aa1e73/src/game/mc2.cpp#L312-L321
.Class = 2 is Mission_LM, i.e., an LM step.

I consider this to be a bug, with serious implications on the game balance. It means that if you fly Apollo/Soyuz, you can completely ditch all docking tests and rely on the R&D of your LM.

![t](https://user-images.githubusercontent.com/68769393/199008811-f041cc9c-815e-41a8-af14-a74aac21cb2a.png)

**Comment by peyre** [comment]
Yes, that sounds like a bug.

Pretty sure the minishuttles require a DM for LM steps of missions like Gemini does.

**Comment by hweimer** [comment]
If you try to launch an LM test without having prototyped the DM, the VAB complains and refuses to continue. So I think we can set the class to Mission_Probe_DM in all cases.
