### ISSUE TITLE
Allow Esc out of more screens

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#723]
It might be handy if Administration and the Museum, and many of the screens accessible from them, could be closed with the Escape key in addition to E in the first two and Enter in the others.

![Esc should Exit png](https://user-images.githubusercontent.com/3118014/204102633-08b5c98a-de98-4ec5-9d52-c22a6b0a7a97.png)
![Esc should Exit](https://user-images.githubusercontent.com/3118014/204102635-b15d5c2c-9e5e-4c95-a5e6-ee67e221637c.png)
![Esc should exit here too](https://user-images.githubusercontent.com/3118014/204102632-7e7b3b5d-ec75-4558-abb5-0357d941a6ab.png)

**Comment by rnyoakum** [comment]
This is completed with the exception of the Preferences option in the Administration menu. Due to its implementation, Preferences is tightly coupled with the New Game menu (see #289). That will take more work, but it is its own thing so I consider this resolved.

**Comment by peyre** [comment]
Thanks Ryan, it's nice to see these added.  While you're at it, do you think you could add it to Preferences as well, so someone who hit New Game by accident could cancel back out to the main screen (#289)?
