### ISSUE TITLE
Capsule freed but pulled down?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#725]
I had a launch failure, saw the video of the capsule being pulled out by the emergency ejection system, but then it said the capsule was pulled down by the booster.  Is this a bug, or am I misjudging this one?

![Capsule pulled down](https://user-images.githubusercontent.com/3118014/205455314-3d74cd33-1d2c-4107-a274-1b03a679f9d2.png)

**Comment by peyre** [comment]
Oh yes, this might be a duplicate!

Yes, the game plays capf_03.ogg, which shows the capsule being pulled away by the emergency eject system, but then it tells you they all died in the explosion it _just showed_ them escaping.

**Comment by peyre** [comment]
Is that what it is?  If so, all that would be needed would be a wording change in fails.cdr.  I'll see what I can do with that, test it this coming weekend.

**Comment by hweimer** [comment]
I think the best solution would be to have consistency with similar failures during the recovery step. Then, the first one would read "NEGATIVE STAGE SEPARATION. EMERGENCY SYSTEMS FIRE, BUT CAPSULE IS PULLED DOWN BY BOOSTERS AND HITS HARD." This is ambiguous enough to allow for all possible outcomes ranging from all okay to all dead. The second would read "NEGATIVE STAGE SEPARATION. EMERGENCY SYSTEMS FIRE, BUT CAPSULE IS PULLED DOWN BY BOOSTERS AND CRASHES. FLIGHT CREW KILLED."

**Comment by peyre** [comment]
Ok, I'll modify my fails.dat to match that and keep testing.  I've been playing a bunch hoping for the same failure to occur, but of course it keeps not happening.

**Comment by hweimer** [comment]
If you run the game inside gdb (e.g., via `make gdb`), you can CTRL-C in the console during countdown to get a gdb prompt, where you can enter
`print Mev[0].dice = 100`
to force a launch failure and
`print Mev[0].rnum = 8100`
to get the FLIGHT CREW KILLED failure or
`print Mev[0].rnum = 8190`
to get the other one. After you've made your changes, you can enter `c` to continue the game.

**Comment by peyre** [comment]
Hey, thanks!  So, do I just add gdb like so?
cd ~/ && sudo rm -r raceintospace-build && mkdir raceintospace-build && cd raceintospace-build && cmake -DCMAKE_BUILD_TYPE=Debug ../raceintospace && make gdb && sudo make install && cd src/game && ./raceintospace


    On Wednesday, January 4, 2023 at 11:17:52 PM PST, Hendrik W. ***@***.***> wrote:  
 
 


If you run the game inside gdb (e.g., via make gdb), you can CTRL-C in the console during countdown to get a gdb prompt, where you can enter
print Mev[0].dice = 100
to force a launch failure and
print Mev[0].rnum = 8100
to get the FLIGHT CREW KILLED failure or
print Mev[0].rnum = 8190
to get the other one. After you've made your changes, you can enter c to continue the game.

**Comment by peyre** [comment]
Well that didn't work.  Also since recent changes I've been getting:
WARNING /home/leon/raceintospace/src/game/fs.cpp:279:try_find_file    can't find file `liftoff.OGG' in audio dir(s)
WARNING /home/leon/raceintospace/src/game/fs.cpp:279:try_find_file    can't find file `good.OGG' in audio dir(s)
WARNING /home/leon/raceintospace/src/game/fs.cpp:279:try_find_file    can't find file `new1970.OGG' in audio dir(s)
WARNING /home/leon/raceintospace/src/game/fs.cpp:279:try_find_file    can't find file `usport2.OGG' in audio dir(s)
WARNING /home/leon/raceintospace/src/game/fs.cpp:279:try_find_file    can't find file `drumsm.OGG' in audio dir(s)
WARNING /home/leon/raceintospace/src/game/fs.cpp:279:try_find_file    can't find file `hardware.OGG' in audio dir(s)
WARNING /home/leon/raceintospace/src/game/fs.cpp:279:try_find_file    can't find file `usmil.OGG' in audio dir(s)
WARNING /home/leon/raceintospace/src/game/fs.cpp:279:try_find_file    can't find file `sovtyp.OGG' in audio dir(s)
[Thread 0x7ffff13f4640 (LWP 6075) exited]
[Thread 0x7ffff67b7640 (LWP 6073) exited]
[Inferior 1 (process 6070) exited normally]

    On Thursday, January 5, 2023 at 07:10:24 PM PST, Leon ***@***.***> wrote:  
 
  Hey, thanks!  So, do I just add gdb like so?
cd ~/ && sudo rm -r raceintospace-build && mkdir raceintospace-build && cd raceintospace-build && cmake -DCMAKE_BUILD_TYPE=Debug ../raceintospace && make gdb && sudo make install && cd src/game && ./raceintospace


    On Wednesday, January 4, 2023 at 11:17:52 PM PST, Hendrik W. ***@***.***> wrote:  
 
 


If you run the game inside gdb (e.g., via make gdb), you can CTRL-C in the console during countdown to get a gdb prompt, where you can enter
print Mev[0].dice = 100
to force a launch failure and
print Mev[0].rnum = 8100
to get the FLIGHT CREW KILLED failure or
print Mev[0].rnum = 8190
to get the other one. After you've made your changes, you can enter c to continue the game.

**Comment by hweimer** [comment]
The "[Thread ...]" messages come from gdb, so it looks like you are already running the game inside the debugger. I've made a small video that hopefully clarifies what you have to do.

[Screencast from 06.01.2023 08:34:46.webm](https://user-images.githubusercontent.com/68769393/210955786-f33348f8-aea9-42b1-8871-c124f82e2f20.webm)

**Comment by peyre** [comment]
Thanks for the video - that showed me the key, running make gdb by itself, then pressing Ctrl-C and all the rest in the terminal.  That worked, for both messages.  I still don't see, though, why we have it saying the capsule was pulled down by boosters when you actually see it fly free.

**Comment by peyre** [comment]
Also one time gave me a chuckle--I saw the capsule slam into the ground and it said the flight crew was killed, but two of them were only injured!  Maybe this sort of weirdness is to be expected when you force a failure.

![Crew killed](https://user-images.githubusercontent.com/3118014/211167595-a6df3e73-0b2b-4f16-a042-e3a2b05e18f5.png)

**Comment by peyre** [comment]
Also one time gave me a chuckle--I saw the capsule slam into the ground and it said the flight crew was killed, but two of them were only injured!  Maybe this sort of weirdness is to be expected when you force a failure.

![capf_04](https://user-images.githubusercontent.com/3118014/212737785-d2aa2f1e-0499-4e2f-af1b-f27d4c6ed58a.png)
![Crew killed](https://user-images.githubusercontent.com/3118014/211167595-a6df3e73-0b2b-4f16-a042-e3a2b05e18f5.png)

**Comment by rnyoakum** [comment]
Forcing a failure shouldn't be having an impact here. The fact that the failure text is being displayed indicates the desired error is being triggered, and unless you're doing further console editing the game should be implementing the consequences of the failure normally. Do you still have the save where the crew is surviving the crash?

**Comment by peyre** [comment]
Oh, sorry!  I don't.  I wasn't so much looking for a fix as having a laugh over 2/3 of the crew surviving a 140kph impact.

**Comment by hweimer** [comment]
One thing is that I think you have the two texts mixed up. When I get "NEGATIVE STAGE SEPARATION, CAPSULE PULLED DOWN BY BOOSTERS.", I can get injuries.

The other thing is that the two failures always show the same animations (modulo random variations). This is controlled by the .fail variable in the XFails struct (which is read from fails.dat). In both cases, it is set to 50. Changing the value to 40 for the not necessarily fatal failure would show the same animations as "NEGATIVE STAGE SEPARATION, CAPSULE EMERGENCY SYSTEMS WORK. RECOVERY REQUIRED.", which at least shows a parachute opening and no hard impact.

**Comment by peyre** [comment]
_Pretty_ sure I did them in the order you suggested, with the shorter one first.  But they might have been out of order in the data file.  Either way it'd be easy to trade them out.  Maybe I should try that this coming weekend.  Are there other .rnum values that can bring up these messages?

**Comment by peyre** [comment]
Ok, I _think_ I have it sorted out.  I'll commit the change and we can try it from here.  If anyone sees the message doesn't match the mission movies, please go ahead and change it to be more appropriate.
