### ISSUE TITLE
Prestige award for landing probe?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#727]
I landed a probe on the Moon, but the Americans beat me to it, so I got 9 prestige for doing it second.  However, the Satellite Building shows 4 prestige for it--any idea about this one?

![Lander probe gave 4 prestige](https://user-images.githubusercontent.com/3118014/208313740-62955176-59de-44e3-b578-e5a4a32606a4.png)

**Comment by hweimer** [comment]
It says there was an unsuccessful attempt, which should give you -5 prestige points, so 4 in total looks correct to me.

**Comment by peyre** [comment]
Oh yeah, that makes sense!  Thanks.
