### ISSUE TITLE
Could not find help entry i174

### ISSUE THREAD

**Issue by hweimer** [raceintospace/raceintospace#733]
It looks like that the help entry to warn of legacy save games (#720) got removed, possibly in 6a8c6864097ddc88fd1bc8dc6ec098efa570ec90.

**Comment by peyre** [comment]
Sorry Hendrik!  I'll get that fixed.

**Comment by peyre** [comment]
Ok, I've added it back from a previous version of help.cdr.  I've also reviewed all the entries, fixed some typos, and tightened up a few entries.

**Comment by hweimer** [comment]
Cool, thanks!
