### ISSUE TITLE
Boosted Atlas too short

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#735]
I noticed yesterday that the boosted Atlas looks kinda funny.  I'd sort-of seen it before but never took much notice of it before.  Taking a look at vab.img.0.png, sure enough--it's shorter than the regular Atlas, which seems kind of silly and looks odd in the VAB.  

This is similar to how we needed to shorten the Lapot sprite in #418, modifying the vtable.dat.  In this case of course we'd have to move the docking module down a bit.  Modifying the .png would be easy enough, but vtable kind of mystifies me.  I'd be especially puzzled where to find the _boosted_ Atlas.

![AtlasComparison](https://user-images.githubusercontent.com/3118014/212560450-9b658062-4b99-4f4d-a3fc-bce8c1d5ff5a.png)

**Comment by peyre** [comment]
Hum, it looks like the DM is 07008900 4500AF00 8B000700 DF00.  I get that the values are x1, y1, x2, y2, y offset.  However, we have 28 characters, so I don't see how this lines up.  If x1=070, y1=089,x2=004,y2=500,offset=AF0, that still leaves 0 8B000700 DF00 left over.  I'm missing something pretty simple, I expect.

**Comment by rnyoakum** [comment]
What do you mean we have 28 characters?

**Comment by peyre** [comment]
_Uh  oh!_  Looks like I misread it there.  The first 28 _entries_ are for the US, and each entry has 10 bytes.  However, in there you say that Lapot is 000001b8: f900 8400 1301 c100 0b00, and that's a bit more than 10 bytes long, unless I'm missing something.  Which wouldn't surprise me since this working with hex files is confusing!

**Comment by rnyoakum** [comment]
I'm linking to where I [discussed this](https://github.com/raceintospace/raceintospace/issues/418#issuecomment-976090413) for my own reference.

> Lapot is at 000001b8:

The entry for Lapot begins at index 000001b8 in the file; translating from hex to decimal yields 440 bytes. The Lapot is the 45th entry in the file. Each entry is 10 bytes, and the first entry begins 0 bytes into the file, so the Lapot would be found 440 bytes offset into the file.

> f900 8400 1301 c100 0b00

These 10 bytes are the data for the Lapot. It's read as five values, each a 16-bit integer (`int16_t`) value. So the Lapot data values are

- **x1**: f900
- **y1**: 8400
- **x2**: 1301
- **y2**: c100
- **yOffset**: 0b00

In the example of Lapot's x1 variable, its value is 249 in decimal form.

**Comment by peyre** [comment]
Ohoh, I get it now.  So, it looks like the boosted Atlas would be 7900 0100 8D00 3500 0000, and the DM would be 0000 3B00 5600 4800 6400.

**Comment by peyre** [comment]
Good deal.  If I set my hex editor (Okteta) to set Bytes per line to 10 (it defaults to 16), then it shows one piece of hardware per line.  Now they're easy to identify!

![vtable](https://user-images.githubusercontent.com/3118014/218329983-41a39259-47fc-4f0f-ab0c-057851f665d0.png)

**Comment by peyre** [comment]
Better now!  The rocket is the same height now, whether boosted or not.  I'll commit the changes.

![Atlas](https://user-images.githubusercontent.com/3118014/218330090-f18a9568-36c8-4685-b96c-1f057fd12910.png)
