### ISSUE TITLE
Game not giving credit for the landing

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#741]
Today I saw a resurfacing of one of my old frustrations with original BARIS that I thought was gone from RIS.  On the lunar landing, some minor thing goes wrong, and the game denies you credit for the landing.  Maybe someone is injured on recovery, but no deaths--they still came home safely.  I describe it in my guide as denying you credit because someone broke a nail getting out of the capsule.

But this time was actually worse.  I was denied credit for _two_ landings in a row due to minor failures that didn't hurt anyone.  On at least one, I think both, these missions it was that docking with the returning LM failed so they had to EVA over to the capsule.  No deaths, no injuries.  Even Apollo 11 had some of what in the game would be failed rolls.

So my "First on the Moon" was in fact the _fifth_ person on the Moon to come home safely.  First it was Overmyer and Henize, then Engle and McCay, now Weitz (followed by Evans).  I have a savegame if it will help.

![ThirdonMoon](https://user-images.githubusercontent.com/3118014/215285011-813b80d2-8fdf-41e9-984d-8ef9245695f4.png)

**Comment by hweimer** [comment]
Injuries always invalidate any prestige firsts; you might remember our lengthy discussion in #374, after which the status quo has been kept.

However, if there weren't any injuries and you completed the lunar EVA, the game should definitely award you the win, no matter what else happens during the mission. Having an emergency EVA should be fine, and I think I've also seen that working. So, feel free to send me the game (you can also add save games to bug reports if you zip them before uploading).

**Comment by hweimer** [comment]
I can reproduce the bug, and it's indeed caused by the emergency EVA. The game does not want to award prestige for emergency EVAs, but this is done in a way that a subsequent emergency EVA overwrites the credit you are supposed to get for the real one. I have to think about the best way to fix this without adding a really ugly kludge.

**Comment by peyre** [comment]
That's awesome!  So glad you're able to see the workings of this one.  Avoiding a kludge sounds like a good idea, though to my mind anything that fixes it will be welcome.

**Comment by hweimer** [comment]
My idea would be to move the lunar landing prestige (prestige code 22) to the lunar EVA (it's currently on lunar liftoff), then we could simply check whether it succeeded, as it is done for other milestones. However, there is this comment in the source code:
 https://github.com/raceintospace/raceintospace/blob/46ff5e433a7248fdf315081893a5d2c93edac705/src/game/mc2.cpp#L387-L389
Frankly speaking, I have no clue what this "good reason" is supposed to mean. The only weak reason I can see is that if you haven't done a spacewalk yet, you wouldn't get its prestige from the lunar EVA, but that's not a real concern in my opinion.

**Comment by hweimer** [comment]
I just checked, if you do an EVA in lunar orbit (e.g., during MANNED LUNAR ORBITAL LM TEST EVA), that's step "H", i.e., the same as for an EVA in earth orbit. So you cannot win the game by flying such a mission if we move the lunar landing prestige to step "P" (which is LUNAR EVA). I guess it makes sense that the two are different because they have different failures (like nauts tripping on the lunar surface).

**Comment by peyre** [comment]
Humph.  When I see something done for unspecified "good reason", I'm inclined to assume the reason wasn't _actually_ so good as they made it out to be.  However it sounds like you found the reason and it's a good one - we might want to document it in the comment.

So if I'm understanding you right, we can't fix this issue within the current mechanics - i.e., fixing it would require an ugly kludge you were hoping to avoid.

**Comment by hweimer** [comment]
No, I didn't find the reason, it's just pure speculation at this point. I was concerned that you might be able to win the game by an EVA in lunar orbit if we change the way the lunar landing prestige is awarded, but this is clearly not the case.

Of course, I could just try and see what happens, but it is difficult to investigate all corner cases (direct ascent, Soyuz L.L., etc.) that might cause unintended side effects.

**Comment by peyre** [comment]
Ah.  Well, seems to me this probably isn't specific to the spacecraft but the mission type.  We could try implementing the change and I could test-fly a number of Historical Manned Lunar Landings, maybe with DMs at like 60%.

**Comment by peyre** [comment]
That's awesome!  So glad you're able to see the workings of this one.  Avoiding a kludge sounds like a good idea, though to my mind anything that fixes it will be welcome.  Incidentally I experienced it again today:

![EVA back to capsule](https://user-images.githubusercontent.com/3118014/217628614-0d9e4089-08d7-4d98-8f57-4c8acaac3d09.png)
![EVA back to capsule - aftermath](https://user-images.githubusercontent.com/3118014/217628627-c7365203-0c87-4b16-9f6a-c75d9a76014a.png)

Which was double-extra bad because the next landing mission managed it all, except it experienced a catastrophic failure on the reentry step, setting me back at least a year.

**Comment by hweimer** [comment]
There is already an existing check during prestige evaluation of alternate branches that is supposed to deal with that, but it's not working because it requires a different StepInfo. I have removed the check for StepInfo since alternate branches are not supposed to affect prestige no matter whether the step was attempted or not. (The only exception is manned lunar orbital, which we introduced to fix #332).

**Comment by Angel-0a** [comment]
I got another one of these today. This was mission 55 - Joint Lunar Landing: EOR. It was successful except for failed docking after lunar lift-off, which resulted in successful emergency EVA. I'm not surprised I didn't get Lunar Landing achievement as I see it's a common bug but what surprises me is that I got Lunar Probe Landing achievement. In a joint lunar landing the lunar module takes off first unmanned, I wonder if this may somehow be related to this achievement for an unmanned mission being added to the party. 

![USSR landing](https://github.com/raceintospace/raceintospace/assets/48546703/6c2ae403-e123-426d-a960-62849c6b951f)

**Comment by hweimer** [comment]
@Angel-0a , I cannot reproduce this behavior. When I fly an EOR landing, the game credits the win even if the second docking fails and requires and emergency EVA. The lunar probe landing prestige should only get awarded if there is a probe in the hardware list, which is not the case for a manned lunar landing. I'd guess that the mission evaluation struct somehow got corrupted (e.g., by a botched up pointer), which is not related to this issue.
