### ISSUE TITLE
Wrong movie showing in Training screens

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#752]
I noticed this morning that Basic and Advanced Training now show one of the Atlast launch videos!

![Basic Training](https://user-images.githubusercontent.com/3118014/221431546-2ac5e411-b88b-4e13-b415-46b78eca9f1f.png)

**Comment by hweimer** [comment]
Hm, this is exactly what I tried to fix in #751. Can you confirm this behavior with the commit being applied?

**Comment by peyre** [comment]
Oh--maybe I'm running an older set of code.  I'll redownload and see if it still does it.  I just got that game crash again, the one pointing to 2954.

**Comment by peyre** [comment]
Yep, that did it!  Sorry for the dup.
