### ISSUE TITLE
Help pop-up in R&D doesn't show if mouse too low

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#753]
I've noticed that in R&D (but not Purchasing), if you click in the black box that should bring up the hardware help pop-up, if the mouse cursor is in the bottom fourth or fifth of that area it doesn't respond.  It works right in Purchasing though.  The relevant code looks right (rdplex.cpp, 742-47, 1461-66).  I know this must be something I introduced, but I sure can't find it.

![Help](https://user-images.githubusercontent.com/3118014/222922256-2d06edcb-5ca6-4be4-92a1-a3771a1516cf.png)

**Comment by rnyoakum** [comment]
I investigated, and can confirm it wasn't anything you did. The R&D control loop checks for a click on the research teams buttons before it checks for a click on the hardware image. That check for the research teams icons grabs every mouse click in that vertical band without querying the x-coordinate. It's a simple fix, I'll take care of it in the next day or two.

**Comment by peyre** [comment]
Oh thanks!  That would explain why it doesn't occur in Purchasing.

**Comment by peyre** [comment]
Very nice, thanks!
