### ISSUE TITLE
AI Prestige First closes immediately

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#754]
I noticed a strange thing this morning.  Whenever I end a turn and the AI gets a prestige first, the Prestige First screen pops up and then closes without showing the movie.  I though I might have broken something on my system, so I downloaded the code and compiled to make sure, but it's still doing it.

**Comment by hweimer** [comment]
This was a regression caused by confusing "0000" and "OOOO".

**Comment by peyre** [comment]
Ahhh, makes sense.
