### ISSUE TITLE
Super-low morale in Basic Training?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#764]
I have someone in Basic Training II who's already down to 10 morale and planning retirement!

![Poor morale in basic training](https://user-images.githubusercontent.com/3118014/229251421-18dee572-3256-40ff-866f-19abb8ae11b1.png)

I don't see a newscast saying he's announced retirement or anything.
![Newscast-0](https://user-images.githubusercontent.com/3118014/229251488-144e84e7-26a4-40a9-bf70-4304b798920e.png)
![Newscast-1](https://user-images.githubusercontent.com/3118014/229251491-fd080c37-b5c4-4c56-9cd1-8c718f7f0ff9.png)
![Newscast-2](https://user-images.githubusercontent.com/3118014/229251493-2602f87b-fe4f-4512-9cc7-14d261aa2869.png)

**Comment by sflynn850** [comment]
It's brutal, but maybe space just wasn't for him :)

Do we feel this is a bug (i.e., this shouldn't happen, but a code defect is letting it happen), or undesired behavior (working as intended, but let's change our intent), or is this one of those luck-of-the-draw things and we should keep it?

**Comment by rnyoakum** [comment]
It's definitely a bug - there isn't a path in the mood code for a recruit to drop 50+ morale points in a turn. My guess at the time was that it was an array overflow error that was around briefly and got fixed. I never saw anything like it or could figure out how to duplicate it.

**Comment by sflynn850** [comment]
Keeping this open for now in case we see it again, but tagging as low priority. I've seen it before back in the day, though, so I suspect we're chasing an issue that's persisted for some time.

**Comment by peyre** [comment]
I just saw it again!  But this time there's an explanation.

![Lovell](https://github.com/user-attachments/assets/e8873b33-cd96-4684-910c-a4a755389f28)
![Lovell 2](https://github.com/user-attachments/assets/e2e157ac-a759-48fd-8092-79235e381442)

**Comment by hweimer** [comment]
I'm pretty sure that you also got that newscast in the earlier instance.Both times the mood was exactly at 10, which is what the newscast sets it to.

**Comment by peyre** [comment]
Not that I know of.  The newscast said Cooper and Wood had declared retirement, but it was Knight who showed a 10 morale.

**Comment by hweimer** [comment]
If you get this news event (i.e, the text shown in white), the retirement announcement doesn't show up again in the astronaut news (the text shown in yellow).

**Comment by peyre** [comment]
Maybe that was it.  We could close this one I suppose, reopen it if others start seeing it without seeing something in the newscasts.
