### ISSUE TITLE
Money cheat not working

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#766]
I was testing a modified image for the Saturn rocket yesterday, and to avoid ending turn a couple times I tried the money cheat, but it wasn't working.  I don't have no_money_cheat set in my config file, and lines 1467-69 of rdplex.cpp still show

```
        } else if ((Data->P[0].AIStat > 0 || Data->P[1].AIStat > 0) && key == '$' && !options.no_money_cheat) {
            Data->P[player_index].Cash += 100;  // Cheat - add 100MB to cash on hand
            DrawCashOnHand(player_index);
```

Any idea what's gone wrong?  Is it maybe the way I used to ensure it only works in single-player mode?

**Comment by rnyoakum** [comment]
Yes, it is the check that you are using to check if there is an AI player. You check the `AIStat` attribute in the player's BuzzData, but that appears to be used for tracking AI behavior. Normally, the global variable `AI[]`, defined in game_main.cpp, is used instead. So a simple fix would be

```
} else if (key == '$' && !options.no_money_cheat && (AI[0] || AI[1])) {
```

I'll test first to make sure the fix works as expected and post it later tonight.
