### ISSUE TITLE
Mars probe got there already?

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#767]
I just launched a Mars mission, and I got the usual screen saying WILL ARRIVE IN 2 TURNS.  However the very next newscast says the mission failed.  Is that supposed to happen sometimes, like it failed early in the mission?

![Mars mission](https://user-images.githubusercontent.com/3118014/230782548-7029af73-af77-4709-b734-1666b56dfc7a.png)

**Comment by rnyoakum** [comment]
Flyby missions test against the probe's safety rating each season, at the beginning of the turn -  a sort of a duration test. If the flyby fails it displays the result in that turn's news. So, this appears to be appropriate behavior.

**Comment by peyre** [comment]
Oh!  Ok, thanks--I _wondered_ if it was expected.

**Comment by peyre** [comment]
Incidentally, this would mean that the chances of success are less for a Jupiter flyby than a Mars one, and less for Saturn than for Jupiter.
