### ISSUE TITLE
Game applied penalty when I agreed to scrub mission

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#769]
Mission Control recommended I scrub my Orbital mission.  This time I told it to, but it seems to have applied the random penalty to my Safety even though I agreed to scrub it.

![Scrubbing](https://user-images.githubusercontent.com/3118014/232333414-f49d7ef9-833f-469f-a073-eb25bd1e5985.png)

**Comment by hweimer** [comment]
This is intentional: it's the failure that downgrades the safety, not your decision to continue the mission. You just get the option to avoid further risking the lives of your 'nauts by sending them to the moon in a freshly downgraded capsule.

**Comment by peyre** [comment]
Oh, it's intended!  I wonder if we should revisit this in some way?  In this case it didn't change my flight profile--or affect my level of risk I guess--but denied me credit for the flight.  If I remember right.

**Comment by hweimer** [comment]
I'm not sure what the rationale for a change would be. If you continue, the step won't be marked as a failure and you will still get credit for it.

**Comment by peyre** [comment]
Oh that would be a problem.  It's just that on some missions where you get that, there would be no advantage to scrubbing as recommended.

**Comment by peyre** [comment]
Oh I should have closed this one.  Doing it now.
