### ISSUE TITLE
Docking Module at 62%

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#787]
I just had a (successful IIRC) docking test, and somehow my DM was raised to 62%.  Not sure how that happened, but it shouldn't be possible I don't think, at least barring some catastrophic failure involving a DM.

I have a save available if anyone wants to look at it.

![DM at 62](https://github.com/raceintospace/raceintospace/assets/3118014/c64120b6-8039-4ad7-bab4-40cf65e3b00d)

**Comment by rnyoakum** [comment]
Sure, send me the save file and I'll take a look at it.

**Comment by hweimer** [comment]
You can get docking safety values that are not multiples of 5 by encountering a code 26 failure, namely "DOCKING ATTEMPTS HAVE FAILED. CRAFT IS SPINNING WILDLY. DOCKING FAILURE." This will permanently lower the safety of the docking module by a random value between 0 and 9.

**Comment by peyre** [comment]
Really!  So this isn't a bug after all, but expected behavior.  In that case maybe I should mention it in the documentation.

**Comment by peyre** [comment]
You know, if it's just that one failure, maybe I should add a quick note to the failure itself, along the lines of the newscasts that downgrade your hardware--maybe something like 

DOCKING ATTEMPTS HAVE FAILED. CRAFT IS SPINNING WILDLY. DOCKING FAILURE. MODULE SUFFERS SMALL LOSS OF SAFETY.

Does that look like a good idea?  And--I see fails was one of the files you converted away from the old hexadecimal!  It looks fantastic as a JSON.  So if I were to make a change to it such as this, do I just change the text inside the quotes and I'm done?  I don't need to change any of the values above it because the length has changed, or whatever?

**Comment by hweimer** [comment]
Doesn't the failure screen tell you already when a component gets downgraded?

**Comment by peyre** [comment]
No, not this one at least - it just says "DOCKING ATTEMPTS HAVE FAILED. CRAFT IS SPINNING WILDLY. DOCKING FAILURE." as above.
