### ISSUE TITLE
Update Help files for menus

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#793]
I recently added the ability to back out of a screen by pressing the Escape key to a lot of the screens accessible from the Space Museum and Administration buildings, including the Preferences menu. However, at the time I did not think to update the Help or KeyHelp entries for those screens.

**Comment by peyre** [comment]
I should probably do this one myself; I have several updates I'd like to make to the help file, so we could get a twofer here.

**Comment by peyre** [comment]
Ok, I've added it to Administration and Space Museum, among other changes.
