### ISSUE TITLE
Retiring astronauts are not shown in menus

### ISSUE THREAD

**Issue by rnyoakum** [raceintospace/raceintospace#813]
Actually, they are, but their names are in black on a black background so you can't read them. But they still take up a slot and it looks really weird. This should be changed. I was thinking they should use the standard grey background color for text when on a black background, but don't have a strong opinion. But if there was a good color that would work on both the black and grey backgrounds, however, I reckon that would be the better option.

**Comment by peyre** [comment]
Oh Scheiße, that was probably my doing.  Where is it exactly?

**Comment by peyre** [comment]
Ah, like this?  I'll try changing it to brown or something.

**Comment by peyre** [comment]
Hm, here's brown.

![Brown](https://github.com/raceintospace/raceintospace/assets/3118014/cf22031a-5c68-42ec-b046-523b703a649b)

**Comment by peyre** [comment]
Navy blue's not really great.

![Blue](https://github.com/raceintospace/raceintospace/assets/3118014/d3d7b868-c235-4f9f-b0b1-6fc6a63bb60b)

**Comment by peyre** [comment]
Green:

![Green](https://github.com/raceintospace/raceintospace/assets/3118014/8e0a2a4b-db07-4091-bf9a-08065a277be5)

**Comment by peyre** [comment]
And Red:

![Red](https://github.com/raceintospace/raceintospace/assets/3118014/2f0aeb8d-a2a3-4451-8328-0fe034efbcd7)

**Comment by peyre** [comment]
And color 35.  My color blindness is hindering me here a little in identifying it.

![35](https://github.com/raceintospace/raceintospace/assets/3118014/3bff5315-a9f9-4b30-aee8-605af42fe9f1)
