### ISSUE TITLE
Core dump!

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#821]
I was playing as the Soviets and crashed.  Looking over at my terminal window, I see the following:

WARNING /home/leon/raceintospace/src/game/fs.cpp:279:try_find_file	can't find file 'RREC_12.ogg' in audio dir(s)
WARNING /home/leon/raceintospace/src/game/fs.cpp:279:try_find_file	can't find file 'NONE.ogg' in audio dir(s)
unhandled exception: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
Aborted (core dumped)

Now, I have replaced some of the mission movies (those for N1 and UR-700 launches), but I don't think that's relevant since I haven't prototyped either of those rockets.

**Comment by peyre** [comment]
I've rerun the game from autosave several times, but I can't get it to crash again.  I think it crashed during my orbital duration mission, but don't recall on which step.

**Comment by peyre** [comment]
Aha!  Got it to happen again.  This time I was paying more attention.  It happened when I transferred all the cosmonauts to the Soyuz program, but using the old TRANSFER COSMONAUT button, not SEND ALL.

unhandled exception: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
Aborted (core dumped)

**Comment by hweimer** [comment]
I can reproduce this bug. It occurs when there are no nauts in the complex left and you press on the TRANSFER NAUT button. Here's the offending line:
```
#4  0x0000555555695fef in Limbo (plr=0 '\000') at ast2.cpp:490
490	                Data->P[plr].Pool[AstroList.at(now2)].Assign = i + 1;

```
now2 is 0, as this is where the cursor points to when there are no nauts in the complex. However, there are no entries in AstroList, causing the exception. I think the solution should be to wrap a test for AstroList.size() being nonzero around the block, but I have to run some tests to see whether this creates other issues.

**Comment by alsed** [comment]
I have recently encounter these same issue.

If you pressed the arrows in the box where the astronauts are listed, _when there are not astronauts_  (AstroList.size() = 0),  the game crashes.
```
unhandled exception: vector::_M_range_check: __n (which is 1) >= this->size() (which is 0)
`gmake[3]: *** [CMakeFiles/run.dir/build.make:70: CMakeFiles/run] Aborted (core dumped)
```
There are two instances when this happens, when arrow down is pressed or when the roster box is pressed. 
To resolve this problem, a previous condition that checks size for AstroList before enabling the buttons has been added. 
Arrow up button it's also included in the check to avoid animate it when there are no astronauts. Transfer and send-all buttons are also disabled in this condition, to add consistency to the behaviour of the screen.

Also, If you go to astro complex and there are no nauts available, a pop up window informs you that they are none unassigned nauts.
