### ISSUE TITLE
Blank lines missing in help.json

### ISSUE THREAD

**Issue by hweimer** [raceintospace/raceintospace#828]
per #823:
>@peyre: Uh oh, the new JSON format seems to have removed blank lines from the help file. I wouldn't object to fixing it myself if I knew how to do it properly.

The underlying problem is that data_decoder uses strtok(), which treats multiple newlines as a single delimiter.

**Comment by peyre** [comment]
Ah.  Is there a command to insert a line, like HTML's <br/> ?

**Comment by hweimer** [comment]
"YOU HAVE MISSIONS SCHEDULED...",
"",
"DO YOU.WISH..."

should insert a blank line in between the two sentences.

**Comment by peyre** [comment]
Fantastic!  I'd be glad to insert the carriage returns.

**Comment by peyre** [comment]
All right, I've added the spaces back and recompiled.  However, when the game opens it immediately abends:

`unhandled exception: rapidjson internal assertion failure: IsObject()
Aborted (core dumped)`

**Comment by hweimer** [comment]
Yeah, the error indicates a malformed JSON file. I'm glad that you managed to fix it, in such cases it can also be helpful to run the file through a JSON validator.
