### ISSUE TITLE
Visiting R&D Building takes you to the wrong place

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#839]
I've noticed this lately, and just pinned it down.

In R&D, if you visit the Purchasing Facility, then go to one of the other sections (Rockets, Capsule, or Misc), then hit the button to Visit the R&D Facility, it takes you to R&D for the previous section.  So if you were in Rockets, hitting the button takes you to R&D for Unmanned.  If you were in Capsule, hitting the button takes you to R&D for Rockets.

![Weirdness in R D-Purchasing](https://github.com/raceintospace/raceintospace/assets/3118014/a8d0404b-4d55-45ac-b217-3c52ac0320ea)

I've been having a look in rdplex.cpp, comparing the code for the buttons between R&D and Purchasing, and I don't see what could be causing this.

**Comment by rnyoakum** [comment]
The explanation is that this used global variables for tracking the selected hardware when moving between R&D and Hardware Purchasing. I changed (85eeb0b6cd988d109243bb391dd78b327114f2ae) it so the current program would be passed as arguments so _going_ to the other building would preserve the selected hardware, but I improperly handled returning _back_ to the initial building.
