### ISSUE TITLE
Purchase button not animating

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#841]
I just noticed that when you press P in Purchasing, rather than the Purchase Equipment button, the button doesn't animate.  I can't see why: the button animation statements follow the (if the mouse was clicked while in this area || key == 'P' " statement.

![Purchasing](https://github.com/raceintospace/raceintospace/assets/3118014/1c7299f7-c70e-4419-a36b-ec674dac6c62)

**Comment by rnyoakum** [comment]
It's a simple issue - there is no delay() call between drawing the button being pressed and popping back up. With the mouse, you have to wait until the button is released, so the mechanical act of clicking creates a perceptible delay. With the keyboard, there's no wait on the mouse so the 'pressed' state is drawn over immediately.  I'll post the fix within the hour (I'm fixing #839 as well).

**Comment by peyre** [comment]
I'm excited to see you're working on not one, but two issues!  I had thought we were in a lull and no one was doing much with the game.
