### ISSUE TITLE
Weird catastrophic failure

### ISSUE THREAD

**Issue by peyre** [raceintospace/raceintospace#847]
Saw something just now I'd never seen before.  This must be a very obscure bug to have not happened to me before now, so it may be something we don't care to address - but I thought I'd report it.

I flew an EOR Lunar Landing, and experienced a failure on the TLI step that only shows one crew member.
![One crew member killed](https://github.com/raceintospace/raceintospace/assets/3118014/71f282ef-1c7d-4e7a-9d77-01b57cbb028d)

Why only one crew member?  But then it tells me they were all killed. Odd.
![One crew member killed end](https://github.com/raceintospace/raceintospace/assets/3118014/ec9b3088-7c34-4b7d-842e-dfe0c69d75f6)

And yet they're still there in the Apollo Program!  In fact they were still there when I won the game.
![One crew member killed still there](https://github.com/raceintospace/raceintospace/assets/3118014/c7027d9f-b23d-4688-a179-1f4a537c691c)

**Comment by hweimer** [comment]
This is an error in the mission string. For mission 55 (JT LUNAR LANDING: EOR), we have `+1ABC+2ABF+1IJ+2OL+1RUSQPT+2M+1I+2KNg+2DE!OLd+2Hd|`
The closest equivalent is mission 52 (JT MANNED LUNAR ORBITAL LM TEST: EOR), which has
`+1ABC+2ABF+1I+2JOL+2M+1QaI+2KNg+2DE!OLd+2Hd`
You can see that the first one has +1IJ+, which means that both docking and TLI are handled by the hardware launched from the first pad. In contrast, the second string has +1I+2J..., which means that the hardware is switched back to the second pad before TLI. The first pad has the LM and neither a capsule nor any nauts that can be killed.

**Comment by hweimer** [comment]
I just checked, this bug has been present since the original release. But funnily, that's not the oldest LM-related bug that got fixed this week: https://martincmartin.com/2024/06/14/how-i-found-a-55-year-old-bug-in-the-first-lunar-lander-game/

**Comment by peyre** [comment]
Whoa that's a lot of math!  Good spotting on that, and you're right; the timing is a nice coincidence.

Thanks for fixing this one, by the way.  It's such an obscure one I didn't think anyone would be able to track it down.  Must mention this on our Mastodon account.
