### ISSUE TITLE
Is wh.ogg broken?

### ISSUE THREAD

**Issue by Alsed** [raceintospace/raceintospace#871]
In audio/mission there is wh.ogg which is noticeable more small in size that the other audio files.
When I try to reproduce it, the media player informs there is no sound to play.

I've tracked the original sound file in BARIS, is a RAW file (file zip attached)  
[WH.zip](https://github.com/user-attachments/files/15901236/WH.zip)

It can be played online it in this site (it's kind of a stomp sound):
https://www.francogarcia.com/en/tools/raw-audio-player/

I also have try to re-convert it using raw2ogg (wich uses oggenc) but again the output ogg doesn't play anything.

**Comment by peyre** [comment]
Huh!  Good spotting, I think.  I'm not sure where this sound is used in the game; I can't find a reference to it in the code.

I'm able to play audio/mission/wh.ogg in Audacious.  It's a single tap, sounds a bit like the very beginning of elephant.ogg.

Not sure what wh.ogg is supposed to be for, or if we need it.

**Comment by Alsed** [comment]
Hi Peyre, you couldn't find wh.ogg it in the code because i changed the function that played the audio file, but you can find it in  [/src/game/mis_c.cpp  (Line 498)](https://github.com/raceintospace/raceintospace/blob/dc3e795723715bdda679f24cce77504f5f9f765f/src/game/mis_c.cpp#L498)

` if (!IsChannelMute(AV_SOUND_CHANNEL)) {
        if (lnch == 0) {
            play_audio("wh", 0);
        }`

Is inside the function `PlaySequence` that supposedly finds the proper video for the current mission step, and plays it. 
So is most certain that this sound should play in the control room during a mission ( a cancellation maybe?).
I didn't try in Audacious, which was an obvious choice. I should assume that works properly then.
